## Named-Targets M1 test fixtures for
## ``t_engine_multiple_outputs_produce_multiple_names``.
##
## The ``gccCompile`` typed-tool exposes both ``output`` and ``makeDep``
## flags and declares ``outputs output makeDep``. A single call
## ``gccCompile.compile(output = "foo.o", makeDep = "foo.d")`` then
## carries TWO implicit names — ``"foo"`` from ``foo.o`` (``.o``
## stripped) and ``"foo"`` from ``foo.d`` (``.d`` stripped). Both
## extensions are in the M1 basename-rule extension list. The two
## rows in the target-export table both carry the name ``"foo"`` and
## point at the same edge handle.
##
## Naming note: the milestone spec text uses ``depfile`` as the second
## flag name on the fixture. The typed-tool wrapper proc generated by
## ``defineCliInterface`` already reserves the formal parameter name
## ``depfile`` for its make-depfile annotation (see
## ``toolActionWrapperCode`` in ``macros_a.nim``), so a user-declared
## flag of the same name collides. The fixture renames it to
## ``makeDep`` while preserving every property the spec exercises:
## the second output flag carries a ``.d``-suffixed value, the
## basename rule strips ``.d``, and the resulting ``targetNames`` is
## the canonical ``@["foo", "foo"]`` pair.

import repro_project_dsl

defineCliInterface gccCompile, "test-gccCompile":
  subcmd "compile":
    flag output is string,
      alias = "-o",
      role = output,
      required = true
    flag makeDep is string,
      alias = "-MF",
      role = output,
      required = true
    pos source is string,
      role = input,
      position = 0
    outputs output makeDep

package tEngineMultipleOutputsPkg:
  uses:
    "gcc >=1"
  build:
    discard gccCompile.compile(source = "foo.c", output = "foo.o",
      makeDep = "foo.d", actionId = "compile-foo")

export gccCompile
export buildTEngineMultipleOutputsPkgPackage
