version = "0.1.0"
author = "Metacraft Labs"
description = "Reprobuild profile-compile build-graph edge (M83 Phase C)"
license = "MIT"
srcDir = "src"
requires "nim >= 2.2.0"
requires "blake3"
requires "repro_core"
requires "repro_hash"
requires "repro_build_engine"
requires "repro_profile"
requires "repro_profile_intent"
