# AUTO-GENERATED by scripts/generate_test_edges.nim — do not edit by hand.
# Regenerate with: nim r scripts/generate_test_edges.nim
#
# This module is a plain Nim module exporting a single const,
# ``reprobuildTestSpecs*``: a ``seq[TestSpec]`` table of every
# discovered Nim ``unittest`` test binary in the repository.
#
# ``repro.nim`` ``import``s this module and iterates the table
# inside its ``package reprobuild: build:`` block, calling
# ``buildNimUnittest.build(...)`` once per spec. The returned
# build-edge actions are then aggregated into the ``test``
# target so ``repro build test`` schedules every test-binary
# compilation in one engine pass.
#
# Tests that need ``--define:reproProviderMode`` at compile
# time carry the define in their ``TestSpec.defines`` field.
# The adapter wires each entry as ``--define:<name>`` on the
# underlying ``nim c`` invocation, so the build is fully routed
# through the typed-output edge graph (no path-based shell
# carry-forward needed).
#
# Project-DSL-Composition M6 migration: the previous shape
# emitted a ``build:`` block ``include``-d from ``repro.nim``,
# which the package macro silently dropped. The data-table
# shape lifts the registration into the caller, so the macro
# sees every typed-tool call.

type
  TestSpec* = object
    ## One row of the test-suite table. ``source`` is the
    ## repo-relative path to the ``.nim`` test file;
    ## ``binary`` is the repo-relative output binary path;
    ## ``defines`` is the per-test ``-d:`` flag list passed
    ## through to ``buildNimUnittest.build``.
    source*: string
    binary*: string
    defines*: seq[string]

const reprobuildTestSpecs*: seq[TestSpec] = @[
  TestSpec(
    source: "libs/repro_build_engine/tests/t_engine_action_create_dyndep.nim",
    binary: "build/test-bin/t_engine_action_create_dyndep",
    defines: @[]),
  TestSpec(
    source: "libs/repro_build_engine/tests/t_engine_implicit_target_name_basename_rule.nim",
    binary: "build/test-bin/t_engine_implicit_target_name_basename_rule",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_build_engine/tests/t_engine_implicit_target_name_hook_overrides_canonical.nim",
    binary: "build/test-bin/t_engine_implicit_target_name_hook_overrides_canonical",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_build_engine/tests/t_engine_method_call_on_typed_field_emits_execution_edge.nim",
    binary: "build/test-bin/t_engine_method_call_on_typed_field_emits_execution_edge",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_build_engine/tests/t_engine_multiple_outputs_produce_multiple_names.nim",
    binary: "build/test-bin/t_engine_multiple_outputs_produce_multiple_names",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_build_engine/tests/t_engine_target_export_table_records_ambiguity.nim",
    binary: "build/test-bin/t_engine_target_export_table_records_ambiguity",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_build_engine/tests/t_engine_typed_output_recorded_in_normalized_graph.nim",
    binary: "build/test-bin/t_engine_typed_output_recorded_in_normalized_graph",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_cli_support/tests/t_partition_plan_json_round_trip.nim",
    binary: "build/test-bin/t_partition_plan_json_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_cli_support/tests/t_partition_planner_degrades_gracefully_on_cold_cache.nim",
    binary: "build/test-bin/t_partition_planner_degrades_gracefully_on_cold_cache",
    defines: @[]),
  TestSpec(
    source: "libs/repro_cli_support/tests/t_partition_planner_reads_runquota_estimates.nim",
    binary: "build/test-bin/t_partition_planner_reads_runquota_estimates",
    defines: @[]),
  TestSpec(
    source: "libs/repro_cli_support/tests/test_m10_home_gc_cli.nim",
    binary: "build/test-bin/test_m10_home_gc_cli",
    defines: @[]),
  TestSpec(
    source: "libs/repro_cli_support/tests/test_m2_env_ps1_migration_clean.nim",
    binary: "build/test-bin/test_m2_env_ps1_migration_clean",
    defines: @[]),
  TestSpec(
    source: "libs/repro_cli_support/tests/test_m69_home_add_versioned.nim",
    binary: "build/test-bin/test_m69_home_add_versioned",
    defines: @[]),
  TestSpec(
    source: "libs/repro_cli_support/tests/test_m70_migrate_from_env_scripts.nim",
    binary: "build/test-bin/test_m70_migrate_from_env_scripts",
    defines: @[]),
  TestSpec(
    source: "libs/repro_cmake_trycompile/tests/test_envelope_v3.nim",
    binary: "build/test-bin/test_envelope_v3",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_convention_attribution.nim",
    binary: "build/test-bin/t_convention_attribution",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_cpp_dep_scanner.nim",
    binary: "build/test-bin/t_cpp_dep_scanner",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_deps_refresh_check.nim",
    binary: "build/test-bin/t_deps_refresh_check",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_go_dep_scanner.nim",
    binary: "build/test-bin/t_go_dep_scanner",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_jsts_dep_scanner.nim",
    binary: "build/test-bin/t_jsts_dep_scanner",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_nim_dep_scanner.nim",
    binary: "build/test-bin/t_nim_dep_scanner",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_project_file_alias.nim",
    binary: "build/test-bin/t_project_file_alias",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_python_dep_scanner.nim",
    binary: "build/test-bin/t_python_dep_scanner",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_rust_dep_scanner.nim",
    binary: "build/test-bin/t_rust_dep_scanner",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_show_conventions_cli.nim",
    binary: "build/test-bin/t_show_conventions_cli",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_show_conventions_manual_deps.nim",
    binary: "build/test-bin/t_show_conventions_manual_deps",
    defines: @[]),
  TestSpec(
    source: "libs/repro_core/tests/t_smoke_repro_core.nim",
    binary: "build/test-bin/t_smoke_repro_core",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/t_m67_bulk_catalog.nim",
    binary: "build/test-bin/t_m67_bulk_catalog",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/t_m68_baseline_catalog.nim",
    binary: "build/test-bin/t_m68_baseline_catalog",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/t_m8_bulk_catalog.nim",
    binary: "build/test-bin/t_m8_bulk_catalog",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/t_smoke_catalog_audit_m29.nim",
    binary: "build/test-bin/t_smoke_catalog_audit_m29",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/t_smoke_configurables.nim",
    binary: "build/test-bin/t_smoke_configurables",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/t_smoke_generated_config.nim",
    binary: "build/test-bin/t_smoke_generated_config",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/t_versioned_provisioning_schema.nim",
    binary: "build/test-bin/t_versioned_provisioning_schema",
    defines: @[]),
  TestSpec(
    source: "libs/repro_dsl_stdlib/tests/test_m69_package_macro.nim",
    binary: "build/test-bin/test_m69_package_macro",
    defines: @[]),
  TestSpec(
    source: "libs/repro_elevation/tests/t_smoke_repro_elevation.nim",
    binary: "build/test-bin/t_smoke_repro_elevation",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_adapter_chain.nim",
    binary: "build/test-bin/t_adapter_chain",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter.nim",
    binary: "build/test-bin/t_builtin_adapter",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_7z_nested.nim",
    binary: "build/test-bin/t_builtin_adapter_7z_nested",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_7z_sfx_flatten.nim",
    binary: "build/test-bin/t_builtin_adapter_7z_sfx_flatten",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_installer.nim",
    binary: "build/test-bin/t_builtin_adapter_installer",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_installer_innosetup_fpc.nim",
    binary: "build/test-bin/t_builtin_adapter_installer_innosetup_fpc",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_installer_nsis_erlang.nim",
    binary: "build/test-bin/t_builtin_adapter_installer_nsis_erlang",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_launcher_emit_composer.nim",
    binary: "build/test-bin/t_builtin_adapter_launcher_emit_composer",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_msys2.nim",
    binary: "build/test-bin/t_builtin_adapter_msys2",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_builtin_adapter_pre_install_runner.nim",
    binary: "build/test-bin/t_builtin_adapter_pre_install_runner",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_home_gc.nim",
    binary: "build/test-bin/t_home_gc",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_junction_aware_remove.nim",
    binary: "build/test-bin/t_junction_aware_remove",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_plan_topological_sort.nim",
    binary: "build/test-bin/t_plan_topological_sort",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_preview_chain.nim",
    binary: "build/test-bin/t_preview_chain",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_realize_honors_adapter_preference.nim",
    binary: "build/test-bin/t_realize_honors_adapter_preference",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_realize_honors_requested_version.nim",
    binary: "build/test-bin/t_realize_honors_requested_version",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/t_smoke_home_apply.nim",
    binary: "build/test-bin/t_smoke_home_apply",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m1_fpc_resolves.nim",
    binary: "build/test-bin/test_m1_fpc_resolves",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m25_adapter_preference_parse.nim",
    binary: "build/test-bin/test_m25_adapter_preference_parse",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m25_adapter_preference_plumbed.nim",
    binary: "build/test-bin/test_m25_adapter_preference_plumbed",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m25_adapter_preference_text_macro_parity.nim",
    binary: "build/test-bin/test_m25_adapter_preference_text_macro_parity",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m69_apply_end_to_end.nim",
    binary: "build/test-bin/test_m69_apply_end_to_end",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m69_catalog_lookup.nim",
    binary: "build/test-bin/test_m69_catalog_lookup",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m69_env_export.nim",
    binary: "build/test-bin/test_m69_env_export",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_apply/tests/test_m69_env_userpath_multi_package.nim",
    binary: "build/test-bin/test_m69_env_userpath_multi_package",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_generations/tests/t_smoke_home_generations.nim",
    binary: "build/test-bin/t_smoke_home_generations",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_intent/tests/t_smoke_home_intent.nim",
    binary: "build/test-bin/t_smoke_home_intent",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_resources/tests/t_registry_root_override.nim",
    binary: "build/test-bin/t_registry_root_override",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_resources/tests/t_smoke_home_resources.nim",
    binary: "build/test-bin/t_smoke_home_resources",
    defines: @[]),
  TestSpec(
    source: "libs/repro_home_rollback/tests/t_smoke_home_rollback.nim",
    binary: "build/test-bin/t_smoke_home_rollback",
    defines: @[]),
  TestSpec(
    source: "libs/repro_homebrew_adapter/tests/t_smoke_repro_homebrew_adapter.nim",
    binary: "build/test-bin/t_smoke_repro_homebrew_adapter",
    defines: @[]),
  TestSpec(
    source: "libs/repro_infra/tests/t_smoke_repro_infra.nim",
    binary: "build/test-bin/t_smoke_repro_infra",
    defines: @[]),
  TestSpec(
    source: "libs/repro_interface_artifacts/tests/t_multi_package_merge.nim",
    binary: "build/test-bin/t_multi_package_merge",
    defines: @[]),
  TestSpec(
    source: "libs/repro_interface_artifacts/tests/test_library_codec_roundtrip.nim",
    binary: "build/test-bin/test_library_codec_roundtrip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_launch_plan/tests/t_codec_smoke.nim",
    binary: "build/test-bin/t_codec_smoke",
    defines: @[]),
  TestSpec(
    source: "libs/repro_local_store/tests/t_sqlite_smoke.nim",
    binary: "build/test-bin/t_sqlite_smoke",
    defines: @[]),
  TestSpec(
    source: "libs/repro_monitor_shim/tests/t_dispatch_mechanism_coverage_windows.nim",
    binary: "build/test-bin/t_dispatch_mechanism_coverage_windows",
    defines: @[]),
  TestSpec(
    source: "libs/repro_monitor_shim/tests/t_install_audit_zero_failures_windows.nim",
    binary: "build/test-bin/t_install_audit_zero_failures_windows",
    defines: @[]),
  TestSpec(
    source: "libs/repro_monitor_shim/tests/t_windows_hook_registry.nim",
    binary: "build/test-bin/t_windows_hook_registry",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_action_cache_reader_consults_peer_on_miss.nim",
    binary: "build/test-bin/t_peer_cache_action_cache_reader_consults_peer_on_miss",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_admin_cli_status.nim",
    binary: "build/test-bin/t_peer_cache_admin_cli_status",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_advertise_v1_decoded_as_v2.nim",
    binary: "build/test-bin/t_peer_cache_advertise_v1_decoded_as_v2",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_advertise_v2_codec_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_advertise_v2_codec_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_bearssl_200_peer_tls_convergence.nim",
    binary: "build/test-bin/t_peer_cache_bearssl_200_peer_tls_convergence",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_bearssl_ecdsa_smoke.nim",
    binary: "build/test-bin/t_peer_cache_bearssl_ecdsa_smoke",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_bearssl_tls_context_smoke.nim",
    binary: "build/test-bin/t_peer_cache_bearssl_tls_context_smoke",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_bearssl_tls_partition_recovery.nim",
    binary: "build/test-bin/t_peer_cache_bearssl_tls_partition_recovery",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_cert_validity_window_enforced.nim",
    binary: "build/test-bin/t_peer_cache_cert_validity_window_enforced",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_cli_lan_spec_enables_multicast.nim",
    binary: "build/test-bin/t_peer_cache_cli_lan_spec_enables_multicast",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_cli_lan_tls_query.nim",
    binary: "build/test-bin/t_peer_cache_cli_lan_tls_query",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_codec_frame_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_codec_frame_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_codec_version_mismatch_rejected.nim",
    binary: "build/test-bin/t_peer_cache_codec_version_mismatch_rejected",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_connection_pool_eviction_lru.nim",
    binary: "build/test-bin/t_peer_cache_connection_pool_eviction_lru",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_cuckoo_filter_delete_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_cuckoo_filter_delete_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_cuckoo_filter_false_positive_rate.nim",
    binary: "build/test-bin/t_peer_cache_cuckoo_filter_false_positive_rate",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_ecdsa_sign_verify_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_ecdsa_sign_verify_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_ecdsa_signed_advertisement_tamper_rejection.nim",
    binary: "build/test-bin/t_peer_cache_ecdsa_signed_advertisement_tamper_rejection",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_ecdsa_trust_anchor_file_format.nim",
    binary: "build/test-bin/t_peer_cache_ecdsa_trust_anchor_file_format",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_event_stream_jsonl_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_event_stream_jsonl_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_fetch_corrupted_payload_rejected.nim",
    binary: "build/test-bin/t_peer_cache_fetch_corrupted_payload_rejected",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_fetch_loopback_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_fetch_loopback_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_fetch_oversize_truncated_flag.nim",
    binary: "build/test-bin/t_peer_cache_fetch_oversize_truncated_flag",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_find_peers_with_blob_uses_filter.nim",
    binary: "build/test-bin/t_peer_cache_find_peers_with_blob_uses_filter",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_handshake_rejects_unknown_peer_id.nim",
    binary: "build/test-bin/t_peer_cache_handshake_rejects_unknown_peer_id",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_loopback_three_peer_discovery.nim",
    binary: "build/test-bin/t_peer_cache_loopback_three_peer_discovery",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_metrics_prometheus_format.nim",
    binary: "build/test-bin/t_peer_cache_metrics_prometheus_format",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_mint_cert_ca_signed_chain.nim",
    binary: "build/test-bin/t_peer_cache_mint_cert_ca_signed_chain",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_mint_cert_self_signed_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_mint_cert_self_signed_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_multicast_cidr_allowlist_drops_off_network.nim",
    binary: "build/test-bin/t_peer_cache_multicast_cidr_allowlist_drops_off_network",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_multicast_loopback_discovery.nim",
    binary: "build/test-bin/t_peer_cache_multicast_loopback_discovery",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_registry_advertise_snapshot_and_delta.nim",
    binary: "build/test-bin/t_peer_cache_registry_advertise_snapshot_and_delta",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_self_signed_cert_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_self_signed_cert_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_sim_fetch_workload_hits_peer_cache.nim",
    binary: "build/test-bin/t_peer_cache_sim_fetch_workload_hits_peer_cache",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_sim_mixed_tenant_isolation.nim",
    binary: "build/test-bin/t_peer_cache_sim_mixed_tenant_isolation",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_sim_report_renders_markdown.nim",
    binary: "build/test-bin/t_peer_cache_sim_report_renders_markdown",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_simulation_200_peer_convergence.nim",
    binary: "build/test-bin/t_peer_cache_simulation_200_peer_convergence",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_simulation_partition_recovery.nim",
    binary: "build/test-bin/t_peer_cache_simulation_partition_recovery",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_swim_50_peer_convergence.nim",
    binary: "build/test-bin/t_peer_cache_swim_50_peer_convergence",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_swim_dissemination_piggyback.nim",
    binary: "build/test-bin/t_peer_cache_swim_dissemination_piggyback",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_swim_incarnation_self_refute.nim",
    binary: "build/test-bin/t_peer_cache_swim_incarnation_self_refute",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_swim_indirect_probe_K_3.nim",
    binary: "build/test-bin/t_peer_cache_swim_indirect_probe_K_3",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_swim_partition_recovery.nim",
    binary: "build/test-bin/t_peer_cache_swim_partition_recovery",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tier2_central_fallthrough.nim",
    binary: "build/test-bin/t_peer_cache_tier2_central_fallthrough",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tier2_eviction_policy.nim",
    binary: "build/test-bin/t_peer_cache_tier2_eviction_policy",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tier2_inter_rack_advertisement.nim",
    binary: "build/test-bin/t_peer_cache_tier2_inter_rack_advertisement",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tier2_preferred_in_fetch_order.nim",
    binary: "build/test-bin/t_peer_cache_tier2_preferred_in_fetch_order",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_application_data_flows_through_tunnel.nim",
    binary: "build/test-bin/t_peer_cache_tls_application_data_flows_through_tunnel",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_handshake_rejects_unknown_cert.nim",
    binary: "build/test-bin/t_peer_cache_tls_handshake_rejects_unknown_cert",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_handshake_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_tls_handshake_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_handshake_validates_cert_chain.nim",
    binary: "build/test-bin/t_peer_cache_tls_handshake_validates_cert_chain",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_mixed_mode_compat.nim",
    binary: "build/test-bin/t_peer_cache_tls_mixed_mode_compat",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_per_tenant_ca_isolation.nim",
    binary: "build/test-bin/t_peer_cache_tls_per_tenant_ca_isolation",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_per_tenant_isolation.nim",
    binary: "build/test-bin/t_peer_cache_tls_per_tenant_isolation",
    defines: @[]),
  TestSpec(
    source: "libs/repro_peer_cache/tests/t_peer_cache_tls_signed_advertisement_round_trip.nim",
    binary: "build/test-bin/t_peer_cache_tls_signed_advertisement_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_profile/tests/t_smoke_repro_profile.nim",
    binary: "build/test-bin/t_smoke_repro_profile",
    defines: @[]),
  TestSpec(
    source: "libs/repro_profile_compile/tests/t_smoke_apply_integration.nim",
    binary: "build/test-bin/t_smoke_apply_integration",
    defines: @[]),
  TestSpec(
    source: "libs/repro_profile_compile/tests/t_smoke_module_imports.nim",
    binary: "build/test-bin/t_smoke_module_imports",
    defines: @[]),
  TestSpec(
    source: "libs/repro_profile_compile/tests/t_smoke_profile_adapter.nim",
    binary: "build/test-bin/t_smoke_profile_adapter",
    defines: @[]),
  TestSpec(
    source: "libs/repro_profile_compile/tests/t_smoke_repro_profile_compile.nim",
    binary: "build/test-bin/t_smoke_repro_profile_compile",
    defines: @[]),
  TestSpec(
    source: "libs/repro_profile_compile/tests/t_smoke_system_apply_integration.nim",
    binary: "build/test-bin/t_smoke_system_apply_integration",
    defines: @[]),
  TestSpec(
    source: "libs/repro_profile_intent/tests/t_smoke_repro_profile_intent.nim",
    binary: "build/test-bin/t_smoke_repro_profile_intent",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_executable_cli_only_no_build.nim",
    binary: "build/test-bin/t_dsl_executable_cli_only_no_build",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_implicit_target_name_hook_compiles.nim",
    binary: "build/test-bin/t_dsl_implicit_target_name_hook_compiles",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_m5_composition_smoke.nim",
    binary: "build/test-bin/t_dsl_m5_composition_smoke",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_m6_test_suite_smoke.nim",
    binary: "build/test-bin/t_dsl_m6_test_suite_smoke",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_forward_reference_error.nim",
    binary: "build/test-bin/t_dsl_outputs_forward_reference_error",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_lexical_scope_parent_subcmd.nim",
    binary: "build/test-bin/t_dsl_outputs_lexical_scope_parent_subcmd",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_lexical_scope_root_flag_inherited.nim",
    binary: "build/test-bin/t_dsl_outputs_lexical_scope_root_flag_inherited",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_multiple_flags_one_statement.nim",
    binary: "build/test-bin/t_dsl_outputs_multiple_flags_one_statement",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_sibling_scope_invisible_error.nim",
    binary: "build/test-bin/t_dsl_outputs_sibling_scope_invisible_error",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_statement_basic_accepted.nim",
    binary: "build/test-bin/t_dsl_outputs_statement_basic_accepted",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_statements_accumulate.nim",
    binary: "build/test-bin/t_dsl_outputs_statements_accumulate",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_typed_complex_path_expression.nim",
    binary: "build/test-bin/t_dsl_outputs_typed_complex_path_expression",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_typed_field_emitted_on_subtype.nim",
    binary: "build/test-bin/t_dsl_outputs_typed_field_emitted_on_subtype",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_typed_form_parsed.nim",
    binary: "build/test-bin/t_dsl_outputs_typed_form_parsed",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_typed_multiple_interfaces.nim",
    binary: "build/test-bin/t_dsl_outputs_typed_multiple_interfaces",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_unknown_flag_error.nim",
    binary: "build/test-bin/t_dsl_outputs_unknown_flag_error",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_dsl_outputs_untyped_form_unchanged.nim",
    binary: "build/test-bin/t_dsl_outputs_untyped_form_unchanged",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_engine_path_expression_uses_flag_value.nim",
    binary: "build/test-bin/t_engine_path_expression_uses_flag_value",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_engine_typed_output_field_populated_at_action_emission.nim",
    binary: "build/test-bin/t_engine_typed_output_field_populated_at_action_emission",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_engine_typed_output_payload_codec_round_trip.nim",
    binary: "build/test-bin/t_engine_typed_output_payload_codec_round_trip",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/t_multi_package_macro.nim",
    binary: "build/test-bin/t_multi_package_macro",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/test_depends_on_macro.nim",
    binary: "build/test-bin/test_depends_on_macro",
    defines: @[]),
  TestSpec(
    source: "libs/repro_project_dsl/tests/test_library_macro.nim",
    binary: "build/test-bin/test_library_macro",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_clingo_smoke.nim",
    binary: "build/test-bin/t_clingo_smoke",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_solve_variants_end_to_end.nim",
    binary: "build/test-bin/t_solve_variants_end_to_end",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_solve_variants_unsatisfiable.nim",
    binary: "build/test-bin/t_solve_variants_unsatisfiable",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_variant_encoder_bool_universe.nim",
    binary: "build/test-bin/t_variant_encoder_bool_universe",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_variant_encoder_conflicts.nim",
    binary: "build/test-bin/t_variant_encoder_conflicts",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_variant_encoder_enum_universe.nim",
    binary: "build/test-bin/t_variant_encoder_enum_universe",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_variant_encoder_priorities.nim",
    binary: "build/test-bin/t_variant_encoder_priorities",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_variant_encoder_propagates.nim",
    binary: "build/test-bin/t_variant_encoder_propagates",
    defines: @[]),
  TestSpec(
    source: "libs/repro_solver/tests/t_variant_encoder_requires.nim",
    binary: "build/test-bin/t_variant_encoder_requires",
    defines: @[]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_ada_direct_convention.nim",
    binary: "build/test-bin/test_ada_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_c_cpp_autotools_convention.nim",
    binary: "build/test-bin/test_c_cpp_autotools_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_c_cpp_cmake_convention.nim",
    binary: "build/test-bin/test_c_cpp_cmake_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_c_cpp_direct_convention.nim",
    binary: "build/test-bin/test_c_cpp_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_c_cpp_make_convention.nim",
    binary: "build/test-bin/test_c_cpp_make_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_c_cpp_meson_convention.nim",
    binary: "build/test-bin/test_c_cpp_meson_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_convention_registry_dispatch.nim",
    binary: "build/test-bin/test_convention_registry_dispatch",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_crude_fallback.nim",
    binary: "build/test-bin/test_crude_fallback",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_crystal_convention.nim",
    binary: "build/test-bin/test_crystal_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_csharp_dotnet_convention.nim",
    binary: "build/test-bin/test_csharp_dotnet_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_d_direct_convention.nim",
    binary: "build/test-bin/test_d_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_elixir_mix_convention.nim",
    binary: "build/test-bin/test_elixir_mix_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_emit_cache_m18.nim",
    binary: "build/test-bin/test_emit_cache_m18",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_emit_cache_m29.nim",
    binary: "build/test-bin/test_emit_cache_m29",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_erlang_rebar3_convention.nim",
    binary: "build/test-bin/test_erlang_rebar3_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_examples_layout.nim",
    binary: "build/test-bin/test_examples_layout",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_fortran_direct_convention.nim",
    binary: "build/test-bin/test_fortran_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_go_convention.nim",
    binary: "build/test-bin/test_go_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_go_direct_convention.nim",
    binary: "build/test-bin/test_go_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_haskell_cabal_convention.nim",
    binary: "build/test-bin/test_haskell_cabal_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_java_maven_convention.nim",
    binary: "build/test-bin/test_java_maven_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_jsts_convention.nim",
    binary: "build/test-bin/test_jsts_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_jsts_direct_convention.nim",
    binary: "build/test-bin/test_jsts_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_kotlin_gradle_convention.nim",
    binary: "build/test-bin/test_kotlin_gradle_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_mode1_loader.nim",
    binary: "build/test-bin/test_mode1_loader",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_nim_convention.nim",
    binary: "build/test-bin/test_nim_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_ocaml_dune_convention.nim",
    binary: "build/test-bin/test_ocaml_dune_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_pascal_direct_convention.nim",
    binary: "build/test-bin/test_pascal_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_php_composer_convention.nim",
    binary: "build/test-bin/test_php_composer_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_project_file_alias.nim",
    binary: "build/test-bin/test_project_file_alias",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_python_convention.nim",
    binary: "build/test-bin/test_python_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_python_direct_convention.nim",
    binary: "build/test-bin/test_python_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_ruby_bundler_convention.nim",
    binary: "build/test-bin/test_ruby_bundler_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_rust_convention.nim",
    binary: "build/test-bin/test_rust_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_rust_direct_convention.nim",
    binary: "build/test-bin/test_rust_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_swift_swiftpm_convention.nim",
    binary: "build/test-bin/test_swift_swiftpm_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "libs/repro_standard_provider/tests/test_zig_direct_convention.nim",
    binary: "build/test-bin/test_zig_direct_convention",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "tests/e2e/cmake-develop/t_e2e_repro_develop_cmake.nim",
    binary: "build/test-bin/t_e2e_repro_develop_cmake",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/codetracer-subset/t_e2e_codetracer_build_subset_without_tup.nim",
    binary: "build/test-bin/t_e2e_codetracer_build_subset_without_tup",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/codetracer-subset/t_e2e_codetracer_dev_environment_slice.nim",
    binary: "build/test-bin/t_e2e_codetracer_dev_environment_slice",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/codetracer-subset/t_e2e_codetracer_in_place_project_file.nim",
    binary: "build/test-bin/t_e2e_codetracer_in_place_project_file",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/configurable-system/t_e2e_configurable_system_in_dsl.nim",
    binary: "build/test-bin/t_e2e_configurable_system_in_dsl",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_deactivate_per_shell.nim",
    binary: "build/test-bin/t_e2e_dev_env_deactivate_per_shell",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_deactivate_round_trip.nim",
    binary: "build/test-bin/t_e2e_dev_env_deactivate_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_deactivate_tampered.nim",
    binary: "build/test-bin/t_e2e_dev_env_deactivate_tampered",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_edge_cache.nim",
    binary: "build/test-bin/t_e2e_dev_env_edge_cache",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_export_bash.nim",
    binary: "build/test-bin/t_e2e_dev_env_export_bash",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_export_fish.nim",
    binary: "build/test-bin/t_e2e_dev_env_export_fish",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_export_nushell.nim",
    binary: "build/test-bin/t_e2e_dev_env_export_nushell",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_export_pwsh.nim",
    binary: "build/test-bin/t_e2e_dev_env_export_pwsh",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_export_zsh.nim",
    binary: "build/test-bin/t_e2e_dev_env_export_zsh",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_dev_env_performance_gates.nim",
    binary: "build/test-bin/t_e2e_dev_env_performance_gates",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_develop_overrides_activity.nim",
    binary: "build/test-bin/t_e2e_develop_overrides_activity",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_hooks_shell_direnv.nim",
    binary: "build/test-bin/t_e2e_hooks_shell_direnv",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_native_shell_hooks.nim",
    binary: "build/test-bin/t_e2e_native_shell_hooks",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_provider_dev_env_introspection.nim",
    binary: "build/test-bin/t_e2e_provider_dev_env_introspection",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_repro_dev_sessions.nim",
    binary: "build/test-bin/t_e2e_repro_dev_sessions",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_repro_exec_shell.nim",
    binary: "build/test-bin/t_e2e_repro_exec_shell",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_shell_hook_cd_activate_deactivate.nim",
    binary: "build/test-bin/t_e2e_shell_hook_cd_activate_deactivate",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_shell_hook_noop_io_bounded.nim",
    binary: "build/test-bin/t_e2e_shell_hook_noop_io_bounded",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_shell_hook_noop_latency.nim",
    binary: "build/test-bin/t_e2e_shell_hook_noop_latency",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_shell_hook_realistic_workload.nim",
    binary: "build/test-bin/t_e2e_shell_hook_realistic_workload",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dev-env/t_e2e_shell_hook_templates.nim",
    binary: "build/test-bin/t_e2e_shell_hook_templates",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/dotfiles-replacement/t_e2e_dotfiles_replacement_on_real_host.nim",
    binary: "build/test-bin/t_e2e_dotfiles_replacement_on_real_host",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/external-packages/t_e2e_local_store_unified_across_adapters.nim",
    binary: "build/test-bin/t_e2e_local_store_unified_across_adapters",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/fs-snoop/t_debug_fs_snoop_reads_monitor_depfile.nim",
    binary: "build/test-bin/t_debug_fs_snoop_reads_monitor_depfile",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/generated-config/t_e2e_generated_config_file_block_macro.nim",
    binary: "build/test-bin/t_e2e_generated_config_file_block_macro",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/generated-config/t_e2e_generated_config_file_external_template.nim",
    binary: "build/test-bin/t_e2e_generated_config_file_external_template",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/generated-config/t_e2e_generated_config_file_json_value.nim",
    binary: "build/test-bin/t_e2e_generated_config_file_json_value",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/generated-config/t_e2e_generated_config_file_managed_block.nim",
    binary: "build/test-bin/t_e2e_generated_config_file_managed_block",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/generated-config/t_e2e_managed_block_cache_key_isolation.nim",
    binary: "build/test-bin/t_e2e_managed_block_cache_key_isolation",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/hcr-debug-unwind/t_e2e_hcr_direct_patch_debug_unwind_replay.nim",
    binary: "build/test-bin/t_e2e_hcr_direct_patch_debug_unwind_replay",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/hcr-direct-linker/t_e2e_hcr_in_target_link_and_trampoline.nim",
    binary: "build/test-bin/t_e2e_hcr_in_target_link_and_trampoline",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/hcr-watch/t_e2e_hcr_watch_inference.nim",
    binary: "build/test-bin/t_e2e_hcr_watch_inference",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/hcr-watch/t_e2e_repro_watch_hcr_multi_target_independent_patches.nim",
    binary: "build/test-bin/t_e2e_repro_watch_hcr_multi_target_independent_patches",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/hcr-watch/t_e2e_repro_watch_hcr_one_target_agent_inject_failure.nim",
    binary: "build/test-bin/t_e2e_repro_watch_hcr_one_target_agent_inject_failure",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-apply/t_e2e_repro_home_add_remove_immediate.nim",
    binary: "build/test-bin/t_e2e_repro_home_add_remove_immediate",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-apply/t_e2e_repro_home_apply_fresh_install.nim",
    binary: "build/test-bin/t_e2e_repro_home_apply_fresh_install",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-apply/t_e2e_repro_home_apply_noop.nim",
    binary: "build/test-bin/t_e2e_repro_home_apply_noop",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-apply/t_e2e_repro_home_apply_partial_recovery.nim",
    binary: "build/test-bin/t_e2e_repro_home_apply_partial_recovery",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-apply/t_e2e_stow_auto_discovery_and_materialization.nim",
    binary: "build/test-bin/t_e2e_stow_auto_discovery_and_materialization",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-apply/t_e2e_stow_suppression_and_warnings.nim",
    binary: "build/test-bin/t_e2e_stow_suppression_and_warnings",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-generations/t_integration_activation_manifest_dedup_in_cas.nim",
    binary: "build/test-bin/t_integration_activation_manifest_dedup_in_cas",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-generations/t_integration_apply_lock_serializes.nim",
    binary: "build/test-bin/t_integration_apply_lock_serializes",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-generations/t_integration_pointer_envelope_and_history_enumeration.nim",
    binary: "build/test-bin/t_integration_pointer_envelope_and_history_enumeration",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-intent/t_e2e_repro_home_intent_commands.nim",
    binary: "build/test-bin/t_e2e_repro_home_intent_commands",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-intent/t_integration_intent_layer_config_section.nim",
    binary: "build/test-bin/t_integration_intent_layer_config_section",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-intent/t_integration_intent_layer_round_trip.nim",
    binary: "build/test-bin/t_integration_intent_layer_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-resources/t_e2e_home_registry_typed_value_kinds.nim",
    binary: "build/test-bin/t_e2e_home_registry_typed_value_kinds",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-resources/t_e2e_home_resource_lifecycle.nim",
    binary: "build/test-bin/t_e2e_home_resource_lifecycle",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-resources/t_e2e_home_resource_rollback_preserves_unrelated.nim",
    binary: "build/test-bin/t_e2e_home_resource_rollback_preserves_unrelated",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-resources/t_e2e_macos_user_default_restart_target.nim",
    binary: "build/test-bin/t_e2e_macos_user_default_restart_target",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-resources/t_integration_prevent_destroy.nim",
    binary: "build/test-bin/t_integration_prevent_destroy",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-resources/t_integration_resource_move.nim",
    binary: "build/test-bin/t_integration_resource_move",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-rollback/t_e2e_repro_home_rollback_round_trip.nim",
    binary: "build/test-bin/t_e2e_repro_home_rollback_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-rollback/t_e2e_repro_home_rollback_user_edit_protection.nim",
    binary: "build/test-bin/t_e2e_repro_home_rollback_user_edit_protection",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/home-set-get/t_e2e_repro_home_set_triggers_focused_rebuild.nim",
    binary: "build/test-bin/t_e2e_repro_home_set_triggers_focused_rebuild",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/launcher-isolation/t_e2e_windows_launcher_isolation.nim",
    binary: "build/test-bin/t_e2e_windows_launcher_isolation",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_e2e_local_reprobuild_project_build.nim",
    binary: "build/test-bin/t_e2e_local_reprobuild_project_build",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_e2e_m51_dsl_stdlib_file_ops.nim",
    binary: "build/test-bin/t_e2e_m51_dsl_stdlib_file_ops",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_e2e_repro_build_multiple_named_targets.nim",
    binary: "build/test-bin/t_e2e_repro_build_multiple_named_targets",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_e2e_repro_build_named_target.nim",
    binary: "build/test-bin/t_e2e_repro_build_named_target",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_repro_build_ambiguous_target_diagnostic.nim",
    binary: "build/test-bin/t_repro_build_ambiguous_target_diagnostic",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_repro_build_qualified_target_resolves.nim",
    binary: "build/test-bin/t_repro_build_qualified_target_resolves",
    defines: @["reproProviderMode"]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_repro_build_unknown_target_diagnostic.nim",
    binary: "build/test-bin/t_repro_build_unknown_target_diagnostic",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/local-build-engine/t_repro_list_targets_lists_implicit_and_explicit.nim",
    binary: "build/test-bin/t_repro_list_targets_lists_implicit_and_explicit",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m68/t_e2e_repro_home_depends_on_topological.nim",
    binary: "build/test-bin/t_e2e_repro_home_depends_on_topological",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m68/t_e2e_repro_home_fs_user_file.nim",
    binary: "build/test-bin/t_e2e_repro_home_fs_user_file",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_apply_builtin_catalog.nim",
    binary: "build/test-bin/t_e2e_repro_home_apply_builtin_catalog",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_env_user_path_vm.nim",
    binary: "build/test-bin/t_e2e_repro_home_env_user_path_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_fs_managed_block_vm.nim",
    binary: "build/test-bin/t_e2e_repro_home_fs_managed_block_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_fs_user_file_vm.nim",
    binary: "build/test-bin/t_e2e_repro_home_fs_user_file_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_linux_dconfkey_vm.nim",
    binary: "build/test-bin/t_e2e_repro_home_linux_dconfkey_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_linux_kdeconfigkey_vm.nim",
    binary: "build/test-bin/t_e2e_repro_home_linux_kdeconfigkey_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_shell_integration_vm.nim",
    binary: "build/test-bin/t_e2e_repro_home_shell_integration_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_home_systemd_user_unit_vm.nim",
    binary: "build/test-bin/t_e2e_repro_home_systemd_user_unit_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_depends_on_topological.nim",
    binary: "build/test-bin/t_e2e_repro_infra_depends_on_topological",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_env_system_variable.nim",
    binary: "build/test-bin/t_e2e_repro_infra_env_system_variable",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_fs_system_file.nim",
    binary: "build/test-bin/t_e2e_repro_infra_fs_system_file",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_linux_firewallrule_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_linux_firewallrule_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_linux_nixdaemonsetting_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_linux_nixdaemonsetting_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_linux_polkitrule_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_linux_polkitrule_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_linux_sudoersrule_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_linux_sudoersrule_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_linux_sysctl_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_linux_sysctl_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_linux_tmpfilesrule_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_linux_tmpfilesrule_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_linux_udevrule_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_linux_udevrule_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_os_hostname_posix_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_os_hostname_posix_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_os_timezone_posix_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_os_timezone_posix_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_passwd_group_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_passwd_group_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_passwd_user_safe_destroy.nim",
    binary: "build/test-bin/t_e2e_repro_infra_passwd_user_safe_destroy",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_plan_apply_convergent.nim",
    binary: "build/test-bin/t_e2e_repro_infra_plan_apply_convergent",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_plan_time_external_drift.nim",
    binary: "build/test-bin/t_e2e_repro_infra_plan_time_external_drift",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_systemd_system_timer_vm.nim",
    binary: "build/test-bin/t_e2e_repro_infra_systemd_system_timer_vm",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_infra_systemd_system_unit.nim",
    binary: "build/test-bin/t_e2e_repro_infra_systemd_system_unit",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_repro_system_command_family.nim",
    binary: "build/test-bin/t_e2e_repro_system_command_family",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_windows_optional_feature_and_capability.nim",
    binary: "build/test-bin/t_e2e_windows_optional_feature_and_capability",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_windows_registry_system_scope.nim",
    binary: "build/test-bin/t_e2e_windows_registry_system_scope",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m69/t_e2e_windows_vs_installer.nim",
    binary: "build/test-bin/t_e2e_windows_vs_installer",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m71/t_e2e_m71_phase2_partials_resolve.nim",
    binary: "build/test-bin/t_e2e_m71_phase2_partials_resolve",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m71/t_e2e_remote_apply_home_profile_phase_e.nim",
    binary: "build/test-bin/t_e2e_remote_apply_home_profile_phase_e",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m71/t_integration_remote_apply_activation_bundle_phase_a.nim",
    binary: "build/test-bin/t_integration_remote_apply_activation_bundle_phase_a",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m71/t_integration_remote_apply_cross_host_evaluation_phase_b.nim",
    binary: "build/test-bin/t_integration_remote_apply_cross_host_evaluation_phase_b",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m71/t_integration_remote_apply_remote_activation_phase_d.nim",
    binary: "build/test-bin/t_integration_remote_apply_remote_activation_phase_d",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m71/t_integration_remote_apply_ssh_transfer_phase_c.nim",
    binary: "build/test-bin/t_integration_remote_apply_ssh_transfer_phase_c",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m72/t_e2e_apply_plan_dry_run.nim",
    binary: "build/test-bin/t_e2e_apply_plan_dry_run",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m72/t_integration_production_package_catalog.nim",
    binary: "build/test-bin/t_integration_production_package_catalog",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m72/t_integration_stow_non_destructive_over_existing.nim",
    binary: "build/test-bin/t_integration_stow_non_destructive_over_existing",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m73/t_integration_stow_gnu_package_layout.nim",
    binary: "build/test-bin/t_integration_stow_gnu_package_layout",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m74/t_integration_scoop_manifest_bin_resolution.nim",
    binary: "build/test-bin/t_integration_scoop_manifest_bin_resolution",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m75/t_integration_scoop_probe_gui_and_timeout.nim",
    binary: "build/test-bin/t_integration_scoop_probe_gui_and_timeout",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m76/t_integration_stow_byte_identical_target_is_cache_hit.nim",
    binary: "build/test-bin/t_integration_stow_byte_identical_target_is_cache_hit",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m77/t_integration_scoop_installed_version_survives_bucket_drift.nim",
    binary: "build/test-bin/t_integration_scoop_installed_version_survives_bucket_drift",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m78/t_e2e_profile_declared_resources_apply.nim",
    binary: "build/test-bin/t_e2e_profile_declared_resources_apply",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m79/t_integration_shell_integration_replan_idempotent.nim",
    binary: "build/test-bin/t_integration_shell_integration_replan_idempotent",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m80/t_integration_plan_classifier_bucket_drift_is_cache_hit.nim",
    binary: "build/test-bin/t_integration_plan_classifier_bucket_drift_is_cache_hit",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m81/t_integration_privileged_broker_single_prompt.nim",
    binary: "build/test-bin/t_integration_privileged_broker_single_prompt",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m83/t_e2e_compile_fail_is_hard_error.nim",
    binary: "build/test-bin/t_e2e_compile_fail_is_hard_error",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m83/t_e2e_profile_modules.nim",
    binary: "build/test-bin/t_e2e_profile_modules",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m83/t_e2e_repro_profile_compile.nim",
    binary: "build/test-bin/t_e2e_repro_profile_compile",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m83/t_e2e_repro_profile_compile_via_action.nim",
    binary: "build/test-bin/t_e2e_repro_profile_compile_via_action",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m9/t_e2e_m9_linux_phase2_partials_resolve.nim",
    binary: "build/test-bin/t_e2e_m9_linux_phase2_partials_resolve",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m9_5/t_e2e_m9_5_linux_url_harvest.nim",
    binary: "build/test-bin/t_e2e_m9_5_linux_url_harvest",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/m9_5/t_e2e_m9_5_smoke_chain_resolve_gh_linux.nim",
    binary: "build/test-bin/t_e2e_m9_5_smoke_chain_resolve_gh_linux",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-monitor/t_macos_monitor_shim_event_taxonomy.nim",
    binary: "build/test-bin/t_macos_monitor_shim_event_taxonomy",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_env_user_path.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_env_user_path",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_fs_managed_block.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_fs_managed_block",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_fs_user_file.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_fs_user_file",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_homebrew_cask.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_homebrew_cask",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_homebrew_formula.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_homebrew_formula",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_launchd_system_daemon.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_launchd_system_daemon",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_launchd_user_agent.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_launchd_user_agent",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_macos_system_default.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_macos_system_default",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_os_hostname.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_os_hostname",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_os_timezone.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_os_timezone",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_passwd_group.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_passwd_group",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/macos-phase5/t_e2e_macos_phase5_shell_integration.nim",
    binary: "build/test-bin/t_e2e_macos_phase5_shell_integration",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/path-only/t_path_only_tool_interfaces.nim",
    binary: "build/test-bin/t_path_only_tool_interfaces",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/scoop/t_e2e_scoop_adapter_diagnostics.nim",
    binary: "build/test-bin/t_e2e_scoop_adapter_diagnostics",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/scoop/t_e2e_scoop_adapter_realize_and_launch.nim",
    binary: "build/test-bin/t_e2e_scoop_adapter_realize_and_launch",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/scoop/t_e2e_scoop_practical_hardening.nim",
    binary: "build/test-bin/t_e2e_scoop_practical_hardening",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/sharding/t_e2e_repro_test_shard_balances_wall_time.nim",
    binary: "build/test-bin/t_e2e_repro_test_shard_balances_wall_time",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/sharding/t_e2e_repro_test_shard_emit_plan_then_consume.nim",
    binary: "build/test-bin/t_e2e_repro_test_shard_emit_plan_then_consume",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/sharding/t_e2e_repro_test_shard_lan_peer_cache_not_implemented.nim",
    binary: "build/test-bin/t_e2e_repro_test_shard_lan_peer_cache_not_implemented",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/sharding/t_e2e_repro_test_shard_partition_total_coverage.nim",
    binary: "build/test-bin/t_e2e_repro_test_shard_partition_total_coverage",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/sharding/t_e2e_repro_test_shard_workspace_integration.nim",
    binary: "build/test-bin/t_e2e_repro_test_shard_workspace_integration",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/t_m54_verified_tarball_profile.nim",
    binary: "build/test-bin/t_m54_verified_tarball_profile",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/watch/t_e2e_repro_watch.nim",
    binary: "build/test-bin/t_e2e_repro_watch",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/watch/t_e2e_repro_watch_multiple_named_targets.nim",
    binary: "build/test-bin/t_e2e_repro_watch_multiple_named_targets",
    defines: @[]),
  TestSpec(
    source: "tests/e2e/watch/t_repro_watch_unknown_target_diagnostic.nim",
    binary: "build/test-bin/t_repro_watch_unknown_target_diagnostic",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_action_cache_fingerprint_policies.nim",
    binary: "build/test-bin/t_action_cache_fingerprint_policies",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_dependency_report_and_converter_paths.nim",
    binary: "build/test-bin/t_dependency_report_and_converter_paths",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_dev_env_artifact.nim",
    binary: "build/test-bin/t_dev_env_artifact",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_entrypoints.nim",
    binary: "build/test-bin/t_entrypoints",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_build_engine_api_ready_queue.nim",
    binary: "build/test-bin/t_integration_build_engine_api_ready_queue",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_configurable_doc_comment_directives.nim",
    binary: "build/test-bin/t_integration_configurable_doc_comment_directives",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_configurable_persistent_lookup.nim",
    binary: "build/test-bin/t_integration_configurable_persistent_lookup",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_configurable_staged_field_access.nim",
    binary: "build/test-bin/t_integration_configurable_staged_field_access",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_configurable_system_basic_resolution.nim",
    binary: "build/test-bin/t_integration_configurable_system_basic_resolution",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_configurable_system_incremental_refinalize.nim",
    binary: "build/test-bin/t_integration_configurable_system_incremental_refinalize",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_daemon_nix_and_tarball_realize.nim",
    binary: "build/test-bin/t_integration_daemon_nix_and_tarball_realize",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_hcr_linkgraph_relocation_classification.nim",
    binary: "build/test-bin/t_integration_hcr_linkgraph_relocation_classification",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_hcr_reference_corpus_and_object_inputs.nim",
    binary: "build/test-bin/t_integration_hcr_reference_corpus_and_object_inputs",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_launch_plan_binding_strategies.nim",
    binary: "build/test-bin/t_integration_launch_plan_binding_strategies",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_local_store_gc.nim",
    binary: "build/test-bin/t_integration_local_store_gc",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_local_store_layout_and_atomic_writes.nim",
    binary: "build/test-bin/t_integration_local_store_layout_and_atomic_writes",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_provider_fragment_refresh_and_pruning.nim",
    binary: "build/test-bin/t_integration_provider_fragment_refresh_and_pruning",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_reprobuild_sessions_share_runquota.nim",
    binary: "build/test-bin/t_integration_reprobuild_sessions_share_runquota",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_scheduler_dependency_gathering_policies.nim",
    binary: "build/test-bin/t_integration_scheduler_dependency_gathering_policies",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_variant_cli_flag.nim",
    binary: "build/test-bin/t_integration_variant_cli_flag",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_variant_conditional_uses_static_value.nim",
    binary: "build/test-bin/t_integration_variant_conditional_uses_static_value",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_variant_declaration_basic.nim",
    binary: "build/test-bin/t_integration_variant_declaration_basic",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_variant_override_priorities.nim",
    binary: "build/test-bin/t_integration_variant_override_priorities",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_integration_variant_value_accessor.nim",
    binary: "build/test-bin/t_integration_variant_value_accessor",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_just_test_end_to_end_via_parallel_runner.nim",
    binary: "build/test-bin/t_just_test_end_to_end_via_parallel_runner",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_just_test_hot_cache_is_no_op_build.nim",
    binary: "build/test-bin/t_just_test_hot_cache_is_no_op_build",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_just_test_via_ct_test_runner.nim",
    binary: "build/test-bin/t_just_test_via_ct_test_runner",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m0.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m0",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m1.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m1",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m10.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m10",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m11.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m11",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m2.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m2",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m3.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m3",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m4.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m4",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m5.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m5",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m6.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m6",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m7.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m7",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_local_daemons_control_plane_m8.nim",
    binary: "build/test-bin/t_local_daemons_control_plane_m8",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_monitor_depfile_reader.nim",
    binary: "build/test-bin/t_monitor_depfile_reader",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_project_dsl_build_action_payload.nim",
    binary: "build/test-bin/t_project_dsl_build_action_payload",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_project_interface_artifact_import_modes.nim",
    binary: "build/test-bin/t_project_interface_artifact_import_modes",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_repro_build_test_aggregate_builds_every_test.nim",
    binary: "build/test-bin/t_repro_build_test_aggregate_builds_every_test",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_repro_core_binary_roundtrip.nim",
    binary: "build/test-bin/t_repro_core_binary_roundtrip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_repro_test_runner_aggregate_exit_code.nim",
    binary: "build/test-bin/t_repro_test_runner_aggregate_exit_code",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_repro_test_runner_parallel_n_workers.nim",
    binary: "build/test-bin/t_repro_test_runner_parallel_n_workers",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_spec_example_fixtures_compile.nim",
    binary: "build/test-bin/t_spec_example_fixtures_compile",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_spec_example_fixtures_present.nim",
    binary: "build/test-bin/t_spec_example_fixtures_present",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_stackable_hooks_extracted_process_tree.nim",
    binary: "build/test-bin/t_stackable_hooks_extracted_process_tree",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_store_daemon_m66_dev.nim",
    binary: "build/test-bin/t_store_daemon_m66_dev",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_test_edge_migration_covers_all_test_files.nim",
    binary: "build/test-bin/t_test_edge_migration_covers_all_test_files",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_branch_create_records_metadata.nim",
    binary: "build/test-bin/t_workspace_branch_create_records_metadata",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_branch_create_refuses_on_any_dirty_sibling.nim",
    binary: "build/test-bin/t_workspace_branch_create_refuses_on_any_dirty_sibling",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_checkout_switches_all_repos.nim",
    binary: "build/test-bin/t_workspace_checkout_switches_all_repos",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_develop_clones_and_registers_override.nim",
    binary: "build/test-bin/t_workspace_develop_clones_and_registers_override",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_develop_overrides_round_trip.nim",
    binary: "build/test-bin/t_workspace_develop_overrides_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_git_tool_identity.nim",
    binary: "build/test-bin/t_workspace_git_tool_identity",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_hooks_ensure_is_idempotent_across_three_runs.nim",
    binary: "build/test-bin/t_workspace_hooks_ensure_is_idempotent_across_three_runs",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_init_clones_missing_and_reports_existing.nim",
    binary: "build/test-bin/t_workspace_init_clones_missing_and_reports_existing",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_list_walks_resolved_repos.nim",
    binary: "build/test-bin/t_workspace_list_walks_resolved_repos",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_lock_round_trips_through_resolver.nim",
    binary: "build/test-bin/t_workspace_lock_round_trips_through_resolver",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifest_refresh_after_post_merge.nim",
    binary: "build/test-bin/t_workspace_manifest_refresh_after_post_merge",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifest_refresh_skips_when_divergent.nim",
    binary: "build/test-bin/t_workspace_manifest_refresh_skips_when_divergent",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifest_refresh_skips_when_locally_dirty.nim",
    binary: "build/test-bin/t_workspace_manifest_refresh_skips_when_locally_dirty",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_develop_overrides_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_develop_overrides_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_enumerates_layers.nim",
    binary: "build/test-bin/t_workspace_manifests_enumerates_layers",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_lock_index_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_lock_index_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_lock_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_lock_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_private_override_shadows_public.nim",
    binary: "build/test-bin/t_workspace_manifests_private_override_shadows_public",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_project_manifest_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_project_manifest_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_repo_fragment_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_repo_fragment_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_resolve_collision.nim",
    binary: "build/test-bin/t_workspace_manifests_resolve_collision",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_resolve_reprobuild_project.nim",
    binary: "build/test-bin/t_workspace_manifests_resolve_reprobuild_project",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_resolve_variant_overrides_revision.nim",
    binary: "build/test-bin/t_workspace_manifests_resolve_variant_overrides_revision",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_snapshot_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_snapshot_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_variant_manifest_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_variant_manifest_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_manifests_workspace_local_round_trip.nim",
    binary: "build/test-bin/t_workspace_manifests_workspace_local_round_trip",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_metadata_branch_round_trips_through_reader.nim",
    binary: "build/test-bin/t_workspace_metadata_branch_round_trips_through_reader",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_metadata_branch_survives_init_and_status.nim",
    binary: "build/test-bin/t_workspace_metadata_branch_survives_init_and_status",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_override_shadows_upstream_in_resolver.nim",
    binary: "build/test-bin/t_workspace_override_shadows_upstream_in_resolver",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_post_commit_lock_refresh_is_best_effort.nim",
    binary: "build/test-bin/t_workspace_post_commit_lock_refresh_is_best_effort",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_pre_push_blocks_lock_with_private_only_refs.nim",
    binary: "build/test-bin/t_workspace_pre_push_blocks_lock_with_private_only_refs",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_pre_push_blocks_on_develop_override_cleanliness.nim",
    binary: "build/test-bin/t_workspace_pre_push_blocks_on_develop_override_cleanliness",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_pre_push_blocks_when_branch_mismatch.nim",
    binary: "build/test-bin/t_workspace_pre_push_blocks_when_branch_mismatch",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_pre_push_blocks_when_head_unpublished.nim",
    binary: "build/test-bin/t_workspace_pre_push_blocks_when_head_unpublished",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_pre_push_blocks_when_repo_dirty.nim",
    binary: "build/test-bin/t_workspace_pre_push_blocks_when_repo_dirty",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_pre_push_passes_when_clean_and_published_and_locked.nim",
    binary: "build/test-bin/t_workspace_pre_push_passes_when_clean_and_published_and_locked",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_pre_push_refreshes_lock_when_missing.nim",
    binary: "build/test-bin/t_workspace_pre_push_refreshes_lock_when_missing",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_private_layer_e2e.nim",
    binary: "build/test-bin/t_workspace_private_layer_e2e",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_start_marks_feature_branch.nim",
    binary: "build/test-bin/t_workspace_start_marks_feature_branch",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_status_shows_active_branch_and_drift.nim",
    binary: "build/test-bin/t_workspace_status_shows_active_branch_and_drift",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_sync_seven_corner_cases.nim",
    binary: "build/test-bin/t_workspace_sync_seven_corner_cases",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_vcs_clone_cacheable.nim",
    binary: "build/test-bin/t_workspace_vcs_clone_cacheable",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_vcs_evidence_round_trips_through_build_report.nim",
    binary: "build/test-bin/t_workspace_vcs_evidence_round_trips_through_build_report",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_vcs_fetch_no_op_when_up_to_date.nim",
    binary: "build/test-bin/t_workspace_vcs_fetch_no_op_when_up_to_date",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_vcs_hybrid_workspace_clone.nim",
    binary: "build/test-bin/t_workspace_vcs_hybrid_workspace_clone",
    defines: @[]),
  TestSpec(
    source: "tests/integration/t_workspace_vcs_switch_preserves_dirty_state.nim",
    binary: "build/test-bin/t_workspace_vcs_switch_preserves_dirty_state",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_capabilities.nim",
    binary: "build/test-bin/t_capabilities",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_hcr_agent_coordinator.nim",
    binary: "build/test-bin/t_hcr_agent_coordinator",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_hcr_agent_endpoint.nim",
    binary: "build/test-bin/t_hcr_agent_endpoint",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_hcr_agent_ipc.nim",
    binary: "build/test-bin/t_hcr_agent_ipc",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_hcr_agent_process_target.nim",
    binary: "build/test-bin/t_hcr_agent_process_target",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_hcr_agent_protocol.nim",
    binary: "build/test-bin/t_hcr_agent_protocol",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_hcr_agent_runtime.nim",
    binary: "build/test-bin/t_hcr_agent_runtime",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_hcr_watch_inference.nim",
    binary: "build/test-bin/t_hcr_watch_inference",
    defines: @[]),
  TestSpec(
    source: "tests/unit/t_version.nim",
    binary: "build/test-bin/t_version",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_gh_releases_source.nim",
    binary: "build/test-bin/test_gh_releases_source",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_harvester_app_name_validation.nim",
    binary: "build/test-bin/test_harvester_app_name_validation",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_harvester_history.nim",
    binary: "build/test-bin/test_harvester_history",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_harvester_history_walk.nim",
    binary: "build/test-bin/test_harvester_history_walk",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_harvester_idempotent.nim",
    binary: "build/test-bin/test_harvester_idempotent",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_harvester_verify.nim",
    binary: "build/test-bin/test_harvester_verify",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_manifest_parser.nim",
    binary: "build/test-bin/test_manifest_parser",
    defines: @[]),
  TestSpec(
    source: "tools/catalog-harvester/tests/test_msys2_source.nim",
    binary: "build/test-bin/test_msys2_source",
    defines: @[])
]
