## Reprobuild repo project file.
##
## A Mode 1 / Mode 3 hybrid (per
## ``reprobuild-specs/Three-Mode-Convention-System.md``):
##
## * Declares the upstream tool dependencies via ``uses:`` so future
##   consumers can ``uses: "reprobuild"`` and pick up the same toolchain
##   floor that the existing ``flake.nix`` provisions today (nim, gcc,
##   just, libblake3, xxhash, sqlite, plus the two source-only fixed
##   inputs nimcrypto-src and runquota-src).
## * Declares ``library reprobuild`` so consumers can express a
##   workspace dependency on this repo with ``uses: "reprobuild"``. The
##   library is the umbrella view of every ``libs/<name>/src`` tree
##   (see ``config.nims`` for the active path list); there is no single
##   ``src/reprobuild.nim`` umbrella because the repo is a fan-out of
##   independent libs the apps wire together explicitly.
## * Declares the six shipping executables one-for-one with
##   ``apps/entrypoints.txt``. The Nim-identifier names are camelCase
##   stand-ins for the hyphenated binary names; ``name: "<bin>"``
##   inside each ``executable`` body pins the on-disk artifact.
## * (HISTORICAL, retired in B5) Wrapped ``scripts/build_apps.sh``
##   byte-for-byte in a single ``build:`` action. That was the option-(A)
##   cut described in the repo packaging memo — coarse-grained and opaque,
##   but immediately consistent with ``just build``. Every artifact it
##   produced now has its own edge, and the wrapper is gone; the script
##   remains only as the ``just bootstrap`` path. Option (B) — one
##   ``nim c`` per entrypoint via the DSL's per-entry ``buildAction``
##   primitive — is deferred to a follow-on milestone.
##
## The ``build:`` action inherits ``BLAKE3_PREFIX`` / ``XXHASH_PREFIX``
## / ``SQLITE_PREFIX`` / ``NIMCRYPTO_SRC`` / ``RUNQUOTA_SRC`` /
## ``REPROBUILD_USE_SYSTEM_HASH_LIBS`` from the calling environment, the
## same way the ``flake.nix`` devShell and the existing ``just build``
## drop-in do. The Nix package definition at
## ``nix/pkgs/by-name/re/reprobuild/package.nix`` sets every one of
## those before invoking ``just build``; an interactive developer gets
## them out of the ``nix develop`` shell.

import std/[os, osproc, strutils]
# Ambient-execution hatches. Every call below is bootstrap tier: the recipe has
# to locate a host tool BEFORE any engine-provisioned prefix exists, so a typed
# execution profile is not available to it. Naming the hatch says so at the
# call site instead of leaving it to be inferred — `git grep uncontrolled` is
# the audit surface.
import lints/ambient_execution
              # Incremental-Test-Runner M7: getEnv + the `/` path operator
              # for the io-mon / nim-stackable-hooks sibling resolution in the
              # test-fixtures monitor-shim build edge below.
import repro_project_dsl
import repro_dsl_stdlib/packages/sh
import repro_dsl_stdlib/fs as dslfs
import repro_dsl_stdlib/types

proc sanitizeStaticExec(val: string): string =
  var cleanLines: seq[string] = @[]
  for line in val.splitLines:
    let s = line.strip()
    if s.len > 0 and not s.startsWith("io-mon:"):
      cleanLines.add(s)
  if cleanLines.len > 0: cleanLines[^1] else: ""

when defined(windows):
  const CompileTimeIoMonSrc =
    sanitizeStaticExec(staticExec("cmd /C if defined IO_MON_SRC (echo %IO_MON_SRC%)"))
  const CompileTimeStackableHooksSrc =
    sanitizeStaticExec(staticExec("cmd /C if defined STACKABLE_HOOKS_SRC (echo %STACKABLE_HOOKS_SRC%)"))
else:
  const CompileTimeIoMonSrc =
    sanitizeStaticExec(staticExec("sh -c 'printf %s \"${IO_MON_SRC:-}\"'"))
  const CompileTimeStackableHooksSrc =
    sanitizeStaticExec(staticExec("sh -c 'printf %s \"${STACKABLE_HOOKS_SRC:-}\"'"))

# Interface extraction compiles this project file without the provider build
# body. Keep the stdlib typed-value surface visible for generated DSL helpers.

# Bootstrap-And-Self-Build B4: Python tests participate in the ``test``
# build graph collection via the ``pythonUnittest`` typed-tool wrapper.
# Each entry in ``pythonTestPaths`` (generated by
# ``scripts/generate_test_edges.nim``) expands to one
# ``pythonUnittest.run(...)`` execute edge that the engine schedules
# alongside the Nim test execute edges. The wrapper records a
# ``PublicCliCall`` against the ``python3`` profile so the engine's
# normal tool-resolution path drives the run.
import repro_dsl_stdlib/packages/python_unittest_runner

# Bootstrap-And-Self-Build B1: ``nim.c(...)`` typed-tool calls in the
# package-level ``build:`` block below resolve through the ``nim``
# const emitted by the ``package nim:`` DSL block in
# ``repro_dsl_stdlib/packages/nim.nim``. That module is auto-imported
# by the ``package`` macro's ``usesImportCode`` pass because
# ``"nim >=2.2 <3.0"`` appears in our ``uses:`` block (the macro
# imports it ``as nim_module`` so the bare ``nim`` identifier resolves
# to the const value, not to the module — direct ``import
# repro_dsl_stdlib/packages/nim`` would shadow the const with the
# module name and break ``nim.c(...)`` method-call resolution).

# Test-Edges-And-Parallel-Runner M1: ``ct_test_nim_unittest`` is the in-tree
# Nim-unittest framework adapter that supplies the
# ``buildNimUnittest.build(...)`` typed-tool used by every entry in
# the generated ``repro_tests.nim``. The module re-exports
# ``repro_project_dsl`` so the import order is fine either way.
# ``config.nims`` adds ``libs/ct_test_nim_unittest/src`` to the Nim path.
import ct_test_nim_unittest

# Spec-Implementation M4: install the in-process ct-test ``TestRunner``
# adapter (from the ``reprobuild-ct-test-runner`` repo) onto
# the active build context so ``repro test`` RUN/LIST/ENUMERATE route
# through the test binary's protocol instead of the stdlib default. The
# engine-coupled ``setTestRunner`` wiring lives in this reprobuild-side
# helper (see ``ct_test_runner_install.nim``); the install call fires from
# inside the ``build:`` block below where a build context is active.
import ct_test_runner_install

# Project-DSL-Composition M6: the generated test-edge table.
# ``repro_tests.nim`` exports ``reprobuildTestSpecs*: seq[TestSpec]``;
# the ``build:`` block below iterates the table and registers one
# ``buildNimUnittest.build(...)`` edge per spec, then aggregates the
# resulting actions into the ``test`` target so ``repro build test``
# schedules every test-binary compilation in one engine pass.
#
# Pre-M6 the generated file was ``repro.tests.nim`` and emitted a
# ``build:`` block included from this file. The package macro's
# ``collectBuildStatements`` did not see through ``include`` nodes,
# so the 450+ edges were silently dropped — ``repro build test``
# reported "no named targets in this project". The data + iteration
# migration shape (Approach A from
# ``reprobuild-specs/Project-DSL-Composition.md``) lifts the
# registration into the caller, so the macro sees the typed-tool
# calls and the edges register correctly. The rename also lets Nim
# import the module by name (Nim does not accept dotted module
# identifiers in ``import`` statements).
import repro_tests

package reprobuild:
  # Declare ``path``-mode tool provisioning so the engine adopts it
  # automatically. Without this, ``repro build`` refuses to run with
  # "typed tool provisioning is required for uses declarations" unless
  # the caller passes ``--tool-provisioning=path`` explicitly. The
  # reprobuild dev shell (``nix develop``) and the Nix package both
  # furnish every tool we need via PATH and via env vars
  # (BLAKE3_PREFIX / XXHASH_PREFIX / SQLITE_PREFIX / NIMCRYPTO_SRC /
  # RUNQUOTA_SRC / SSZ_SERIALIZATION_SRC), so the weak-local PATH mode
  # is the right default for this repo.
  defaultToolProvisioning "path"

  uses:
    # Toolchain floor — mirrors flake.nix's nativeBuildInputs. These
    # are the PATH-resolvable binaries the reprobuild build needs;
    # they're sufficient for the path-mode tool resolver to succeed
    # under ``nix develop``.
    "nim >=2.2 <3.0"
    "gcc >=12"
    "just >=1"
    "sh"

    # Deferred-Item D1: ``python3`` is required by the in-graph Python
    # test execute edges emitted via ``pythonUnittest.run(...)`` (see
    # the ``for source in pythonTestPaths`` loop in the ``build:``
    # block below). The wrapper at
    # ``libs/repro_dsl_stdlib/src/repro_dsl_stdlib/packages/python_unittest_runner.nim``
    # records a ``PublicCliCall`` with ``executableName = "python3"``,
    # so the path-mode resolver needs an explicit ``uses:`` entry to
    # populate a profile for ``python3``. Without this entry the engine
    # raises ``no tool profile was resolved`` when lowering any
    # ``reprobuild.python_test.<stem>`` action. The Bootstrap-And-Self-
    # Build B4 outcome documented this gap; D1 closes it.
    "python3"

    # Bootstrap-And-Self-Build B0: ``runquotad`` is a runtime
    # dependency (spawned as a subprocess by daemon tests at
    # ``../runquota/build/bin/runquotad``). Declaring it in ``uses:``
    # makes the dependency explicit + lets path-mode resolution find
    # the sibling-built binary when ``../runquota/build/bin`` is on
    # ``$PATH``. The sibling ``runquota`` repo now ships its own
    # ``repro.nim`` so later milestones (B1+) can flip this to
    # ``uses: "runquota"`` and consume runquota's typed
    # ``executable runquotad`` output via cross-project resolution;
    # ``runquotad`` (the bare executable selector) is the path-mode
    # form that works today.
    "runquotad"

    # Note: the system hash libraries (libblake3, xxhash, sqlite3) and
    # the source-only fixed inputs (nimcrypto, runquota,
    # ssz-serialization, ct_test_nim_unittest) are NOT listed here.
    # The path-mode resolver requires every ``uses:`` selector to be
    # findable on ``$PATH`` as an executable file, and these are
    # shared libraries, header bundles, or Nim source trees rather
    # than CLI binaries. They are provisioned by ``flake.nix`` /
    # ``nix/pkgs/by-name/re/reprobuild/package.nix`` via env vars
    # (BLAKE3_PREFIX / XXHASH_PREFIX / SQLITE_PREFIX / NIMCRYPTO_SRC /
    # RUNQUOTA_SRC / SSZ_SERIALIZATION_SRC) and consumed by
    # ``config.nims``. Once the DSL grows a typed "env-provided
    # dependency" concept (a ``provides:`` clause, or a Mode 2 catalog
    # shape for header-only / source-only deps) the list above will
    # grow back to capture them; until then the constraints live in
    # ``flake.nix`` and ``config.nims``.

  # Library declaration — every ``.nim`` file under ``libs/<name>/src``
  # that ``config.nims`` adds to ``--path`` is importable when this
  # package is consumed via ``uses: "reprobuild"``. The umbrella is
  # implicit (no single ``src/reprobuild.nim``); consumers import the
  # individual lib modules they need (``import repro_core``,
  # ``import repro_cli_support``, ...).
  library reprobuild

  # Shipping executables, one entry per non-comment line in
  # apps/entrypoints.txt. Nim identifiers are camelCase; the hyphenated
  # on-disk binary name is restored via ``name: "<bin>"``. The order
  # below matches apps/entrypoints.txt to make drift visually obvious.
  #
  # Bootstrap-And-Self-Build B1: the executable declarations stay as
  # naming/visibility records here; the per-executable ``nim.c(...)``
  # build edges are emitted in the package-level ``build:`` block below
  # (the project DSL's ``parseExecutable`` currently accepts only
  # ``name:`` and ``cli:`` body members — a ``build:`` body inside an
  # executable would be silently ignored, so the edges live one scope
  # out and aggregate into the ``apps`` build graph collection there).
  #
  # Executable-Consolidation M1 retired the five placeholder /
  # standalone-io-monitor entry points (repro-controller, repro-worker,
  # repro-provider-host, repro-hcr-link); io-monitor logic is
  # now reached via `repro internal io monitor` / `repro debug io monitor`.
  executable repro:
    discard

  executable reproCacheDaemon:
    name: "repro-cache-daemon"

  executable reproPeerCacheTier2:
    name: "repro-peer-cache-tier2"

  executable reproPeerCacheAdmin:
    name: "repro-peer-cache-admin"

  executable reproPeerCacheMintCert:
    name: "repro-peer-cache-mint-cert"

  executable reproCmakeDyndepFragment:
    name: "repro-cmake-dyndep-fragment"

  executable reproCmakeTrycompileProvider:
    name: "repro-cmake-trycompile-provider"

  executable reproStandardProvider:
    name: "repro-standard-provider"

  # Bootstrap-And-Self-Build B2: test-helper executables.
  #
  # Three helper binaries that more than one test suite reuses. Before
  # B2 these were direct ``nim c`` calls in ``scripts/run_tests.sh``
  # (the ``build_test_helper`` shell function + the
  # ``harness_apply_lock_holder`` block); B2 declares them as typed
  # ``executable`` blocks here and adds per-helper ``nim.c(...)`` edges
  # in the package-level ``build:`` body below. The helpers form their
  # own ``test-helpers`` build graph collection so consumers can
  # ``repro build .#test-helpers`` to materialise the trio in one
  # engine pass (and so test edges can declare typed-input dependencies
  # on them later — B2 spec deliverable note about
  # ``buildNimUnittest``'s ``inputs:`` slot).
  #
  # B5 retires the corresponding ``build_test_helper`` lines from
  # ``scripts/run_tests.sh`` once the in-graph path is the supported
  # one end-to-end.
  executable liveEndpointHelper:
    name: "live_endpoint_helper"

  executable fakeProtocolDaemonHelper:
    name: "fake_protocol_daemon_helper"

  executable harnessApplyLockHolder:
    name: "harness_apply_lock_holder"

  executable legacyCachePeerOriginDev:
    name: "legacy_cache_peer_origin_dev"

  # The A2/A2.5/A3/A4 binary-cache integration tests under
  # ``libs/repro_binary_cache_client/tests/`` spawn the
  # ``repro-binary-cache`` server daemon (and, for the A3 CLI gate, the
  # ``repro_binary_cache_client_cli`` test driver — a thin wrapper over
  # the shared ``runCacheSubcommand`` dispatch that now backs
  # ``repro cache``) as a subprocess from
  # ``build/test-bin/``. These were previously built only by the
  # Windows-only ``scripts/run-a2-gate.ps1`` gate, so the helpers were
  # absent on Linux/macOS and every binary-cache integration test
  # tripped its ``fileExists`` guard. Declaring them as ordinary
  # ``test-helpers`` build edges (below) makes them available on every
  # platform via the graph-native ``repro build .#test-helpers`` path.
  executable reproBinaryCacheHelper:
    name: "repro_binary_cache"

  executable reproBinaryCacheClientCliHelper:
    name: "repro_binary_cache_client_cli"

  build:
    # Install the in-process ct-test TestRunner adapter onto the active
    # build context up front, so any RUN/LIST/ENUMERATE the engine drives
    # for this project's test edges uses the protocol-aware adapter rather
    # than the stdlib's direct-binary default.
    installCtTestRunner(currentBuildContext())

    # Project-DSL-Composition M6: declared typed-output build edges for
    # every ``t_*.nim`` / ``test_*.nim`` file under tests/,
    # libs/*/tests/, and tools/*/tests/. The data table is generated by
    # ``scripts/generate_test_edges.nim`` into ``repro_tests.nim``; this
    # ``for`` loop registers one ``buildNimUnittest.build(...)`` edge
    # per ``TestSpec`` and aggregates the collected actions into the
    # ``test`` target so ``repro build test`` schedules every
    # test-binary compilation in one engine pass.
    #
    # The M5 active-build-context handle is what makes the iteration
    # shape work: each call to ``buildNimUnittest.build(...)`` reads
    # ``currentBuildState()`` to find the active package even though
    # the call now happens inside a runtime ``for`` loop rather than
    # at a literal top-level position in the ``build:`` body.
    #
    # Bootstrap-And-Self-Build B3: each TestSpec now expands into TWO
    # edges (per Package-Model.md §"The test template"):
    #
    #   * A BUILD edge — the compile-only ``buildNimUnittest.build(...)``
    #     call that produces ``build/test-bin/<stem>``. Actions accumulate
    #     into ``reprobuildTestBuildActions`` and collect into a
    #     ``test-builds`` build graph collection so callers that want
    #     compile-only verification (the old ``repro build test``
    #     semantics) can still do ``repro build .#test-builds``.
    #
    #   * An EXECUTE edge — ``edge.testBinary.run(...)`` per Package-
    #     Model.md ~line 994. The binary path flows in as a typed input
    #     so the engine action-cache keys on the binary content. When
    #     the TestSpec's ``requiresReproBinary`` flag is set the engine-
    #     built ``./build/bin/repro`` artifact is declared as an extra
    #     typed input via the ``requiredBinaries`` slot the
    #     ``ct_test_nim_unittest`` adapter exposes — this is the
    #     mechanism that triggers a ``repro`` rebuild before an e2e test
    #     runs, and re-runs the test execute edge when a source under
    #     ``libs/repro_*/`` changes. Execute actions accumulate into
    #     ``reprobuildTestExecuteActions`` and the resulting collection
    #     is registered as ``test``, so ``repro test`` /
    #     ``repro build test`` now materialises the EXECUTE closures
    #     (each execute action transitively depends on its build edge).
    #
    # B5 retires the out-of-band ``ct-test-runner`` walk of
    # ``build/test-bin/`` in favour of these graph-native execute edges
    # entirely; B3 + B4 land both paths in parallel.
    var reprobuildTestBuildActions: seq[BuildActionDef] = @[]
    var reprobuildTestExecuteActions: seq[BuildActionDef] = @[]
    const reproBinaryPath = "build/bin/repro"

    proc reproTestExecuteId(binary: string): string =
      ## Compute the per-test EXECUTE-edge action id from the build
      ## edge's binary path. Uses raw string-slicing instead of
      ## ``os.extractFilename`` because the package macro lifts the
      ## body into a generated proc whose scope does not transparently
      ## see ``std/os``.
      var lastSlash = -1
      for i in 0 ..< binary.len:
        if binary[i] == '/' or binary[i] == '\\':
          lastSlash = i
      let stem =
        if lastSlash >= 0: binary[lastSlash + 1 .. ^1]
        else: binary
      "reprobuild.test_execute." & stem

    # Bootstrap-And-Self-Build B4: the three macOS-arm64 HCR tests
    # carry ``extraPassC`` / ``extraPassL`` lists (the codesign
    # workaround flags that previously lived in ``scripts/run_tests.sh``'s
    # ``compile_hcr_workaround`` direct ``nim c`` re-compile loop) plus
    # ``targetOs: soMacosArm64`` as the cross-target guard.
    #
    # **B4 CI fix**: the original spec assumed gcc on Linux would
    # accept the macOS-only ``-Wl,-segprot,__HCR,rwx,rwx`` flag
    # harmlessly. binutils-ld instead errors out
    # (``unable to disambiguate: -segprot``), which broke ``just
    # test`` once D1 + D2 + D3 wired the engine through end-to-end.
    # The flags are macOS-only by construction; gating their
    # emission on ``when defined(macosx)`` at compile time of the
    # project interface DLL keeps the ``targetOs: soMacosArm64``
    # field documentary and avoids the linker error on Linux/Windows.
    # The HCR tests themselves are macOS-only at runtime anyway, so
    # the gated build edge still produces a compilable binary on
    # Linux/Windows for any non-runtime CI sweep.
    const hostIsMacos = defined(macosx)

    proc nixRuntimePassLForLibraries(libNames: openArray[string]): seq[string] =
      ## Some runtime paths are resolved by dlopen() from plain library names.
      ## Local graph-built binaries are not post-fixed by the flake package's
      ## patchelf hook, so thread the Nix-provided lib dirs into DT_RPATH when
      ## the dev shell exposes them.
      when defined(posix):
        var libDirs: seq[string] = @[]
        for envName in ["CLINGO_LIB", "ZSTD_LIB"]:
          let libDir = getEnv(envName)
          if libDir.len > 0 and libDir notin libDirs:
            for libName in libNames:
              if fileExists(libDir / libName):
                libDirs.add(libDir)
        for token in getEnv("NIX_LDFLAGS").splitWhitespace:
          if token.startsWith("-L"):
            let libDir = token[2 .. ^1]
            for libName in libNames:
              if fileExists(libDir / libName) and libDir notin libDirs:
                libDirs.add(libDir)
        when defined(macosx):
          let storeRoot = "/nix/store"
          if dirExists(storeRoot):
            for kind, path in walkDir(storeRoot):
              if kind != pcDir: continue
              let libDir = path / "lib"
              for libName in libNames:
                if fileExists(libDir / libName) and libDir notin libDirs:
                  libDirs.add(libDir)
        if libDirs.len > 0:
          when defined(linux):
            result.add("-Wl,--disable-new-dtags")
          for libDir in libDirs:
            result.add("-Wl,-rpath," & libDir)
      else:
        @[]

    let reproRuntimePassL = nixRuntimePassLForLibraries(@[
      "libclingo.so", "libclingo.dylib"])
    let testRuntimePassL = nixRuntimePassLForLibraries(@[
      "libclingo.so", "libclingo.dylib",
      "libzstd.so.1", "libzstd.dylib"])

    proc findNixStoreSourceDir(namePart, marker: string): string =
      when defined(posix):
        let storeRoot = "/nix/store"
        if dirExists(storeRoot):
          for kind, path in walkDir(storeRoot):
            if kind == pcDir and namePart in path.lastPathPart and
                fileExists(path / marker):
              return path
      ""

    proc nixDevShellSourcePath(envName, marker: string): string =
      when defined(windows):
        ""
      else:
        if not fileExists("flake.nix"):
          return ""
        let systemResult =
          uncontrolledExecCmdEx("nix eval --raw --impure --expr 'builtins.currentSystem' 2>/dev/null")
        if systemResult.exitCode != 0:
          return ""
        let system = systemResult.output.strip()
        if system.len == 0:
          return ""
        let valueResult = uncontrolledExecCmdEx(
          "nix eval --raw '.#devShells." & system & ".default." & envName &
          "' 2>/dev/null")
        if valueResult.exitCode != 0:
          return ""
        let candidate = valueResult.output.strip()
        if candidate.len > 0 and fileExists(candidate / marker):
          return candidate
        ""

    proc sourceOnlyPackagePath(envName: string; candidates: openArray[string];
                               marker: string; nixStoreNamePart = ""):
        tuple[path: string; env: seq[(string, string)]] =
      let fromEnv = getEnv(envName)
      if fromEnv.len > 0 and fileExists(fromEnv / marker):
        return (fromEnv, @[(envName, fromEnv)])
      for candidate in candidates:
        if fileExists(candidate / marker):
          return (candidate, @[(envName, candidate)])
      let fromFlake = nixDevShellSourcePath(envName, marker)
      if fromFlake.len > 0:
        return (fromFlake, @[(envName, fromFlake)])
      if nixStoreNamePart.len > 0:
        let fromStore = findNixStoreSourceDir(nixStoreNamePart, marker)
        if fromStore.len > 0:
          return (fromStore, @[(envName, fromStore)])
      ("", @[])

    proc resolvedIoMonNimPaths(): seq[string] =
      var candidates: seq[string] = @[]
      let fromEnv = getEnv("IO_MON_SRC")
      if fromEnv.len > 0:
        candidates.add(fromEnv)
        if not fromEnv.endsWith("/src") and not fromEnv.endsWith("\\src"):
          candidates.add(fromEnv / "src")
      candidates.add(".." / "io-mon" / "src")
      for candidate in candidates:
        if fileExists(candidate / "io_mon.nim"):
          return @[candidate]

    let ioMonNimPaths = resolvedIoMonNimPaths()
    let repoParent = ".."
    var sourceOnlyNimPaths: seq[string] = @[]
    var sourceOnlyEnv: seq[(string, string)] = @[]
    for pkg in [
      sourceOnlyPackagePath("NIMCRYPTO_SRC", [
        "libs" / "nimcrypto",
        repoParent / "codetracer" / "libs" / "nimcrypto",
        repoParent / "nimcrypto",
      ], "nimcrypto" / "hash.nim"),
      sourceOnlyPackagePath("BEARSSL_SRC", [
        "libs" / "nim-bearssl",
        repoParent / "nim-bearssl",
      ], "bearssl.nim", "nim-bearssl-"),
      sourceOnlyPackagePath("REPRO_TEST_ADAPTERS_SRC", [
        repoParent / "reprobuild-test-adapters" / "src",
      ], "repro_test_adapters" / "test_runner.nim"),
      sourceOnlyPackagePath("REPRO_CT_TEST_RUNNER_SRC", [
        repoParent / "reprobuild-ct-test-runner",
      ], "libs" / "ct_test_runner_adapter" / "src" /
        "ct_test_runner_adapter.nim"),
      sourceOnlyPackagePath("RUNQUOTA_SRC", [
        repoParent / "runquota",
      ], "runquota.nim"),
      sourceOnlyPackagePath("STACKABLE_HOOKS_SRC", [
        repoParent / "nim-stackable-hooks" / "src",
      ], "stackable_hooks.nim"),
      sourceOnlyPackagePath("SHM_QUEUE_SRC", [
        repoParent / "nim-shm-queue" / "src",
      ], "shm_queue.nim"),
    ]:
      if pkg.path.len > 0:
        sourceOnlyNimPaths.add(pkg.path)
        for entry in pkg.env:
          sourceOnlyEnv.add(entry)
    let testNimPaths = ioMonNimPaths & sourceOnlyNimPaths

    for spec in reprobuildTestSpecs:
      when defined(windows):
        if spec.source.contains("shm_index") or
           spec.source.contains("cache_daemon") or
           spec.source.contains("nix_daemon"):
          continue

      let platformPassC: seq[string] =
        when hostIsMacos: spec.extraPassC else: newSeq[string]()
      let platformPassL: seq[string] =
        when hostIsMacos: spec.extraPassL else: newSeq[string]()
      let edge = buildNimUnittest.build(
        source = spec.source,
        binary = spec.binary,
        defines = spec.defines,
        paths = testNimPaths,
        extraPassC = platformPassC,
        extraPassL = platformPassL & testRuntimePassL,
        extraEnv = sourceOnlyEnv,
        cacheable = false)
      reprobuildTestBuildActions.add(edge.action)
      # B3: emit the EXECUTE edge.
      #
      # ``requiredBinaries`` is the typed input slot the
      # ``ct_test_nim_unittest.run`` proc exposes (Bootstrap-And-Self-
      # Build B3 extension): when a TestSpec carries
      # ``requiresReproBinary``, the engine-built
      # single ``build/bin/repro`` CLI is recorded as an input on the execute
      # edge. Without the
      # flag the execute edge depends only on its own binary content —
      # keeping the action-cache fingerprint small for the 500+ tests
      # that do NOT spawn the CLI.
      let executeActionId = reproTestExecuteId(spec.binary)
      # ``registerImplicitName = false`` because the BUILD edge
      # already registers the binary basename as the implicit target
      # name for this package; the execute edge would otherwise
      # collide on the same name and the per-package target-export
      # table rejects the duplicate with a ``duplicate implicit target
      # name`` diagnostic at provider time. The explicit ``actionId``
      # is the selector for the execute edge.
      var requiredBinaries: seq[string] = @[]
      var executeDeps: seq[string] = @[]
      if spec.requiresReproBinary:
        requiredBinaries.add(reproBinaryPath)
      if spec.source ==
          "tests/integration/t_cache_daemon_drains_dedups_persists_and_warms_from_disk.nim":
        when not defined(windows):
          # Both separately compiled compatibility peers are runtime fixtures
          # of this integration binary. The typed input paths make a focused
          # graph target build them, while the explicit ids make the ordering
          # contract unambiguous even though helper declarations occur later.
          requiredBinaries.add("build/test-bin/legacy_cache_peer_origin_dev")
          requiredBinaries.add("build/test-bin/legacy_cache_peer_legacy_wire")
          executeDeps.add(
            "reprobuild.test_helpers.legacy_cache_peer_origin_dev")
          executeDeps.add(
            "reprobuild.test_helpers.legacy_cache_peer_legacy_wire")
      let executeEdge = edge.testBinary.run(
        deps = executeDeps,
        requiredBinaries = requiredBinaries,
        actionId = executeActionId,
        registerImplicitName = false)
      reprobuildTestExecuteActions.add(executeEdge)

    # Bootstrap-And-Self-Build B4: Python tests join the ``test``
    # collection as additional execute edges. Each entry in
    # ``pythonTestPaths`` (generated by
    # ``scripts/generate_test_edges.nim``) is a repo-relative path to a
    # ``tests/**/test_*.py`` file; the ``pythonUnittest.run(...)``
    # wrapper records a ``PublicCliCall`` against the ``python3``
    # profile so the engine schedules each Python test as an ordinary
    # execute edge alongside the Nim ones. The action id mirrors the
    # Nim convention (``reprobuild.python_test.<stem>``).
    #
    # Per the B3-outcome known limitation, the path-mode tool resolver
    # doesn't yet have a profile for ``pythonUnittest`` (nor for
    # ``ct_test_nim_unittest.buildNimUnittest``) — execute-edge
    # materialisation through the engine SKIPs with a classifier in
    # the B4 integration tests, and the structural arms PASS. B5
    # closes the loop once a tool profile lands.
    proc pythonTestActionId(source: string): string =
      var lastSlash = -1
      for i in 0 ..< source.len:
        if source[i] == '/' or source[i] == '\\':
          lastSlash = i
      var stem =
        if lastSlash >= 0: source[lastSlash + 1 .. ^1]
        else: source
      # Strip the trailing ``.py`` so the id reads cleanly.
      if stem.len >= 3 and stem[^3 .. ^1] == ".py":
        stem = stem[0 ..< stem.len - 3]
      "reprobuild.python_test." & stem

    for source in pythonTestPaths:
      let pyActionId = pythonTestActionId(source)
      let pyExecute = pythonUnittest.run(
        source = source,
        actionId = pyActionId)
      reprobuildTestExecuteActions.add(pyExecute)

    # Spec-Implementation M0: the ``test`` build graph collection
    # (per reprobuild-specs/Build-Graph-Collections.md). ``repro test``
    # and ``repro build test`` both materialize this collection's
    # closure.
    #
    # B3: the collection now holds EXECUTE edges (the build edges are
    # transitive inputs reached automatically by the engine's closure
    # walk). The semantic change is per Bootstrap-And-Self-Build B3
    # outcome and Package-Model.md §"The test template". The compile-
    # only verification (former ``repro build test`` semantics) is
    # available via the ``test-builds`` collection registered below.
    discard collect("test", reprobuildTestExecuteActions)

    # B3: a parallel collection of just the BUILD halves for callers
    # that want compile-only verification of the test corpus without
    # actually executing the tests (e.g. CI byte-equivalence checks,
    # the historical ``repro build test`` behaviour before B3).
    discard collect("test-builds", reprobuildTestBuildActions)

    # Bootstrap-And-Self-Build B1: per-app typed-tool build edges +
    # the ``apps`` build graph collection.
    #
    # One ``nim.c(...)`` edge per non-comment line in
    # ``apps/entrypoints.txt``. The mapping reproduces the per-entry
    # shell loop in ``scripts/build_apps.sh``: each entry's binary
    # basename becomes ``build/bin/<name>`` and the source path is the
    # ``.nim`` file under ``apps/<name>/<source>.nim``. The two
    # provider entries carry ``-d:reproProviderMode`` (the third field
    # in ``apps/entrypoints.txt`` for those rows).
    #
    # Per-app edge actions are accumulated into ``reprobuildAppsActions``
    # and folded into a build graph collection named ``apps`` via the
    # M0 ``collect`` primitive. ``repro build .#apps`` materialises
    # every member in one engine pass. (The fragment form ``.#apps``
    # is required because the CLI's path-vs-name classifier treats
    # bare ``apps`` as the on-disk ``apps/`` directory; the fragment
    # syntax disambiguates per the Named-Targets M3 rules in
    # CLI/build.md §"Target Selection".)
    #
    # B1 shipped these edges alongside the option-(A)
    # ``shell(command = "bash scripts/build_apps.sh", ...)`` wrapper so
    # consumers could cut over incrementally. B5 has since deleted that
    # wrapper: these edges are now the only path, and ``.#release`` is the
    # collection the release workflow builds.
    var reprobuildAppsActions: seq[BuildActionDef] = @[]

    reprobuildAppsActions.add(nim.c(
      source = "apps/repro/repro.nim",
      binary = "build/bin/repro",
      defines = @["release", "reproVendoredHash"],
      paths = ioMonNimPaths & sourceOnlyNimPaths,
      passL = reproRuntimePassL,
      nimcache = "build/nimcache/repro",
      cacheable = false,
      # The public launcher sits on the prompt-time dev-env no-op path.
      # Build it with the vendored portable hash backend so each no-op spawn
      # does not load the system libblake3 -> TBB/C++ runtime closure.
      extraEnv = sourceOnlyEnv & @[("REPROBUILD_USE_SYSTEM_HASH_LIBS", "0")],
      actionId = "reprobuild.apps.repro"))

    # The shared-memory action-cache daemon is spawned by build processes, so
    # it must be graph-owned alongside the engine binary. In particular, a
    # warm checkout must not retain an older daemon after the imported
    # repro_shm_index implementation changes.
    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-cache-daemon/repro_cache_daemon.nim",
      binary = "build/bin/repro-cache-daemon",
      defines = @["release"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-cache-daemon",
      cacheable = false,
      actionId = "reprobuild.apps.repro-cache-daemon"))

    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-peer-cache-tier2/repro_peer_cache_tier2.nim",
      binary = "build/bin/repro-peer-cache-tier2",
      defines = @["release"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-peer-cache-tier2",
      cacheable = false,
      actionId = "reprobuild.apps.repro-peer-cache-tier2"))

    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-peer-cache-admin/repro_peer_cache_admin.nim",
      binary = "build/bin/repro-peer-cache-admin",
      defines = @["release"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-peer-cache-admin",
      cacheable = false,
      actionId = "reprobuild.apps.repro-peer-cache-admin"))

    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-peer-cache-mint-cert/repro_peer_cache_mint_cert.nim",
      binary = "build/bin/repro-peer-cache-mint-cert",
      defines = @["release"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-peer-cache-mint-cert",
      cacheable = false,
      actionId = "reprobuild.apps.repro-peer-cache-mint-cert"))

    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-cmake-dyndep-fragment/repro_cmake_dyndep_fragment.nim",
      binary = "build/bin/repro-cmake-dyndep-fragment",
      defines = @["release"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-cmake-dyndep-fragment",
      cacheable = false,
      actionId = "reprobuild.apps.repro-cmake-dyndep-fragment"))

    # Provider-mode entries carry ``-d:reproProviderMode`` per the
    # third field on their ``apps/entrypoints.txt`` line.
    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-cmake-trycompile-provider/repro_cmake_trycompile_provider.nim",
      binary = "build/bin/repro-cmake-trycompile-provider",
      nimcache = "build/nimcache/repro-cmake-trycompile-provider",
      defines = @["release", "reproProviderMode"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      cacheable = false,
      actionId = "reprobuild.apps.repro-cmake-trycompile-provider"))

    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-standard-provider/repro_standard_provider.nim",
      binary = "build/bin/repro-standard-provider",
      nimcache = "build/nimcache/repro-standard-provider",
      defines = @["release", "reproProviderMode"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      cacheable = false,
      actionId = "reprobuild.apps.repro-standard-provider"))

    # ``cacheable = false`` is not incidental here, and this edge was the only
    # one in the block missing it. Via ``compileDependencyPolicy`` it is what
    # selects ``makeDepfilePolicy`` — evidence from the compiler's own depfile,
    # and NO monitor wrapping. Left at the default the edge takes
    # ``defaultDependencyPolicy()`` and is monitored like an opaque tool.
    #
    # On macOS that is the difference between building and not: in run
    # 30719789911 the release collection reported built=15/15 with every
    # depfile-policied sibling linking fine, and this single monitored edge
    # died on `clang` exiting non-zero while emitting no diagnostic of its own
    # — the same signature as the retired wrapper, which was monitored for the
    # same reason.
    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-install-mirror-publish/repro_install_mirror_publish.nim",
      binary = "build/bin/repro-install-mirror-publish",
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-install-mirror-publish",
      cacheable = false,
      actionId = "reprobuild.apps.repro-install-mirror-publish"))

    # B5: the last three ``apps/entrypoints.txt`` rows that had no edge and so
    # existed only inside the ``bash scripts/build_apps.sh`` wrapper. Moving
    # them here is not only bookkeeping — a ``nim.c`` edge with
    # ``cacheable = false`` resolves to ``makeDepfilePolicy`` (see
    # ``compileDependencyPolicy``), i.e. it is NOT monitor-wrapped, whereas
    # everything inside the wrapper runs as a child under the io-mon shim.
    #
    # ``ssl`` in ``defines`` is what the entrypoints file spells
    # ``--define:ssl``; the ``nim.c`` alias appends OpenSSL's ``-L`` itself via
    # ``opensslPassLForSsl``, which is the typed equivalent of the
    # ``ssl_passl`` NIX_LDFLAGS scrape in the shell loop.
    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-binary-cache/repro_binary_cache.nim",
      binary = "build/bin/repro-binary-cache",
      defines = @["release", "ssl"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-binary-cache",
      cacheable = false,
      actionId = "reprobuild.apps.repro-binary-cache"))

    reprobuildAppsActions.add(nim.c(
      source =
        "apps/repro-binary-cache-crosshost/repro_binary_cache_crosshost.nim",
      binary = "build/bin/repro-binary-cache-crosshost",
      defines = @["release"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-binary-cache-crosshost",
      cacheable = false,
      actionId = "reprobuild.apps.repro-binary-cache-crosshost"))

    # The only entrypoint with a row-local ``--path:``; it becomes an ordinary
    # entry in the typed ``paths`` list.
    reprobuildAppsActions.add(nim.c(
      source = "apps/repro-harvest-apt/repro_harvest_apt.nim",
      binary = "build/bin/repro-harvest-apt",
      defines = @["release", "ssl"],
      paths = @["apps/repro-harvest-apt/src"] & sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-harvest-apt",
      cacheable = false,
      actionId = "reprobuild.apps.repro-harvest-apt"))

    reprobuildAppsActions.add(shell(
      command = "mkdir -p build/bin && " &
        "cp tools/reprobuild-nix-daemon/reprobuild-nix-daemon " &
        "build/bin/reprobuild-nix-daemon && " &
        "chmod +x build/bin/reprobuild-nix-daemon",
      actionId = "reprobuild.apps.reprobuild-nix-daemon",
      extraInputs = @[
        "tools/reprobuild-nix-daemon/reprobuild-nix-daemon",
      ],
       extraOutputs = @[
         "build/bin/reprobuild-nix-daemon",
       ]))

    # B5: Windows runtime-DLL staging, previously ~200 lines of shell inside the
    # wrapper. Every non-system library reprobuild uses on Windows is dlopen'd
    # by leaf name, and Win32 searches the .exe's own directory first, so these
    # have to sit in build/bin next to the binaries.
    #
    # The interesting part is WHERE the resolution happens. The shell version
    # probed PATH at run time inside an opaque action; here the probing is
    # ordinary Nim executed while the graph is being constructed, and what
    # reaches the graph is a declarative `fs.copyFile` edge with a concrete
    # source and a declared output. The engine can therefore see the dependency
    # instead of watching a shell script for side effects.
    #
    # Not cacheable: the source is a machine-specific absolute path outside the
    # repo (a provisioned toolchain), so its content is not addressed by
    # anything in the action key.
    #
    # An unresolved library emits NO edge rather than failing graph
    # construction — graph evaluation runs for every `repro` command, including
    # ones that build none of this, and a missing optional DLL must not make the
    # whole project unloadable. The gates stay where they were: scripts/build_apps.sh
    # still hard-errors on a missing clingo for `just bootstrap`, and
    # scripts/verify_release.sh fails any archive whose bin/ is incomplete.
    when defined(windows):
      proc firstExistingDll(candidates: openArray[string]): string =
        for candidate in candidates:
          if candidate.len > 0 and fileExists(candidate):
            return candidate
        ""

      proc siblingOf(exeName, dllName: string): string =
        let exe = uncontrolledFindExe(exeName)
        if exe.len == 0: "" else: exe.parentDir / dllName

      # clingo — dlopen'd at MODULE INIT by repro_solver, so a repro.exe
      # without it beside the binary has no working subcommand at all.
      let clingoDir = getEnv("REPRO_WINDOWS_CLINGO_DIR")
      let clingoSrc = firstExistingDll([
        (if clingoDir.len > 0: clingoDir / "clingo.dll" else: ""),
        siblingOf("clingo", "clingo.dll")])
      if clingoSrc.len > 0:
        reprobuildAppsActions.add(dslfs.copyFile(clingoSrc,
          "build/bin/clingo.dll", cacheable = false,
          actionId = "reprobuild.apps.stage_clingo_dll"))

      # libzstd — lazily loaded by `repro cache substitute`. Two upstream
      # layouts: MSYS2 co-locates the DLL with zstd.exe; the facebook/zstd
      # win64 release puts it under a sibling dll/ directory.
      let zstdExe = uncontrolledFindExe("zstd")
      let zstdDir = if zstdExe.len == 0: "" else: zstdExe.parentDir
      let zstdSrc = firstExistingDll([
        (if zstdDir.len > 0: zstdDir / "libzstd.dll" else: ""),
        (if zstdDir.len > 0: zstdDir / "dll" / "libzstd.dll" else: "")])
      if zstdSrc.len > 0:
        reprobuildAppsActions.add(dslfs.copyFile(zstdSrc,
          "build/bin/libzstd.dll", cacheable = false,
          actionId = "reprobuild.apps.stage_libzstd_dll"))

      # sqlite3 — repro_local_store's dynlib. The Windows Nim distribution
      # ships it inside its own tree; probe the layouts Nim has used, then the
      # bare DLL on PATH. Staged under BOTH names because the Nim binding's
      # candidate list tries `sqlite3_64.dll` and `sqlite3.dll`.
      let nimExe = uncontrolledFindExe("nim")
      let nimBinDir = if nimExe.len == 0: "" else: nimExe.parentDir
      let nimRootDir = if nimBinDir.len == 0: "" else: nimBinDir.parentDir
      let sqliteSrc = firstExistingDll([
        (if nimBinDir.len > 0: nimBinDir / "sqlite3_64.dll" else: ""),
        (if nimRootDir.len > 0: nimRootDir / "dist" / "sqlite3_64.dll" else: ""),
        (if nimRootDir.len > 0: nimRootDir / "dlls" / "sqlite3_64.dll" else: ""),
        (if nimRootDir.len > 0: nimRootDir / "bin" / "sqlite3_64.dll" else: ""),
        uncontrolledFindExe("sqlite3_64.dll")])
      if sqliteSrc.len > 0:
        reprobuildAppsActions.add(dslfs.copyFile(sqliteSrc,
          "build/bin/sqlite3_64.dll", cacheable = false,
          actionId = "reprobuild.apps.stage_sqlite3_64_dll"))
        reprobuildAppsActions.add(dslfs.copyFile(sqliteSrc,
          "build/bin/sqlite3.dll", cacheable = false,
          actionId = "reprobuild.apps.stage_sqlite3_dll"))

      # OpenSSL — the --define:ssl entry points dlopen these. release.yml also
      # stages them with a recursive PowerShell scavenge of Program Files,
      # which reaches installs this narrow probe does not. Both are kept on
      # purpose: this edge covers the ordinary dev machine, and because an
      # unresolved probe emits no edge at all, the workflow's scavenge remains
      # the fallback rather than being contradicted by an empty copy.
      for opensslDll in ["libcrypto-3-x64.dll", "libssl-3-x64.dll"]:
        let opensslSrc = firstExistingDll([
          siblingOf("openssl", opensslDll), uncontrolledFindExe(opensslDll)])
        if opensslSrc.len > 0:
          reprobuildAppsActions.add(dslfs.copyFile(opensslSrc,
            "build/bin/" & opensslDll, cacheable = false,
            actionId = "reprobuild.apps.stage_" &
              opensslDll.replace("-", "_").replace(".dll", "")))

    discard collect("apps", reprobuildAppsActions)

    # Bootstrap-And-Self-Build B2: per-helper typed-tool build edges +
    # the ``test-helpers`` build graph collection.
    #
    # One ``nim.c(...)`` edge per helper binary. The source paths
    # mirror the three ``build_test_helper`` (and one inline ``nim c``)
    # invocations in ``scripts/run_tests.sh``:
    #
    #   * ``live_endpoint_helper`` —
    #     ``tests/fixtures/local-daemons-control-plane/live-endpoint-helper/``
    #   * ``fake_protocol_daemon_helper`` —
    #     ``tests/fixtures/local-daemons-control-plane/fake-protocol-daemon-helper/``
    #   * ``harness_apply_lock_holder`` —
    #     ``tests/e2e/home-generations/``
    #
    # The three actions aggregate into a separate ``test-helpers``
    # collection (NOT ``apps`` — apps are shipping binaries; helpers
    # are test scaffolding). ``repro build .#test-helpers`` materialises
    # all three in one engine pass. As with ``apps``, the fragment form
    # is required because the path-vs-name classifier would otherwise
    # try to resolve ``test-helpers`` against the on-disk tree.
    #
    # The corresponding ``build_test_helper`` / inline ``nim c`` lines
    # in ``scripts/run_tests.sh`` stay during the transition; B5
    # retires them once the in-graph path is the supported one.
    var reprobuildTestHelpersActions: seq[BuildActionDef] = @[]

    reprobuildTestHelpersActions.add(nim.c(
      source = "tests/fixtures/local-daemons-control-plane/live-endpoint-helper/live_endpoint_helper.nim",
      binary = "build/test-bin/live_endpoint_helper",
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/live_endpoint_helper",
      cacheable = false,
      actionId = "reprobuild.test_helpers.live_endpoint_helper"))

    reprobuildTestHelpersActions.add(nim.c(
      source = "tests/fixtures/local-daemons-control-plane/fake-protocol-daemon-helper/fake_protocol_daemon_helper.nim",
      binary = "build/test-bin/fake_protocol_daemon_helper",
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/fake_protocol_daemon_helper",
      cacheable = false,
      actionId = "reprobuild.test_helpers.fake_protocol_daemon_helper"))

    reprobuildTestHelpersActions.add(nim.c(
      source = "tests/e2e/home-generations/harness_apply_lock_holder.nim",
      binary = "build/test-bin/harness_apply_lock_holder",
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/harness_apply_lock_holder",
      cacheable = false,
      actionId = "reprobuild.test_helpers.harness_apply_lock_holder"))

    # Cross-version action-cache lifecycle peers. The exact peer compiles all
    # implementation files byte-for-byte from the pinned origin/dev commit.
    # The legacy-wire peer is generated from those same audited blobs; five
    # modules remain byte-identical and only the top/segment modules receive
    # cardinality-checked Darwin boot-id + lifecycle-name substitutions.
    let legacyWireGeneratedRoot =
      "build/test-fixtures/cache-daemon-legacy-wire"
    let legacyWireGeneratedSources = @[
      legacyWireGeneratedRoot &
        "/libs/repro_shm_index/src/repro_shm_index.nim",
      legacyWireGeneratedRoot &
        "/libs/repro_shm_index/src/repro_shm_index/atomics_shm.nim",
      legacyWireGeneratedRoot &
        "/libs/repro_shm_index/src/repro_shm_index/daemon.nim",
      legacyWireGeneratedRoot &
        "/libs/repro_shm_index/src/repro_shm_index/layout.nim",
      legacyWireGeneratedRoot &
        "/libs/repro_shm_index/src/repro_shm_index/mapping.nim",
      legacyWireGeneratedRoot &
        "/libs/repro_shm_index/src/repro_shm_index/ring.nim",
      legacyWireGeneratedRoot &
        "/libs/repro_shm_index/src/repro_shm_index/segment.nim",
    ]
    let legacyWireOriginSources = @[
      "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index.nim",
      "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/atomics_shm.nim",
      "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/daemon.nim",
      "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/layout.nim",
      "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/mapping.nim",
      "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/ring.nim",
      "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/segment.nim",
    ]
    let legacyWireGenerator = sh.shell(
      command = "python3 tests/fixtures/cache-daemon-origin-dev-9f0a9be/generate_legacy_wire.py --output-root " &
        legacyWireGeneratedRoot,
      actionId = "reprobuild.test_helpers.generate_legacy_cache_peer_wire",
      extraInputs = legacyWireOriginSources & @[
        "tests/fixtures/cache-daemon-origin-dev-9f0a9be/generate_legacy_wire.py",
      ],
      extraOutputs = legacyWireGeneratedSources,
      cacheable = false)
    reprobuildTestHelpersActions.add(legacyWireGenerator)

    when not defined(windows):
      reprobuildTestHelpersActions.add(nim.c(
        source = "tests/fixtures/cache-daemon-origin-dev-9f0a9be/legacy_cache_peer.nim",
        binary = "build/test-bin/legacy_cache_peer_origin_dev",
        paths = sourceOnlyNimPaths,
        extraInputs = @[
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/README.md",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/legacy_cache_peer_main.nim",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index.nim",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/atomics_shm.nim",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/daemon.nim",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/layout.nim",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/mapping.nim",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/ring.nim",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/origin/libs/repro_shm_index/src/repro_shm_index/segment.nim",
        ],
        extraEnv = sourceOnlyEnv,
        nimcache = "build/nimcache/legacy_cache_peer_origin_dev",
        cacheable = false,
        actionId = "reprobuild.test_helpers.legacy_cache_peer_origin_dev"))

      reprobuildTestHelpersActions.add(nim.c(
        source = "tests/fixtures/cache-daemon-origin-dev-9f0a9be/legacy_cache_peer_legacy_wire.nim",
        binary = "build/test-bin/legacy_cache_peer_legacy_wire",
        paths = sourceOnlyNimPaths,
        extraInputs = legacyWireGeneratedSources & @[
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/README.md",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/generate_legacy_wire.py",
          "tests/fixtures/cache-daemon-origin-dev-9f0a9be/legacy_cache_peer_main.nim",
        ],
        after = [legacyWireGenerator],
        extraEnv = sourceOnlyEnv,
        nimcache = "build/nimcache/legacy_cache_peer_legacy_wire",
        cacheable = false,
        actionId = "reprobuild.test_helpers.legacy_cache_peer_legacy_wire"))

    # Binary-cache integration-test subprocess helpers (A2/A2.5/A3/A4).
    #
    # The ``repro-binary-cache`` server daemon is the SAME shipping app
    # source used under ``apps/``. The client-side driver
    # (``repro_binary_cache_client_cli``) is a test-only wrapper over the
    # shared ``runCacheSubcommand`` dispatch that backs the shipping
    # ``repro cache`` subcommand — the standalone
    # ``repro-binary-cache-client`` binary was retired (Binary-Caches.md
    # §"Client CLI Surface"). The integration tests spawn both from
    # ``build/test-bin/`` (alongside the other test helpers) rather than
    # from ``build/bin/``. Previously these were produced only by
    # the Windows-only ``scripts/run-a2-gate.ps1`` gate, so the helper
    # binaries never existed on Linux/macOS and every binary-cache
    # integration test failed its ``fileExists`` guard. Declaring them
    # here as ordinary graph edges materialises both on every platform
    # via ``repro build .#test-helpers``.
    #
    # ``repro_binary_cache`` stays plain for A2-A4 HTTP gates, while the
    # M6 helper carries ``-d:ssl`` because that gate exercises the daemon's
    # HTTPS listener with real TLS.
    #
    # Both helpers (and the shipped ``repro-binary-cache`` entrypoint) build
    # from the same ``repro_binary_cache`` source. Nim writes the linker
    # response file as ``<projectName>_linkerArgs.txt`` into its process CWD
    # and ``removeFile``s it right after linking (compiler/extccomp.nim), so
    # two build actions compiling that source under the SAME projectName race
    # on that one shared file — one action's post-link cleanup deletes it
    # while the other's ``gcc @…`` is still reading it (the intermittent
    # ``cannot find @repro_binary_cache_linkerArgs.txt`` link failure). Each
    # helper therefore compiles through its own uniquely-named ``include``
    # wrapper entry module so Nim derives a DISTINCT projectName (hence a
    # distinct response-file name) per action. This removes the collision at
    # the source, with no per-action CWD juggling.
    reprobuildTestHelpersActions.add(nim.c(
      source = "apps/repro-binary-cache/repro_binary_cache_a2.nim",
      binary = "build/test-bin/repro_binary_cache",
      paths = sourceOnlyNimPaths,
      passL = testRuntimePassL,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro_binary_cache",
      cacheable = false,
      actionId = "reprobuild.test_helpers.repro_binary_cache"))

    reprobuildTestHelpersActions.add(nim.c(
      source = "apps/repro-binary-cache/repro_binary_cache_m6.nim",
      binary = "build/test-bin/repro_binary_cache_m6",
      defines = @["ssl"],
      paths = sourceOnlyNimPaths,
      passL = testRuntimePassL,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro_binary_cache_m6",
      cacheable = false,
      actionId = "reprobuild.test_helpers.repro_binary_cache_m6"))

    reprobuildTestHelpersActions.add(nim.c(
      source = "libs/repro_binary_cache_client/tests/repro_binary_cache_client_cli.nim",
      binary = "build/test-bin/repro_binary_cache_client_cli",
      defines = @["ssl"],
      paths = sourceOnlyNimPaths,
      passL = testRuntimePassL,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro_binary_cache_client_cli",
      cacheable = false,
      actionId = "reprobuild.test_helpers.repro_binary_cache_client_cli"))

    discard collect("test-helpers", reprobuildTestHelpersActions)

    # Test-Fixtures-In-Build-Graph M2: the monitor-shim ``test-fixtures``
    # collection.
    #
    # The monitor shim (built ``nim c --app:lib``) was compiled per test by
    # ``repro_test_support.prepareMonitorTools`` (22 callers) and again, ad
    # hoc, by three self-shim outlier tests. M2 lifted that compilation into a
    # single graph edge that produces the shim at the SAME stable path
    # ``scripts/build_apps.sh`` writes — ``build/lib/librepro_monitor_shim.<ext>``
    # — so the per-test code can ``requireBinary`` it instead of shelling out
    # to a compiler.
    #
    # Incremental-Test-Runner M7: the shim's SOURCE now lives in the shared
    # ``io-mon`` sibling (``io_mon/shim/*`` + ``io_mon/hooks/*`` on
    # nim-stackable-hooks) rather than reprobuild's deleted
    # ``repro_monitor_shim`` library. The output filename, exported interpose
    # ABI, and the per-platform flags are byte-identical (io-mon is a
    # relocation), so the graph edge still produces the SAME artifact at the
    # SAME path; only the ``source``/``--path:`` roots changed. The io-mon
    # sibling is resolved at ``../io-mon/src`` (override with ``$IO_MON_SRC``)
    # and nim-stackable-hooks at ``../nim-stackable-hooks/src`` (override with
    # ``$STACKABLE_HOOKS_SRC``), the same siblings ``config.nims`` /
    # ``scripts/build_apps.sh`` use.
    #
    # The platform arm is gated on ``when defined(...)`` of the host OS, the
    # same compile-time-host pattern the B4 ``hostIsMacos`` HCR gate uses
    # above. The shim is a host-native artifact (LD_PRELOAD / DYLD_INSERT
    # / IAT-patch DLL), so the host arm is the correct (and only) target.
    var reprobuildTestFixturesActions: seq[BuildActionDef] = @[]

    # B5: the two artifacts under ``build/lib`` that a RELEASE ships — the
    # monitor shim and the shared DSL runtime library. They live in
    # ``test-fixtures`` for historical reasons (the shim arrived as a test
    # fixture), but the release tarball packages ``build/lib/*``, so they are
    # also collected here and exposed through the ``release`` collection below.
    # Same BuildActionDef in both collections: one action, one actionId, one
    # graph node — collecting it twice groups it, it does not duplicate it.
    var reprobuildLibActions: seq[BuildActionDef] = @[]

    # M76 shell-hook tests need a small counting shim to assert whether prompt
    # evaluation spawned ``repro dev-env export``. Keep that executable in the
    # build graph so tests never invoke ``nim c`` at runtime.
    reprobuildTestFixturesActions.add(nim.c(
      source = "tests/fixtures/shell-hook-counting-shim/repro_shell_hook_counting_shim.nim",
      binary = "build/test-bin/repro_shell_hook_counting_shim",
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro_shell_hook_counting_shim",
      cacheable = false,
      actionId = "reprobuild.test_fixtures.shell_hook_counting_shim"))

    # Variant/configuration tests need subprocess probes so module-level
    # configurable solving can run under a different REPRO_VARIANTS value.
    # Build those probes once in the graph; the tests only execute them.
    reprobuildTestFixturesActions.add(nim.c(
      source = "tests/fixtures/spec-examples/variant-feature-flag/probe_enable_tls_false.nim",
      binary = "build/test-bin/variant_feature_flag_probe",
      paths = sourceOnlyNimPaths,
      passL = reproRuntimePassL,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/variant_feature_flag_probe",
      cacheable = false,
      actionId = "reprobuild.test_fixtures.variant_feature_flag_probe"))
    reprobuildTestFixturesActions.add(nim.c(
      source = "tests/fixtures/spec-examples/buildtype-output/probe_release.nim",
      binary = "build/test-bin/buildtype_output_probe",
      paths = sourceOnlyNimPaths,
      passL = reproRuntimePassL,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/buildtype_output_probe",
      cacheable = false,
      actionId = "reprobuild.test_fixtures.buildtype_output_probe"))

    let ioMonSrc = block:
      let fromEnv = CompileTimeIoMonSrc
      if fromEnv.len > 0: fromEnv else: ".." / "io-mon" / "src"
    let stackableHooksSrc = block:
      let fromEnv = CompileTimeStackableHooksSrc
      if fromEnv.len > 0: fromEnv else: ".." / "nim-stackable-hooks" / "src"
    let monitorShimNimcache = "build/nimcache/repro_monitor_shim"
    # The fixture builds the preload monitor itself. Running that compiler
    # process under the same preload shim can trigger host compiler ICEs; keep
    # the edge non-cacheable and avoid monitor wrapping rather than recording
    # incomplete or unstable evidence.
    let monitorShimPolicy =
      makeDepfilePolicy(monitorShimNimcache / "nim-compile.d")

    when defined(macosx):
      const macosShimArchFlags =
        when defined(arm64) or defined(aarch64):
          @["-arch arm64", "-arch arm64e"]
        else:
          @[]
      reprobuildTestFixturesActions.add(nim.c(
        source = ioMonSrc / "io_mon" / "shim" / "macos_interpose.nim",
        binary = "build/lib/librepro_monitor_shim.dylib",
        appLib = true,
        threadsOn = true,
        paths = @[ioMonSrc, stackableHooksSrc],
        passC = macosShimArchFlags,
        passL = macosShimArchFlags,
        nimcache = monitorShimNimcache,
        cacheable = false,
        dependencyPolicy = monitorShimPolicy,
        actionId = "reprobuild.test_fixtures.monitor_shim"))
      reprobuildLibActions.add(reprobuildTestFixturesActions[^1])
    elif defined(windows):
      # The Windows shim imports the stackable-hooks framework primitives;
      # the path list + ``--mm:orc`` / ``--cc:gcc`` mirror the Windows arm
      # of ``scripts/build_apps.sh`` and io-mon's ``build_shim.sh``.
      reprobuildTestFixturesActions.add(nim.c(
        source = ioMonSrc / "io_mon" / "shim" / "windows_interpose.nim",
        binary = "build/lib/librepro_monitor_shim.dll",
        appLib = true,
        threadsOn = true,
        paths = @[ioMonSrc, stackableHooksSrc],
        nimcache = monitorShimNimcache,
        cacheable = false,
        dependencyPolicy = monitorShimPolicy,
        actionId = "reprobuild.test_fixtures.monitor_shim"))
      reprobuildLibActions.add(reprobuildTestFixturesActions[^1])
    else:
      # The Linux shim exports a version-scripted, interposed ``dlsym``
      # (``.symver …,dlsym@GLIBC_2.2.5`` / ``@GLIBC_2.34`` in
      # ``linux_preload_runtime.nim``); the ``GLIBC_2.2.5`` version node only
      # exists if the linker is handed io-mon's ``linux_preload_versions.map``.
      # io-mon's ``build_shim.sh`` passes it via ``--version-script``; mirror it
      # here or the fixture link fails with "version node not found for symbol
      # dlsym@GLIBC_2.2.5 / failed to set dynamic section sizes".
      let linuxShimVersionScript =
        ioMonSrc / "io_mon" / "hooks" / "linux_preload_versions.map"
      reprobuildTestFixturesActions.add(nim.c(
        source = ioMonSrc / "io_mon" / "shim" / "linux_preload.nim",
        binary = "build/lib/librepro_monitor_shim.so",
        appLib = true,
        threadsOn = true,
        paths = @[ioMonSrc, stackableHooksSrc],
        passL = @["-Wl,--version-script=" & linuxShimVersionScript],
        nimcache = monitorShimNimcache,
        cacheable = false,
        dependencyPolicy = monitorShimPolicy,
        actionId = "reprobuild.test_fixtures.monitor_shim"))
      reprobuildLibActions.add(reprobuildTestFixturesActions[^1])


    # B5 DONE: the ``shell(command = "bash scripts/build_apps.sh")`` wrapper
    # that used to sit here is GONE.
    #
    # It was "Option (A) from the repo packaging memo" — wrap the shell build
    # byte-for-byte as one opaque action while the graph grew native edges for
    # its contents. Every piece now has one: the per-app ``nim.c`` edges above,
    # the three B5 entrypoints, the Windows runtime-DLL ``fs.copyFile`` edges,
    # the monitor shim, and the shared DSL runtime library.
    #
    # Removing it is what actually fixes the macOS release. A ``shell()`` action
    # takes ``automaticMonitorPolicy()``, so the wrapper ran the ENTIRE build —
    # every nim compile, every clang link — as children under the io-mon shim,
    # and on macOS those children die producing no output (empty ``uname``,
    # silent clang). The replacement edges are ``nim.c`` with
    # ``cacheable = false``, which resolves to ``makeDepfilePolicy``: real
    # dependency evidence from the compiler's own depfiles, and no monitor
    # wrapping. That is the sanctioned route — NOT the ``declaredOnly`` policy
    # removed in runtime_core.nim as an unapproved soundness hole.
    #
    # ``scripts/build_apps.sh`` itself stays and remains a complete standalone
    # build: it is what ``just bootstrap`` runs to produce the engine in the
    # first place, so it cannot be expressed as engine edges without a
    # chicken-and-egg. What is gone is the engine ACTION that re-ran it.

    # B5: the shared DSL runtime library (Tier 1 in
    # reprobuild-specs/Provider-Compile-Tiering.md). Per-project provider
    # compiles link against this instead of statically embedding the DSL +
    # runtime surface, so it must carry ``reproProviderMode`` to expose the
    # provider-mode-only runtime procs, plus ``reproProviderRuntimeDll``.
    #
    # Previously built only inside the wrapper, which compiled it to
    # ``.new.<ext>`` and then ``mv``-ed it over the live file. The rename dance
    # exists because a shell script has no way to say "this file is my output";
    # an edge does, so the edge writes the final path directly and the engine
    # owns it. Like every other ``nim.c`` edge here it is ``cacheable = false``
    # and therefore depfile-policied rather than monitor-wrapped.
    const dslRuntimeDllExt =
      when defined(macosx): "dylib"
      elif defined(windows): "dll"
      else: "so"
    reprobuildTestFixturesActions.add(nim.c(
      source =
        "libs/repro_project_dsl_runtime_dll/src/repro_project_dsl_runtime_entry.nim",
      binary = "build/lib/librepro_project_dsl_runtime." & dslRuntimeDllExt,
      appLib = true,
      threadsOn = true,
      mm = "orc",
      defines = @["reproProviderMode", "reproProviderRuntimeDll"],
      paths = sourceOnlyNimPaths,
      extraEnv = sourceOnlyEnv,
      nimcache = "build/nimcache/repro-project-dsl-runtime-dll",
      cacheable = false,
      actionId = "reprobuild.test_fixtures.project_dsl_runtime_dll"))
    reprobuildLibActions.add(reprobuildTestFixturesActions[^1])

    # No publish edge is added here on purpose. ``build/lib/librepro_monitor_shim.<ext>``
    # is ALREADY an owned output of the ``reprobuild.test_fixtures.monitor_shim``
    # nim edge above, and the engine rejects two edges claiming the same output
    # ("duplicate owned effect claim in fragment"). More importantly that edge is
    # the right owner: it carries ``makeDepfilePolicy``, so it is NOT
    # monitor-wrapped, and writing the live shim from an unmonitored edge is
    # exactly the property that makes it safe.
    #
    # The unmonitored nim edge is the sole producer of the live shim. A
    # standalone ``just bootstrap`` publishes it inline instead
    # (REPRO_DEFER_SHIM_PUBLISH unset), which is what puts the shim in place
    # before an engine build starts monitoring anything.

    # Collected LAST, once every fixture edge above has been appended.
    # ``collect`` takes the seq by value, so a collect placed mid-block silently
    # omits everything added after it.
    discard collect("test-fixtures", reprobuildTestFixturesActions)

    # B5: what a release actually ships — every ``build/bin`` artifact plus the
    # two ``build/lib`` libraries the tarball packages. This is the target that
    # replaces ``.#reprobuild.build_apps`` in .github/workflows/release.yml.
    #
    # The lib actions are the SAME BuildActionDef objects already collected into
    # ``test-fixtures``; collecting an action twice groups it under both names,
    # it does not create a second graph node or a second owner of its output.
    discard collect("release", reprobuildAppsActions & reprobuildLibActions)
