#!/usr/bin/env bash
# t_c3_launcher_linux_exec.sh — C3 launcher direct kernel-side test.
#
# Linux-only counterpart to t_c3_launcher_git.sh. Exercises the
# launcher's actual unshare(2) + mount(2) + execve(2) path against a
# hand-crafted manifest + statically-linked probe binary.
#
# t_c3_launcher_git.sh exercises the manifest GENERATION pipeline via
# the Nim helper; this test exercises the manifest EXECUTION pipeline
# via the C launcher. Together they cover the full C3 deliverable.
#
# Skipped on non-Linux: the C3 launcher is a no-op stub on Windows.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

c3_skip_on_windows "t_c3_launcher_linux_exec"

case "$(uname -s 2>/dev/null || echo Unknown)" in
  Linux) ;;
  *)
    echo "SKIP: t_c3_launcher_linux_exec (non-Linux: $(uname -s))"
    exit 0;;
esac

if ! c3_have_userns; then
  echo "SKIP: t_c3_launcher_linux_exec (no unprivileged userns)"
  exit 0
fi

workdir="$(c2_make_workdir c3-exec)"
trap 'rm -rf "$workdir"' EXIT

launcher_bin="$(c3_launcher_binary)"

# Plant a fake content-addressed prefix for libc6 with a recognizable
# blob, and a fake content-addressed prefix for git with a static
# probe binary that prints a fingerprint and verifies the bind mount.
mkdir -p "$workdir/prefixes/git/usr/bin"
mkdir -p "$workdir/prefixes/libc6/lib"
echo "fake-libc6-data" > "$workdir/prefixes/libc6/lib/libc.so.fake"

cat > "$workdir/fakegit.c" <<'CSRC'
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
int main(int argc, char **argv) {
    printf("C3_KERNEL_TEST_FINGERPRINT_alpha\n");
    int fd = open("/lib/libc.so.fake", O_RDONLY);
    if (fd >= 0) {
        char buf[256];
        int n = read(fd, buf, sizeof(buf) - 1);
        if (n > 0) { buf[n] = 0; printf("FOUND_BIND: %s", buf); }
        close(fd);
    } else {
        printf("BIND_NOT_FOUND\n");
    }
    for (int i = 1; i < argc; i++) printf("argv[%d]=%s\n", i, argv[i]);
    return 0;
}
CSRC
if ! cc -static -O2 -o "$workdir/prefixes/git/usr/bin/fake-git" \
     "$workdir/fakegit.c" 2>"$workdir/cc.log"; then
  cat "$workdir/cc.log" >&2
  echo "SKIP: cc -static failed; cannot build the probe"
  exit 0
fi

# Build the launcher manifest by hand.
cat > "$workdir/m.manifest" <<EOF
exec=$workdir/prefixes/git/usr/bin/fake-git
$workdir/prefixes/libc6/lib:/lib:rbind,ro
EOF

# === Test 1: dry-run parses the manifest ===
"$launcher_bin" --manifest="$workdir/m.manifest" --dry-run \
  > "$workdir/dry.log" 2>&1 || \
  { cat "$workdir/dry.log" >&2; c2_fail "dry-run failed"; }
c2_ok "launcher --dry-run parses the hand-crafted manifest"

# === Test 2: real run executes the probe inside the namespace ===
out=$("$launcher_bin" --manifest="$workdir/m.manifest" -- arg1 arg2 2>&1) || \
  { echo "$out" >&2; c2_fail "real launcher run failed"; }

if ! echo "$out" | grep -q "C3_KERNEL_TEST_FINGERPRINT_alpha"; then
  echo "$out" >&2
  c2_fail "launcher did not produce the probe fingerprint"
fi
c2_ok "launcher executed the probe (fingerprint matched)"

# === Test 3: bind mount visible inside the namespace ===
if ! echo "$out" | grep -q "FOUND_BIND: fake-libc6-data"; then
  echo "$out" >&2
  c2_fail "libc6 bind mount not visible inside the namespace"
fi
c2_ok "/lib/libc.so.fake bind mount visible inside the namespace"

# === Test 4: argv forwarding works ===
if ! echo "$out" | grep -q "argv\[1\]=arg1"; then
  echo "$out" >&2
  c2_fail "launcher did not forward argv to the wrapped binary"
fi
if ! echo "$out" | grep -q "argv\[2\]=arg2"; then
  echo "$out" >&2
  c2_fail "launcher did not forward the second arg"
fi
c2_ok "launcher forwarded arg1 + arg2 to the wrapped binary"

# === Test 5: bind mount did NOT leak to host ===
if [ -f /lib/libc.so.fake ]; then
  c2_fail "host /lib/libc.so.fake appeared after the launcher ran"
fi
c2_ok "namespace bind mount did NOT leak into the host /lib"

# === Test 6: shim emission via the C3 generator ===
# Build a shim that invokes the launcher. (Cannot use the Nim helper
# in plain WSL Ubuntu; manually compose what the helper would emit.)
shim_dir="$workdir/shim_dir"
mkdir -p "$shim_dir"
cat > "$shim_dir/git" <<EOF
#!/bin/sh
# Auto-generated by repro_local_store/sandbox_manifest.nim
# (this test composes the equivalent by hand)
exec $launcher_bin --manifest=$workdir/m.manifest --exec=$workdir/prefixes/git/usr/bin/fake-git -- "\$@"
EOF
chmod +x "$shim_dir/git"

shim_out=$("$shim_dir/git" shim-arg 2>&1)
if ! echo "$shim_out" | grep -q "C3_KERNEL_TEST_FINGERPRINT_alpha"; then
  echo "$shim_out" >&2
  c2_fail "shim invocation did not produce the probe fingerprint"
fi
if ! echo "$shim_out" | grep -q "argv\[1\]=shim-arg"; then
  echo "$shim_out" >&2
  c2_fail "shim invocation did not forward argv"
fi
c2_ok "shim invocation reached the probe with argv forwarding"

echo "PASS: t_c3_launcher_linux_exec"
