import std/[os, osproc, sequtils, strtabs, strutils]

import repro_dev_env_artifacts
import repro_provider_runtime

type
  DevEnvPrintFormat* = enum
    depPosix
    depFish
    depPowerShell
    depJson

proc parseDevEnvPrintFormat*(value: string): DevEnvPrintFormat =
  case value.normalize()
  of "posix", "sh", "bash", "zsh":
    depPosix
  of "fish":
    depFish
  of "powershell", "pwsh", "ps1":
    depPowerShell
  of "json":
    depJson
  else:
    raise newException(ValueError,
      "unsupported --print-env format: " & value)

proc validEnvName(name: string): bool =
  if name.len == 0:
    return false
  if not (name[0] in {'A'..'Z', 'a'..'z', '_'}):
    return false
  for ch in name:
    if not (ch in {'A'..'Z', 'a'..'z', '0'..'9', '_'}):
      return false
  true

proc requireEnvName(name: string) =
  if not validEnvName(name):
    raise newException(ValueError,
      "dev-env artifact contains invalid environment variable name: " & name)

proc posixQuote(value: string): string =
  result = "'"
  for ch in value:
    if ch == '\'':
      result.add("'\\''")
    else:
      result.add(ch)
  result.add("'")

proc fishQuote(value: string): string =
  result = "'"
  for ch in value:
    case ch
    of '\'':
      result.add("\\'")
    of '\\':
      result.add("\\\\")
    else:
      result.add(ch)
  result.add("'")

proc powerShellQuote(value: string): string =
  "'" & value.replace("'", "''") & "'"

proc metadataOps(artifact: DevEnvArtifact; artifactPath = ""): seq[DevEnvShellOp] =
  if artifactPath.len > 0:
    result.add(DevEnvShellOp(kind: deskSetEnv,
      name: "REPRO_DEV_ENV_ARTIFACT",
      value: artifactPath))
  result.add(DevEnvShellOp(kind: deskSetEnv,
    name: "REPRO_DEV_ENV_PROJECT_ROOT",
    value: artifact.projectRoot))
  result.add(DevEnvShellOp(kind: deskSetEnv,
    name: "REPRO_DEV_ENV_SELECTED_ACTIVITIES",
    value: artifact.selectedActivities.join(",")))
  result.add(DevEnvShellOp(kind: deskSetEnv,
    name: "REPRO_DEV_ENV_TASKS",
    value: artifact.tasks.mapIt(it.name).join(",")))
  result.add(DevEnvShellOp(kind: deskSetEnv,
    name: "REPRO_DEV_ENV_SERVICES",
    value: artifact.services.mapIt(it.name).join(",")))

proc activationOps(artifact: DevEnvArtifact; artifactPath = ""):
    seq[DevEnvShellOp] =
  result = artifact.shellOps
  result.add(metadataOps(artifact, artifactPath))

proc renderPosix*(ops: openArray[DevEnvShellOp]): string =
  result = "# Generated by repro dev-env. Do not edit.\n"
  for op in ops:
    requireEnvName(op.name)
    let sep = if op.separator.len > 0: op.separator else: $PathSep
    case op.kind
    of deskSetEnv, deskSetPathList:
      result.add("export " & op.name & "=" & posixQuote(op.value) & "\n")
    of deskUnsetEnv:
      result.add("unset " & op.name & "\n")
    of deskPrependPath:
      result.add("if [ -n \"${" & op.name & ":-}\" ]; then\n")
      result.add("  export " & op.name & "=" & posixQuote(op.value) &
        posixQuote(sep) & "\"$" & op.name & "\"\n")
      result.add("else\n")
      result.add("  export " & op.name & "=" & posixQuote(op.value) & "\n")
      result.add("fi\n")
    of deskAppendPath:
      result.add("if [ -n \"${" & op.name & ":-}\" ]; then\n")
      result.add("  export " & op.name & "=\"$" & op.name & "\"" &
        posixQuote(sep) & posixQuote(op.value) & "\n")
      result.add("else\n")
      result.add("  export " & op.name & "=" & posixQuote(op.value) & "\n")
      result.add("fi\n")
    of deskSetWorkingDirectory:
      result.add("cd " & posixQuote(op.value) & "\n")

proc renderFish*(ops: openArray[DevEnvShellOp]): string =
  result = "# Generated by repro dev-env. Do not edit.\n"
  for op in ops:
    requireEnvName(op.name)
    case op.kind
    of deskSetEnv, deskSetPathList:
      result.add("set -gx " & op.name & " " & fishQuote(op.value) & "\n")
    of deskUnsetEnv:
      result.add("set -e " & op.name & "\n")
    of deskPrependPath:
      result.add("if set -q " & op.name & "\n")
      result.add("  set -gx " & op.name & " " & fishQuote(op.value) &
        " $" & op.name & "\n")
      result.add("else\n")
      result.add("  set -gx " & op.name & " " & fishQuote(op.value) & "\n")
      result.add("end\n")
    of deskAppendPath:
      result.add("if set -q " & op.name & "\n")
      result.add("  set -gx " & op.name & " $" & op.name & " " &
        fishQuote(op.value) & "\n")
      result.add("else\n")
      result.add("  set -gx " & op.name & " " & fishQuote(op.value) & "\n")
      result.add("end\n")
    of deskSetWorkingDirectory:
      result.add("cd " & fishQuote(op.value) & "\n")

proc renderPowerShell*(ops: openArray[DevEnvShellOp]): string =
  result = "# Generated by repro dev-env. Do not edit.\n"
  for op in ops:
    requireEnvName(op.name)
    let sep = if op.separator.len > 0: op.separator else: $PathSep
    case op.kind
    of deskSetEnv, deskSetPathList:
      result.add("$env:" & op.name & " = " & powerShellQuote(op.value) & "\n")
    of deskUnsetEnv:
      result.add("Remove-Item Env:" & op.name &
        " -ErrorAction SilentlyContinue\n")
    of deskPrependPath:
      result.add("if ($env:" & op.name & ") {\n")
      result.add("  $env:" & op.name & " = " & powerShellQuote(op.value) &
        " + " & powerShellQuote(sep) & " + $env:" & op.name & "\n")
      result.add("} else {\n")
      result.add("  $env:" & op.name & " = " & powerShellQuote(op.value) & "\n")
      result.add("}\n")
    of deskAppendPath:
      result.add("if ($env:" & op.name & ") {\n")
      result.add("  $env:" & op.name & " = $env:" & op.name & " + " &
        powerShellQuote(sep) & " + " & powerShellQuote(op.value) & "\n")
      result.add("} else {\n")
      result.add("  $env:" & op.name & " = " & powerShellQuote(op.value) & "\n")
      result.add("}\n")
    of deskSetWorkingDirectory:
      result.add("Set-Location -LiteralPath " & powerShellQuote(op.value) & "\n")

proc renderDevEnvShellOps*(ops: openArray[DevEnvShellOp];
                           format: DevEnvPrintFormat): string =
  case format
  of depPosix:
    renderPosix(ops)
  of depFish:
    renderFish(ops)
  of depPowerShell:
    renderPowerShell(ops)
  of depJson:
    raise newException(ValueError,
      "json rendering requires the full dev-env artifact")

proc renderDevEnvArtifact*(artifact: DevEnvArtifact; artifactPath = "";
                           format: DevEnvPrintFormat): string =
  case format
  of depJson:
    toJsonInspection(artifact) & "\n"
  else:
    renderDevEnvShellOps(activationOps(artifact, artifactPath), format)

proc baseEnvironment(): StringTableRef =
  result = newStringTable(modeCaseSensitive)
  for key, value in envPairs():
    result[key] = value

proc applyOp(env: StringTableRef; op: DevEnvShellOp;
             workingDirectory: var string) =
  requireEnvName(op.name)
  let sep = if op.separator.len > 0: op.separator else: $PathSep
  case op.kind
  of deskSetEnv, deskSetPathList:
    env[op.name] = op.value
  of deskUnsetEnv:
    env.del(op.name)
  of deskPrependPath:
    let current = env.getOrDefault(op.name)
    env[op.name] =
      if current.len > 0: op.value & sep & current else: op.value
  of deskAppendPath:
    let current = env.getOrDefault(op.name)
    env[op.name] =
      if current.len > 0: current & sep & op.value else: op.value
  of deskSetWorkingDirectory:
    if op.value.len > 0:
      workingDirectory = op.value
      env["PWD"] = op.value

proc activatedEnvironment*(artifact: DevEnvArtifact; artifactPath = "";
                           defaultWorkingDirectory = ""):
    tuple[env: StringTableRef; workingDirectory: string] =
  result.env = baseEnvironment()
  result.workingDirectory =
    if defaultWorkingDirectory.len > 0:
      defaultWorkingDirectory
    else:
      artifact.projectRoot
  for op in activationOps(artifact, artifactPath):
    result.env.applyOp(op, result.workingDirectory)

proc containsPathSeparator(value: string): bool =
  value.contains(DirSep) or value.contains(AltSep)

proc executableCandidate(dir, name, workingDirectory: string): string =
  let base =
    if dir.isAbsolute or workingDirectory.len == 0:
      dir
    else:
      workingDirectory / dir
  let direct = base / name
  if fileExists(direct):
    return direct
  when defined(windows):
    if splitFile(name).ext.len == 0:
      let withExe = base / addFileExt(name, ExeExt)
      if fileExists(withExe):
        return withExe
  ""

proc resolveFromActivatedPath(command: string; env: StringTableRef;
                              workingDirectory: string): string =
  if command.len == 0 or command.containsPathSeparator():
    return command
  let pathValue = env.getOrDefault("PATH")
  for dir in pathValue.split(PathSep):
    if dir.len == 0:
      continue
    let candidate = executableCandidate(dir, command, workingDirectory)
    if candidate.len > 0:
      return candidate
  command

proc runActivatedCommand*(artifact: DevEnvArtifact; artifactPath: string;
                          command: openArray[string];
                          defaultWorkingDirectory = ""): int =
  if command.len == 0:
    raise newException(ValueError, "dev-env command is empty")
  let activation = activatedEnvironment(artifact, artifactPath,
    defaultWorkingDirectory)
  var childArgs: seq[string] = @[]
  for i in 1 ..< command.len:
    childArgs.add(command[i])
  let executable = resolveFromActivatedPath(command[0], activation.env,
    activation.workingDirectory)
  var process = startProcess(executable,
    args = childArgs,
    env = activation.env,
    workingDir = activation.workingDirectory,
    options = {poUsePath, poParentStreams})
  result = process.waitForExit()
  process.close()

proc spawnActivatedShell*(artifact: DevEnvArtifact; artifactPath,
                          shellPath: string;
                          defaultWorkingDirectory = ""): int =
  if shellPath.len == 0:
    raise newException(ValueError, "dev-env shell path is empty")
  let activation = activatedEnvironment(artifact, artifactPath,
    defaultWorkingDirectory)
  var process = startProcess(shellPath,
    env = activation.env,
    workingDir = activation.workingDirectory,
    options = {poUsePath, poParentStreams})
  result = process.waitForExit()
  process.close()
