## Source-from-tarball make recipe — M9.N Batch E compiler-chain
## slice.
##
## GNU make is the canonical build-system driver every from-source
## recipe under ``recipes/packages/source/`` that consumes the
## ``from-source-autotools`` / ``from-source-make`` / ``from-source-
## custom`` conventions transitively invokes at compile + install
## time. The Batch E (gcc + binutils + make) slice sits BELOW Batch D
## (cmake + autoconf + automake + libtool + pkgconf) in the bootstrap
## layering: every Batch D autotools recipe drives ``./configure``
## which generates ``Makefile``s which only make can drive. R5 musl-
## tcc is the long-term clean root for the bootstrap chain; Batch E
## ships the recipes against the existing upstream tarballs as
## declarative shape so the M9.K convention layer can lower them when
## the recipe graph asks for the host make.
##
## ## Convention chosen — ``from-source-autotools``
##
## make is itself an autotools-driven project: the upstream release
## tarball ships a ``./configure`` script generated by autoconf +
## ``Makefile.in`` files generated by automake at the source root, so
## the canonical ``./configure && make && make install`` cycle
## suffices. The ``from-source-autotools`` convention (M9.L.2) claims
## the recipe via the populated ``configureFlags:`` channel.
##
## (Curiosity: bootstrapping make-from-source with the ``from-source-
## autotools`` convention requires a pre-existing ``make`` binary on
## the host to drive the ``make && make install`` steps. The upstream
## tarball ships a ``./build.sh`` fallback that builds make using just
## a shell + cc — used by the R5 musl-tcc bootstrap root. v1's
## recipe ASSUMES a host ``make`` is available; a future R5 pass will
## either (a) carve out a ``./build.sh`` path under the from-source-
## custom convention, or (b) seed the host with a vendored makefile-
## free static build of make.)
##
## ## Why make matters for the v1 desktop story
##
## make is the build-system driver every autotools / kbuild / hand-
## rolled-Makefile recipe in ``recipes/packages/source/`` depends on.
## Every gcc / binutils invocation ultimately runs under a ``make``
## driver. Every kernel build runs ``make ARCH=x86_64 ...``. Every
## autotools recipe runs ``./configure && make && make install``.
## Bootstrapping make from source closes the host build-system-driver
## floor the entire C / C++ ecosystem pins.
##
## ## sha256 strategy
##
## The fetch URL points at the upstream ftp.gnu.org release tarball
## ``make-4.4.1.tar.gz``. The sha256 was computed locally by
## downloading the tarball and running ``sha256sum`` over the bytes.
## nixpkgs's ``pkgs/development/tools/build-managers/gnumake/default.nix``
## consumes the same ftp.gnu.org tarball via fetchurl so the cross-
## check holds when both pin the same version.
##
## ## Version choice — 4.4.1 (per task brief)
##
## make releases are cut on ftp.gnu.org under tags of the form
## ``make-<X>.<Y>.<Z>``. 4.4.1 is the latest stable in the 4.4.x line
## as of the task brief. The 4.4 cut introduced the ``--shuffle``
## flag for build-order determinism testing + the grouped-targets
## ``&:`` syntax kbuild 5.x+ relies on; anything ``>=4.3`` covers the
## kernel-recipe pinning and every consumer's make floor.
##
## ## Why make is NOT vendored
##
## The ``make-4.4.1.tar.gz`` tarball weighs ~2.3 MB which is well
## below GitHub's 100-MB single-file ceiling, but the Batch D + E
## precedents all use live upstream URLs directly — no vendor/ copy.
## make follows the same precedent.
##
## ## Artifacts
##
## make exposes ONE load-bearing CLI binary on disk:
##
##   * ``make`` — ``$PREFIX/bin/make``, the canonical build-system
##                 driver that interprets ``Makefile`` recipes,
##                 builds the recipe-dependency graph, and shells
##                 out to the recipes' command lines.
##
## (The upstream install body also lays out a ``$PREFIX/bin/gmake``
## symlink to ``make`` on systems where ``make`` itself is BSD make
## or pmake; the recipe records only the canonical ``make`` binary.)
##
## ## Configurables
##
## v1 ships ONE configure flag per the task brief:
##
##   * ``--disable-nls`` — skip the gettext native-language support
##                          pass. NLS adds a build-time dep on
##                          libintl and is unused on a reproducible-
##                          build host (no per-locale message
##                          catalogs to consume).

import repro_project_dsl

# ---------------------------------------------------------------------------
# Package declaration
# ---------------------------------------------------------------------------

package makeSource:
  ## From-source make — M9.N Batch E compiler-chain slice.
  ##
  ## Tier-2b from-source-autotools convention consumer: the
  ## convention layer reads the ``fetch:`` block (registered via
  ## ``registeredFetchSpec``) and the ``configureFlags:`` block
  ## (registered via ``registeredBuildFlags`` on the ``"configure"``
  ## channel) and lowers them into fetch + configure + build + install
  ## BuildActions. Single executable artifact recipe.

  versions:
    ## Pinned upstream tag. ``sourceUrl`` records the canonical
    ## ftp.gnu.org release tarball URL; ``sourceRepository`` points
    ## at the canonical savannah.gnu.org mirror.
    "4.4.1":
      sourceRevision = "v4.4.1"
      sourceUrl = "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
      sourceRepository = "https://git.savannah.gnu.org/git/make.git"

  fetch:
    ## Live upstream URL — NOT vendored, per the Batch D + E
    ## precedent.
    ##
    ## sha256 computed locally over the upstream ftp.gnu.org tarball;
    ## nixpkgs consumes the same tarball via fetchurl so the cross-
    ## check holds when both pin the same version.
    url: "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
    sha256: "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"
    extractStrip: 1

  uses:
    ## gcc is the host C toolchain — make is C99.
    "gcc >=11"
    ## perl is invoked by make's ``configure`` script for a handful
    ## of code-generation passes under ``doc/``.
    "perl >=5.32"

  configureFlags:
    ## Modern-desktop baseline. ``--disable-nls`` skips the gettext
    ## native-language support pass (no per-locale message catalogs
    ## on a reproducible-build host).
    "--disable-nls"

  executable make:
    ## ``$PREFIX/bin/make`` — the canonical build-system driver. v1
    ## records the artifact only.
    discard
