## M66 Part D — Idempotence regression.
##
## Runs the harvester's emit pipeline twice against the same fixture
## bucket and asserts byte-identical output. Catches any leak of
## non-determinism (random key order, timestamps, OS-dependent
## newline conversion).

import std/[os, strutils, unittest]

import ../src/manifest_parser
import ../src/nim_emit
import repro_dsl_stdlib/packages_schema

const FixturesDir = currentSourcePath.parentDir / "fixtures"

proc readFixture(bucket, app: string): string =
  readFile(FixturesDir / bucket / "bucket" / (app & ".json"))

proc harvestOnce(bucket, app, bucketSpec: string): string =
  let raw = readFixture(bucket, app)
  let p = parseScoopManifest(app, raw)
  check p.ok
  emitCatalogFile(app, bucketSpec, @[p.entry])

suite "M66 — emit pipeline idempotence":

  test "byte-identical output across two runs (simple fixture)":
    let a = harvestOnce("bucket-simple", "hello", "scoopinstaller/main")
    let b = harvestOnce("bucket-simple", "hello", "scoopinstaller/main")
    check a == b
    check a.len > 0

  test "byte-identical output across two runs (multi-arch fixture)":
    let a = harvestOnce("bucket-multiarch-extract", "multitool",
      "scoopinstaller/main")
    let b = harvestOnce("bucket-multiarch-extract", "multitool",
      "scoopinstaller/main")
    check a == b

  test "byte-identical output across two runs (installer fixture)":
    let a = harvestOnce("bucket-installer", "myinstaller",
      "scoopinstaller/main")
    let b = harvestOnce("bucket-installer", "myinstaller",
      "scoopinstaller/main")
    check a == b

  test "env-key order is deterministic regardless of input ordering":
    # We feed two manifests whose env_set keys are presented in
    # opposite orders and assert the emitted source carries them in
    # the SAME (sorted) order.
    let rawA = """{
      "version": "1.0.0",
      "url": "https://example.test/x.zip",
      "hash": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
      "bin": "x.exe",
      "env_set": {"AAA": "a", "BBB": "b", "CCC": "c"}
    }"""
    let rawB = """{
      "version": "1.0.0",
      "url": "https://example.test/x.zip",
      "hash": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
      "bin": "x.exe",
      "env_set": {"CCC": "c", "AAA": "a", "BBB": "b"}
    }"""
    let pa = parseScoopManifest("x", rawA)
    let pb = parseScoopManifest("x", rawB)
    check pa.ok and pb.ok
    let srcA = emitCatalogFile("x", "scoop/x", @[pa.entry])
    let srcB = emitCatalogFile("x", "scoop/x", @[pb.entry])
    check srcA == srcB
    let aaaIdx = srcA.find("AAA")
    let bbbIdx = srcA.find("BBB")
    let cccIdx = srcA.find("CCC")
    check aaaIdx > 0
    check bbbIdx > aaaIdx
    check cccIdx > bbbIdx

  test "emitted source carries the bucket header + Versions line":
    let src = harvestOnce("bucket-simple", "hello", "scoopinstaller/main")
    check "Auto-generated by tools/catalog-harvester" in src
    check "Harvested from bucket: scoopinstaller/main" in src
    check "Versions (newest-first): 1.0.0" in src
    check "helloCatalog*" in src
    check "VersionedProvisioning(" in src
