## `repro hooks ensure --vcs` restores a dispatcher that **prek** displaced,
## and the hooks keep running — through real Git and real prek.
##
## prek (the Rust re-implementation of pre-commit) is what the Nix dev shells
## in this workspace install hooks with: `git-hooks.nix`'s installation script
## runs `prek uninstall -t <every hook type>` and then `prek install -t
## <configured stages>` whenever its generated config changes. `prek install`
## over a Reprobuild dispatcher MOVES the dispatcher to `<hook>.legacy` and
## writes its own shim in the dispatcher's slot ("migration mode"). From then
## on the managed hook — for `pre-push`, the publication gate — runs only if
## something still runs that `.legacy` file.
##
## ## What is asserted
##
##   1. **Displaced, the gate keeps running and commits keep working.** In the
##      exact layout `prek install` leaves (slot = prek shim, `.legacy` =
##      dispatcher, `.repro-local` = the previously chained prek shim), a real
##      `git commit` succeeds, prek's checks run ONCE (not again through the
##      chained copy), and the dispatcher does not delete itself. Before this
##      fix the chained copy aborted with "prek's Git shim is installed in
##      migration mode" (prek treats an EMPTY `PREK_RUNNING_LEGACY` as set),
##      and the dispatcher, running as `.legacy`, deleted itself.
##   2. **`ensure` restores the layout.** It reports the repair (not "already
##      current"), the dispatcher is back in the slot, `.legacy` is gone, prek's
##      shim is chained as `.repro-local`, and a commit runs prek's checks
##      through the dispatcher.
##   3. **A regenerated prek shim is not a conflict.** prek installed from a
##      different path (what a toolchain bump does under Nix) writes a shim that
##      differs from the chained copy only in that path; `ensure` takes the new
##      one instead of refusing.
##   4. **A genuinely different hook still refuses — without switching the gate
##      off.** A hand-written `.repro-local` competing with the prek shim is
##      refused as before, and the displaced `.legacy` dispatcher is left in
##      place, because it is the only thing still running the managed hook.
##
## ## Test doubles
##
## None. Git and prek are the real tools, run against a real repository in a
## scratch directory; the "hand-written" hook in (4) is a real
## user hook, which is the thing that case is about.
##
## Skips (with the reason printed) only when `git` or `prek` is not on PATH;
## the reprobuild dev shell provides both.

import std/[os, osproc, strutils, tempfiles, unittest]

import repro_test_support

proc q(value: string): string = quoteShell(value)

proc repoRoot(): string =
  currentSourcePath().parentDir.parentDir.parentDir

proc reproBinary(): string =
  requireBinary(repoRoot() / "build" / "bin" / addFileExt("repro", ExeExt),
    "reprobuild.apps.repro")

type Fixture = object
  scratch, repo, hooks, prek, reproBin, envPrefix, ranFile: string

proc run(f: Fixture; command: string): tuple[code: int; output: string] =
  let res = execCmdEx(f.envPrefix & " " & command, workingDir = f.repo)
  (code: res.exitCode, output: res.output)

proc mustRun(f: Fixture; command: string): string =
  let res = f.run(command)
  if res.code != 0:
    checkpoint("command failed: " & command & "\nexit=" & $res.code & "\n" &
      res.output)
    raise newException(AssertionDefect, "command failed: " & command)
  res.output

proc slot(f: Fixture; name: string): string = f.hooks / name

proc isDispatcher(path: string): bool =
  fileExists(path) and readFile(path).contains("reprobuild hook dispatcher")

proc isPrekShim(path: string): bool =
  fileExists(path) and readFile(path).contains("File generated by prek")

proc ranCount(f: Fixture): int =
  if not fileExists(f.ranFile): 0
  else: readFile(f.ranFile).countLines() - 1

proc prekInstall(f: Fixture; prek = "") =
  ## What git-hooks.nix's installation script does on every run.
  let tool = if prek.len > 0: prek else: f.prek
  for hook in ["pre-commit", "pre-push", "post-commit", "post-merge",
      "post-checkout", "commit-msg"]:
    discard f.run(q(tool) & " uninstall -t " & hook)
  discard f.mustRun(q(tool) & " install -c .pre-commit-config.yaml " &
    "-t pre-commit")

proc ensure(f: Fixture): tuple[code: int; output: string] =
  f.run(q(f.reproBin) & " hooks ensure --vcs " & q(f.repo))

proc commit(f: Fixture; message: string): tuple[code: int; output: string] =
  writeFile(f.repo / "change.txt", message & "\n")
  discard f.mustRun("git add change.txt")
  f.run("git commit -m " & q(message))

proc setup(): Fixture =
  result.scratch = createTempDir("repro-prek-displaced-", "")
  result.repo = result.scratch / "repo"
  result.prek = findExe("prek")
  result.reproBin = reproBinary()
  result.ranFile = result.scratch / "prek-ran.txt"
  createDir(result.scratch / "prek-home")
  # REPROBUILD_REPRO pins the managed bodies to the binary under test; the
  # prek home keeps prek's cache out of the developer's.
  result.envPrefix = "env REPROBUILD_REPRO=" & q(result.reproBin) &
    " PREK_HOME=" & q(result.scratch / "prek-home") &
    " PATH=" & q(result.reproBin.parentDir & PathSep & getEnv("PATH"))
  createDir(result.repo)
  discard result.mustRun("git init -q -b main .")
  discard result.mustRun("git config user.email tester@example.invalid")
  discard result.mustRun("git config user.name Tester")
  writeFile(result.repo / ".pre-commit-config.yaml",
    "repos:\n" &
    "- repo: local\n" &
    "  hooks:\n" &
    "  - id: record\n" &
    "    name: record\n" &
    "    entry: sh -c 'echo ran >> " & result.ranFile & "'\n" &
    "    language: system\n" &
    "    pass_filenames: false\n" &
    "    always_run: true\n")
  discard result.mustRun("git add .pre-commit-config.yaml")
  discard result.mustRun("git commit -q --no-verify -m fixture")
  result.hooks = result.mustRun(
    "git rev-parse --path-format=absolute --git-path hooks").strip()

suite "hooks ensure restores a dispatcher displaced by prek":

  test "prek displacement: gate keeps running, ensure restores the layout":
    if findExe("git").len == 0 or findExe("prek").len == 0:
      skip("needs git and prek on PATH (the reprobuild dev shell has both)")
    else:
      var f = setup()
      defer: removeDir(f.scratch)

      # The steady state a dev shell produces: prek installed first, then
      # `ensure` chains it behind the dispatcher.
      f.prekInstall()
      check f.ensure().code == 0
      check isDispatcher(f.slot("pre-commit"))
      check isPrekShim(f.slot("pre-commit.repro-local"))
      check not fileExists(f.slot("pre-commit.legacy"))
      let c0 = f.commit("steady")
      checkpoint(c0.output)
      check c0.code == 0
      check f.ranCount() == 1

      # ---- (1) re-enter the dev shell: prek displaces the dispatcher ------
      f.prekInstall()
      check isPrekShim(f.slot("pre-commit"))
      check isDispatcher(f.slot("pre-commit.legacy"))
      check isPrekShim(f.slot("pre-commit.repro-local"))
      let c1 = f.commit("displaced")
      checkpoint(c1.output)
      check c1.code == 0
      check not c1.output.contains("migration mode")
      check c1.output.contains("running as pre-commit.legacy")
      # prek ran its checks once, as the slot; the chained copy was skipped.
      check f.ranCount() == 2
      # The post-commit hook (which prek does not touch) re-asserted the
      # layout; either way the dispatcher must not have deleted itself.
      check isDispatcher(f.slot("pre-commit")) or
        isDispatcher(f.slot("pre-commit.legacy"))

      # ---- (2) `ensure` after a displacement ------------------------------
      f.prekInstall()
      check isDispatcher(f.slot("pre-commit.legacy"))
      let e2 = f.ensure()
      checkpoint(e2.output)
      check e2.code == 0
      check not e2.output.contains("already current")
      check isDispatcher(f.slot("pre-commit"))
      check not fileExists(f.slot("pre-commit.legacy"))
      check isPrekShim(f.slot("pre-commit.repro-local"))
      check fileExists(f.slot("pre-commit.repro-managed"))
      let c2 = f.commit("restored")
      checkpoint(c2.output)
      check c2.code == 0
      check f.ranCount() == 3
      check not c2.output.contains("running as pre-commit.legacy")

      # ---- (3) prek from a different path: a regenerated shim -------------
      let otherPrek = f.scratch / "other-prek" / "prek"
      createDir(otherPrek.parentDir)
      copyFile(f.prek, otherPrek)
      setFilePermissions(otherPrek, getFilePermissions(f.prek))
      f.prekInstall(otherPrek)
      check readFile(f.slot("pre-commit")).contains(otherPrek)
      let e3 = f.ensure()
      checkpoint(e3.output)
      check e3.code == 0
      check isDispatcher(f.slot("pre-commit"))
      check readFile(f.slot("pre-commit.repro-local")).contains(otherPrek)
      check f.commit("regenerated").code == 0
      check f.ranCount() == 4

      # ---- (4) a genuinely different hook: refuse, keep the gate ----------
      writeFile(f.slot("pre-commit.repro-local"),
        "#!/bin/sh\n# my own checks\nexit 0\n")
      f.prekInstall()
      check isDispatcher(f.slot("pre-commit.legacy"))
      let e5 = f.ensure()
      checkpoint(e5.output)
      check e5.code != 0
      check e5.output.contains("already holds a different preserved hook")
      # The refusal did not take the displaced dispatcher with it.
      check isDispatcher(f.slot("pre-commit.legacy"))
