// M9.R.18.4 -- InstallerState implementation. The renderSystemNim()
// method synthesises the exact text PRD Sec 3.3 documents from the
// wizard's gathered choices; the Summary screen binds a TextArea to
// the return value so the user sees what gets written verbatim.

#include "installer_state.h"

#include <QtCore/QTextStream>

InstallerState::InstallerState(QObject *parent) : QObject(parent) {}

void InstallerState::setHostname(const QString &v) {
    if (m_hostname == v) return;
    m_hostname = v;
    emit hostnameChanged();
}

void InstallerState::setLocale(const QString &v) {
    if (m_locale == v) return;
    m_locale = v;
    emit localeChanged();
}

void InstallerState::setTimezone(const QString &v) {
    if (m_timezone == v) return;
    m_timezone = v;
    emit timezoneChanged();
}

void InstallerState::setKeymap(const QString &v) {
    if (m_keymap == v) return;
    m_keymap = v;
    emit keymapChanged();
}

void InstallerState::setUsername(const QString &v) {
    if (m_username == v) return;
    m_username = v;
    emit usernameChanged();
}

void InstallerState::setFullName(const QString &v) {
    if (m_fullName == v) return;
    m_fullName = v;
    emit fullNameChanged();
}

void InstallerState::setPassword(const QString &v) {
    if (m_password == v) return;
    m_password = v;
    emit passwordChanged();
}

void InstallerState::setIsAdmin(bool v) {
    if (m_isAdmin == v) return;
    m_isAdmin = v;
    emit isAdminChanged();
}

void InstallerState::setDesktopKind(const QString &v) {
    if (m_desktopKind == v) return;
    m_desktopKind = v;
    emit desktopKindChanged();
}

void InstallerState::setActiveActivities(const QStringList &v) {
    if (m_activeActivities == v) return;
    m_activeActivities = v;
    emit activeActivitiesChanged();
}

void InstallerState::setActivitiesTomlPath(const QString &v) {
    if (m_activitiesTomlPath == v) return;
    m_activitiesTomlPath = v;
    emit activitiesTomlPathChanged();
}

void InstallerState::setDryRun(bool v) {
    if (m_dryRun == v) return;
    m_dryRun = v;
    emit dryRunChanged();
}

void InstallerState::toggleActivity(const QString &name) {
    if (m_activeActivities.contains(name)) {
        m_activeActivities.removeAll(name);
    } else {
        m_activeActivities.append(name);
        m_activeActivities.sort();
    }
    emit activeActivitiesChanged();
}

bool InstallerState::hasActivity(const QString &name) const {
    return m_activeActivities.contains(name);
}

// Maps PRD Sec 3.1 desktop choice to the activity-shape `dkPlasma` /
// `dkGnome` / `dkSway` / `dkHyprland` variant kinds the
// ReproOS-Configuration-Architecture document defines.
static QString desktopKindToVariant(const QString &kind) {
    if (kind == "plasma") return "dkPlasma";
    if (kind == "gnome") return "dkGnome";
    if (kind == "sway") return "dkSway";
    if (kind == "hyprland") return "dkHyprland";
    return "dkPlasma";
}

QString InstallerState::renderSystemNim() const {
    // Render the user-facing system.nim per PRD Sec 3.3. The format is
    // pinned by ReproOS-Configuration-Architecture; the
    // `import repro_profile` + `system "<name>":` header is canonical.
    QString out;
    QTextStream s(&out);
    s << "# /etc/repro/system.nim --- generated by the ReproOS installer\n";
    s << "import repro_profile\n\n";
    s << "system \"" << m_hostname << "\":\n";
    s << "  imports:\n";
    s << "    \"./hardware.nim\"\n";
    for (const QString &act : m_activeActivities) {
        s << "    \"modules/activities/" << act << ".nim\"\n";
    }
    s << "    \"modules/de/" << m_desktopKind << ".nim\"\n";
    s << "    \"modules/networking/networkmanager.nim\"\n\n";
    s << "  config:\n";
    s << "    hostname: string = \"" << m_hostname << "\"\n";
    s << "    timezone: string = \"" << m_timezone << "\"\n";
    s << "    locale: string = \"" << m_locale << "\"\n";
    s << "    keymap: string = \"" << m_keymap << "\"\n";
    s << "    activeAtBoot: DesktopKind = " << desktopKindToVariant(m_desktopKind) << "\n";
    s << "    defaultUser: string = \"" << m_username << "\"\n\n";
    s << "  users:\n";
    s << "    \"" << m_username << "\":\n";
    s << "      fullName: \"" << m_fullName << "\"\n";
    s << "      groups: @[";
    s << "\"audio\", \"video\", \"networkmanager\"";
    if (m_isAdmin) s << ", \"wheel\"";
    s << "]\n";
    s << "      homeIntent: import \"./home.nim\"\n";
    return out;
}
