## M76 — per-shell hook installation script templates.
##
## ``repro shell hook <shell>`` emits the script the user sources from
## their rc file (``~/.bashrc``, ``~/.config/fish/config.fish``,
## ``$PROFILE``, ...). The emitted script:
##
## 1. Defines a ``__repro_shell_hook`` function that walks up from
##    ``$PWD`` looking for ``reprobuild.nim`` / ``repro.nim`` /
##    ``.repro/dev-env.lock``. The walk is bounded at ``$HOME`` and
##    at the filesystem root so the per-prompt cost stays O(depth).
## 2. If the resulting ``candidate_root`` differs from the currently-
##    active ``$__REPRO_PROJECT_ROOT`` and the latter is non-empty,
##    the hook first evaluates ``repro dev-env deactivate
##    "$__REPRO_ACTIVE_MANIFEST"`` and unsets both ``__REPRO_*`` vars
##    so the env returns to its pre-activation state.
## 3. If ``candidate_root`` is non-empty AND differs from
##    ``$__REPRO_PROJECT_ROOT``, the hook evaluates ``repro dev-env
##    export <shell> --project-root "$candidate_root"
##    --pre-activation-env <auto-generated tmp path>``. The pre-
##    activation env file is written by the hook itself BEFORE calling
##    ``export`` so the rollback manifest captures the SHELL's env.
## 4. The hook installs itself into the per-shell prompt machinery:
##
##    * bash: ``PROMPT_COMMAND`` (the canonical pre-prompt hook).
##    * zsh: ``chpwd_functions`` array (zsh-idiomatic cd hook). We
##      ALSO wrap into ``precmd_functions`` so the FIRST prompt of
##      a shell (which is NOT preceded by a cd) still triggers
##      activation against the launching cwd.
##    * fish: a ``--on-variable PWD`` handler PLUS a one-shot fire
##      from ``config.fish`` so the launching cwd activates.
##    * pwsh: the ``prompt`` function is wrapped, preserving the
##      user's existing prompt definition.
##    * nushell: ``$env.config.hooks.env_change.PWD`` (chpwd) +
##      ``pre_prompt`` (precmd-equivalent).
##
## M76 short-circuits via ``$__REPRO_PROJECT_ROOT`` equality only;
## the cache-key fast path (``$__REPRO_APPLIED``) arrives in M77.
## The current M76 check still prevents the "every prompt re-spawns
## repro" pathology — the second prompt after a cd into a project sees
## ``__REPRO_PROJECT_ROOT == candidate_root`` and returns immediately
## without calling ``repro``. That assertion is the load-bearing
## acceptance gate in ``t_e2e_shell_hook_cd_activate_deactivate.nim``.
##
## Quoting: the templates embed the ``repro`` binary path via per-
## shell quoting compatible with each shell's literal-string syntax.
## When ``reproBin`` is the empty string the hook falls back to the
## bare ``repro`` command (PATH lookup); the test surface uses this
## path with a shim under PATH to count subprocess spawns.

import std/strutils

# ---------------------------------------------------------------------
# Per-shell quoting helpers (kept local — not re-using the M74 ones
# because the hook templates don't need to round-trip arbitrary user
# values; the only string we ever embed here is a binary path).
# ---------------------------------------------------------------------

proc bashSingleQuote(value: string): string =
  result = "'"
  for ch in value:
    if ch == '\'':
      result.add("'\\''")
    else:
      result.add(ch)
  result.add("'")

proc fishSingleQuote(value: string): string =
  result = "'"
  for ch in value:
    case ch
    of '\'': result.add("\\'")
    of '\\': result.add("\\\\")
    else: result.add(ch)
  result.add("'")

proc pwshSingleQuote(value: string): string =
  "'" & value.replace("'", "''") & "'"

proc nuSingleQuote(value: string): string =
  if not value.contains('\''):
    return "'" & value & "'"
  result = "\""
  for ch in value:
    case ch
    of '\\': result.add("\\\\")
    of '"': result.add("\\\"")
    else: result.add(ch)
  result.add("\"")

# ---------------------------------------------------------------------
# bash / zsh shared body
# ---------------------------------------------------------------------

proc bashHookBody(reproExpr: string): string =
  ## ``reproExpr`` is a shell expression that evaluates to the repro
  ## binary path/name. The caller passes either a quoted absolute path
  ## or the bare literal ``repro`` (PATH lookup).
  result = ""
  result.add("__repro_shell_hook() {\n")
  result.add("  local __repro_candidate=\"\" __repro_walk=\"$PWD\"\n")
  result.add("  while [ -n \"$__repro_walk\" ] && \\\n")
  result.add("        [ \"$__repro_walk\" != \"/\" ]; do\n")
  result.add("    if [ -e \"$__repro_walk/reprobuild.nim\" ] || \\\n")
  result.add("       [ -e \"$__repro_walk/repro.nim\" ] || \\\n")
  result.add("       [ -e \"$__repro_walk/.repro/dev-env.lock\" ]; then\n")
  result.add("      __repro_candidate=\"$__repro_walk\"\n")
  result.add("      break\n")
  result.add("    fi\n")
  # Bounded walk: stop at $HOME so we never traverse the user's entire
  # home tree on every prompt. The filesystem-root stop above handles
  # the case where the user starts a shell outside their home.
  result.add("    if [ \"$__repro_walk\" = \"$HOME\" ]; then\n")
  result.add("      break\n")
  result.add("    fi\n")
  result.add("    __repro_walk=$(dirname -- \"$__repro_walk\")\n")
  result.add("  done\n")
  # If a project was previously active and we are now either out of
  # any project, or into a different one, deactivate first.
  result.add("  if [ -n \"${__REPRO_PROJECT_ROOT:-}\" ] && \\\n")
  result.add("     [ \"${__REPRO_PROJECT_ROOT}\" != \"$__repro_candidate\" ]; then\n")
  result.add("    if [ -n \"${__REPRO_ACTIVE_MANIFEST:-}\" ]; then\n")
  # Capture stderr so a malformed manifest doesn't silently fail.
  # The user sees deactivation diagnostics on their shell stderr.
  result.add("      local __repro_deact\n")
  result.add("      __repro_deact=$(" & reproExpr &
    " dev-env deactivate \"$__REPRO_ACTIVE_MANIFEST\" --shell=bash)\n")
  result.add("      if [ -n \"$__repro_deact\" ]; then\n")
  result.add("        eval \"$__repro_deact\"\n")
  result.add("      fi\n")
  result.add("    fi\n")
  result.add("    unset __REPRO_PROJECT_ROOT\n")
  result.add("    unset __REPRO_APPLIED\n")
  result.add("    unset __REPRO_ACTIVE_MANIFEST\n")
  result.add("  fi\n")
  # Activate (or re-activate) only when the candidate is non-empty AND
  # different from the currently-active project root. This is the
  # M76 short-circuit: when the user runs additional prompts inside
  # an already-active project, ``__REPRO_PROJECT_ROOT == candidate``
  # so we return without spawning ``repro``.
  result.add("  if [ -n \"$__repro_candidate\" ] && \\\n")
  result.add("     [ \"$__repro_candidate\" != \"${__REPRO_PROJECT_ROOT:-}\" ]; then\n")
  result.add("    local __repro_pre_env\n")
  result.add("    __repro_pre_env=$(mktemp -t repro-pre-env.XXXXXX 2>/dev/null || " &
    "mktemp 2>/dev/null || echo \"${TMPDIR:-/tmp}/repro-pre-env.$$\")\n")
  # Dump the SHELL env using `env -0` (NUL-terminated NAME=VALUE
  # records — the format M75's --pre-activation-env consumes).
  result.add("    env -0 > \"$__repro_pre_env\" 2>/dev/null || env > \"$__repro_pre_env\"\n")
  result.add("    local __repro_export\n")
  # Do NOT swallow stderr — diagnostics from the dev-env edge (parse
  # errors, missing tools, tamper detection downstream) should reach
  # the user's tty rather than disappear silently.
  result.add("    __repro_export=$(" & reproExpr &
    " dev-env export bash --project-root \"$__repro_candidate\" " &
    "--pre-activation-env \"$__repro_pre_env\")\n")
  result.add("    local __repro_rc=$?\n")
  result.add("    rm -f \"$__repro_pre_env\" 2>/dev/null\n")
  result.add("    if [ $__repro_rc -eq 0 ] && [ -n \"$__repro_export\" ]; then\n")
  result.add("      eval \"$__repro_export\"\n")
  result.add("      export __REPRO_PROJECT_ROOT=\"$__repro_candidate\"\n")
  result.add("    fi\n")
  result.add("  fi\n")
  result.add("}\n")

# ---------------------------------------------------------------------
# Per-shell renderers
# ---------------------------------------------------------------------

proc reproExprBash(reproBin: string): string =
  if reproBin.len == 0:
    "repro"
  else:
    bashSingleQuote(reproBin)

proc renderBashHook*(reproBin: string): string =
  ## bash hook: ``PROMPT_COMMAND`` chained with the user's existing
  ## value so we never clobber it.
  result = "# repro shell hook (bash) — installed via `eval \"$(repro shell hook bash)\"`\n"
  result.add(bashHookBody(reproExprBash(reproBin)))
  result.add("if [ -z \"${PROMPT_COMMAND:-}\" ]; then\n")
  result.add("  PROMPT_COMMAND=\"__repro_shell_hook\"\n")
  result.add("else\n")
  result.add("  case \";${PROMPT_COMMAND};\" in\n")
  result.add("    *\";__repro_shell_hook;\"*) : ;;\n")
  result.add("    *) PROMPT_COMMAND=\"__repro_shell_hook;${PROMPT_COMMAND}\" ;;\n")
  result.add("  esac\n")
  result.add("fi\n")

proc renderZshHook*(reproBin: string): string =
  ## zsh hook: register into ``chpwd_functions`` (canonical cd hook)
  ## AND ``precmd_functions`` so the initial prompt fires the activation
  ## against the launching cwd. The body is shared with bash (zsh
  ## evaluates bash-compatible Bourne syntax in the function body).
  result = "# repro shell hook (zsh) — installed via `eval \"$(repro shell hook zsh)\"`\n"
  result.add(bashHookBody(reproExprBash(reproBin)))
  result.add("typeset -ga chpwd_functions precmd_functions\n")
  result.add("if [[ -z \"${chpwd_functions[(r)__repro_shell_hook]:-}\" ]]; then\n")
  result.add("  chpwd_functions+=(__repro_shell_hook)\n")
  result.add("fi\n")
  result.add("if [[ -z \"${precmd_functions[(r)__repro_shell_hook]:-}\" ]]; then\n")
  result.add("  precmd_functions+=(__repro_shell_hook)\n")
  result.add("fi\n")

proc reproExprFish(reproBin: string): string =
  if reproBin.len == 0:
    "repro"
  else:
    fishSingleQuote(reproBin)

proc renderFishHook*(reproBin: string): string =
  ## fish hook: ``--on-variable PWD`` handler plus a one-shot
  ## invocation so the launching cwd activates. Fish has no PROMPT_COMMAND
  ## equivalent; ``fish_prompt`` could work but is per-render rather than
  ## per-cd, which makes the M76 short-circuit moot. We keep the cd
  ## semantics and rely on the next M77 cache-key check for the no-op
  ## branch.
  let reproExpr = reproExprFish(reproBin)
  result = "# repro shell hook (fish) — installed via `repro shell hook fish | source`\n"
  result.add("function __repro_shell_hook --on-variable PWD --description 'repro dev-env activation hook'\n")
  result.add("  set -l __repro_candidate ''\n")
  result.add("  set -l __repro_walk $PWD\n")
  result.add("  while test -n \"$__repro_walk\"; and test \"$__repro_walk\" != '/'\n")
  result.add("    if test -e \"$__repro_walk/reprobuild.nim\"; or test -e \"$__repro_walk/repro.nim\"; or test -e \"$__repro_walk/.repro/dev-env.lock\"\n")
  result.add("      set __repro_candidate $__repro_walk\n")
  result.add("      break\n")
  result.add("    end\n")
  result.add("    if test \"$__repro_walk\" = \"$HOME\"\n")
  result.add("      break\n")
  result.add("    end\n")
  result.add("    set __repro_walk (dirname -- $__repro_walk)\n")
  result.add("  end\n")
  result.add("  if set -q __REPRO_PROJECT_ROOT; and test -n \"$__REPRO_PROJECT_ROOT\"; and test \"$__REPRO_PROJECT_ROOT\" != \"$__repro_candidate\"\n")
  result.add("    if set -q __REPRO_ACTIVE_MANIFEST; and test -n \"$__REPRO_ACTIVE_MANIFEST\"\n")
  result.add("      " & reproExpr & " dev-env deactivate \"$__REPRO_ACTIVE_MANIFEST\" --shell=fish 2>/dev/null | source\n")
  result.add("    end\n")
  result.add("    set -e __REPRO_PROJECT_ROOT\n")
  result.add("    set -e __REPRO_APPLIED\n")
  result.add("    set -e __REPRO_ACTIVE_MANIFEST\n")
  result.add("  end\n")
  result.add("  if test -n \"$__repro_candidate\"; and test \"$__repro_candidate\" != (set -q __REPRO_PROJECT_ROOT; and echo $__REPRO_PROJECT_ROOT; or echo '')\n")
  result.add("    set -l __repro_pre_env (mktemp -t repro-pre-env.XXXXXX 2>/dev/null; or mktemp 2>/dev/null; or echo \"$TMPDIR/repro-pre-env.\"(echo %self))\n")
  result.add("    env -0 > $__repro_pre_env 2>/dev/null; or env > $__repro_pre_env\n")
  result.add("    " & reproExpr & " dev-env export fish --project-root \"$__repro_candidate\" --pre-activation-env \"$__repro_pre_env\" 2>/dev/null | source\n")
  result.add("    rm -f $__repro_pre_env 2>/dev/null\n")
  result.add("    set -gx __REPRO_PROJECT_ROOT $__repro_candidate\n")
  result.add("  end\n")
  result.add("end\n")
  # One-shot fire so the launching cwd activates.
  result.add("__repro_shell_hook\n")

proc reproExprPwsh(reproBin: string): string =
  if reproBin.len == 0:
    "repro"
  else:
    "& " & pwshSingleQuote(reproBin)

proc renderPwshHook*(reproBin: string): string =
  ## pwsh hook: wrap the existing ``prompt`` function so we run BEFORE
  ## the user's prompt rendering. The original prompt body is preserved
  ## via ``$script:__ReproOriginalPrompt`` and invoked at the end.
  let reproInvoke = reproExprPwsh(reproBin)
  result = "# repro shell hook (pwsh) — installed via `repro shell hook pwsh | Out-String | Invoke-Expression`\n"
  result.add("if (-not (Get-Variable -Name '__ReproOriginalPrompt' -Scope Script -ErrorAction SilentlyContinue)) {\n")
  result.add("  $existing = Get-Command prompt -ErrorAction SilentlyContinue\n")
  result.add("  if ($existing -and $existing.CommandType -eq 'Function') {\n")
  result.add("    $script:__ReproOriginalPrompt = $existing.Definition\n")
  result.add("  } else {\n")
  result.add("    $script:__ReproOriginalPrompt = $null\n")
  result.add("  }\n")
  result.add("}\n")
  result.add("function __Repro-ShellHook {\n")
  result.add("  $candidate = ''\n")
  result.add("  $walk = (Get-Location).ProviderPath\n")
  result.add("  $home_dir = $env:HOME\n")
  result.add("  if (-not $home_dir) { $home_dir = $env:USERPROFILE }\n")
  result.add("  while ($walk -and ($walk -ne (Split-Path $walk -Qualifier))) {\n")
  result.add("    if ((Test-Path (Join-Path $walk 'reprobuild.nim')) -or `\n")
  result.add("        (Test-Path (Join-Path $walk 'repro.nim')) -or `\n")
  result.add("        (Test-Path (Join-Path $walk '.repro/dev-env.lock'))) {\n")
  result.add("      $candidate = $walk\n")
  result.add("      break\n")
  result.add("    }\n")
  result.add("    if ($home_dir -and ($walk -eq $home_dir)) { break }\n")
  result.add("    $parent = Split-Path $walk -Parent\n")
  result.add("    if (-not $parent -or ($parent -eq $walk)) { break }\n")
  result.add("    $walk = $parent\n")
  result.add("  }\n")
  result.add("  $current = $env:__REPRO_PROJECT_ROOT\n")
  result.add("  if ($current -and ($current -ne $candidate)) {\n")
  result.add("    if ($env:__REPRO_ACTIVE_MANIFEST) {\n")
  result.add("      try {\n")
  result.add("        $deactScript = " & reproInvoke &
    " dev-env deactivate $env:__REPRO_ACTIVE_MANIFEST --shell=pwsh 2>$null | Out-String\n")
  result.add("        if ($deactScript) { Invoke-Expression $deactScript }\n")
  result.add("      } catch {}\n")
  result.add("    }\n")
  result.add("    Remove-Item Env:__REPRO_PROJECT_ROOT -ErrorAction SilentlyContinue\n")
  result.add("    Remove-Item Env:__REPRO_APPLIED -ErrorAction SilentlyContinue\n")
  result.add("    Remove-Item Env:__REPRO_ACTIVE_MANIFEST -ErrorAction SilentlyContinue\n")
  result.add("  }\n")
  result.add("  if ($candidate -and ($candidate -ne $env:__REPRO_PROJECT_ROOT)) {\n")
  result.add("    $preEnvPath = Join-Path ([System.IO.Path]::GetTempPath()) (\"repro-pre-env.\" + [Guid]::NewGuid().ToString() + \".bin\")\n")
  result.add("    $buf = New-Object System.Text.StringBuilder\n")
  result.add("    foreach ($entry in [System.Environment]::GetEnvironmentVariables().GetEnumerator()) {\n")
  result.add("      [void]$buf.Append($entry.Key); [void]$buf.Append('='); [void]$buf.Append($entry.Value); [void]$buf.Append([char]0)\n")
  result.add("    }\n")
  result.add("    [System.IO.File]::WriteAllText($preEnvPath, $buf.ToString(), [System.Text.Encoding]::UTF8)\n")
  result.add("    try {\n")
  result.add("      $script = " & reproInvoke &
    " dev-env export pwsh --project-root $candidate --pre-activation-env $preEnvPath 2>$null | Out-String\n")
  result.add("      if ($LASTEXITCODE -eq 0 -and $script) {\n")
  result.add("        Invoke-Expression $script\n")
  result.add("        $env:__REPRO_PROJECT_ROOT = $candidate\n")
  result.add("      }\n")
  result.add("    } catch {}\n")
  result.add("    Remove-Item -LiteralPath $preEnvPath -ErrorAction SilentlyContinue\n")
  result.add("  }\n")
  result.add("}\n")
  result.add("function prompt {\n")
  result.add("  __Repro-ShellHook\n")
  result.add("  if ($script:__ReproOriginalPrompt) {\n")
  result.add("    Invoke-Expression $script:__ReproOriginalPrompt\n")
  result.add("  } else {\n")
  result.add("    \"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) \"\n")
  result.add("  }\n")
  result.add("}\n")

proc reproExprNu(reproBin: string): string =
  if reproBin.len == 0:
    "repro"
  else:
    nuSingleQuote(reproBin)

proc renderNushellHook*(reproBin: string): string =
  ## nushell hook: ``env_change.PWD`` (chpwd) + ``pre_prompt`` (precmd).
  ## Nushell evaluates per-prompt closures; the activation script is
  ## captured into the current scope via ``load-env`` / ``$env.X = ...``
  ## (the M74 nushell formatter already emits this form).
  let reproExpr = reproExprNu(reproBin)
  result = "# repro shell hook (nushell) — installed via `repro shell hook nu | save -f ~/.repro-hook.nu; source ~/.repro-hook.nu`\n"
  result.add("def --env __repro_shell_hook [] {\n")
  result.add("  mut candidate = ''\n")
  result.add("  mut walk = ($env.PWD | default '')\n")
  result.add("  let home_dir = ($env.HOME? | default ($env.USERPROFILE? | default ''))\n")
  result.add("  while ($walk | is-not-empty) and ($walk != '/') {\n")
  result.add("    if (($walk + '/reprobuild.nim') | path exists) or (($walk + '/repro.nim') | path exists) or (($walk + '/.repro/dev-env.lock') | path exists) {\n")
  result.add("      $candidate = $walk\n")
  result.add("      break\n")
  result.add("    }\n")
  result.add("    if $walk == $home_dir { break }\n")
  result.add("    let parent = ($walk | path dirname)\n")
  result.add("    if $parent == $walk { break }\n")
  result.add("    $walk = $parent\n")
  result.add("  }\n")
  result.add("  let current = ($env.__REPRO_PROJECT_ROOT? | default '')\n")
  result.add("  if ($current | is-not-empty) and ($current != $candidate) {\n")
  result.add("    let manifest = ($env.__REPRO_ACTIVE_MANIFEST? | default '')\n")
  result.add("    if ($manifest | is-not-empty) {\n")
  result.add("      try { " & reproExpr &
    " dev-env deactivate $manifest --shell=nushell | from nuon | load-env } catch {}\n")
  result.add("    }\n")
  result.add("    hide-env __REPRO_PROJECT_ROOT\n")
  result.add("    hide-env __REPRO_APPLIED\n")
  result.add("    hide-env __REPRO_ACTIVE_MANIFEST\n")
  result.add("  }\n")
  result.add("  if ($candidate | is-not-empty) and ($candidate != ($env.__REPRO_PROJECT_ROOT? | default '')) {\n")
  result.add("    try { " & reproExpr &
    " dev-env export nushell --project-root $candidate | str trim } catch {}\n")
  result.add("    $env.__REPRO_PROJECT_ROOT = $candidate\n")
  result.add("  }\n")
  result.add("}\n")
  result.add("$env.config = ($env.config | upsert hooks.env_change.PWD [{|before, after| __repro_shell_hook }])\n")
  result.add("$env.config = ($env.config | upsert hooks.pre_prompt [{|| __repro_shell_hook }])\n")
