## B2 P2: GRUB menu generator.
##
## Emits ``/boot/grub/grub.cfg`` for the recorded generation tree. One
## ``menuentry`` per generation, sorted newest-first; the active
## generation is the default. A ``boot-prev`` boot-failure-recovery
## entry is always available and loads the second-newest generation's
## kernel + cmdline.
##
## The output is intentionally simple — a single deterministic GRUB
## config that ``grub-mkconfig`` would otherwise have to assemble out
## of multiple ``/etc/grub.d/`` fragments. We sidestep grub-mkconfig's
## script-y machinery because every input to this generator is already
## typed (the ``GenerationManifest`` records carry kernel + initrd +
## cmdline as flat strings) and because the campaign milestone needs
## byte-stable output the integration tests can diff.
##
## The boot-failure auto-fallback story (per the milestone spec):
##
##   * GRUB's ``set default=<entry>`` selects the menuentry the
##     bootloader presents on the next boot.
##   * GRUB's ``set fallback=<entry>`` activates if the default entry
##     fails to boot (we encode this in ``generateGrubMenu`` as the
##     ``boot-prev`` entry, which loads the previous generation).
##   * GRUB's ``set timeout=<seconds>`` keeps the menu visible long
##     enough that an operator can override the auto-boot if the
##     default entry is broken in a way that doesn't fail
##     ``initramfs``-side detection (the hard fallback only fires when
##     the kernel/initrd combination panics out of the
##     ``boot_attempt`` block; soft failures need the
##     ``reproos-confirm-generation`` systemd unit, which lives in the
##     pipeline + the systemd unit fragment).
##
## The generator does NOT write to ``/boot/grub/grub.cfg`` directly —
## the caller (the ``reproos-rebuild`` CLI) is responsible for that.
## This module returns a string so unit tests can compare byte-for-
## byte without touching the host filesystem.

import std/[algorithm, os, strutils, times]

import ./pipeline

type
  GrubGenerationInput* = object
    ## What ``generateGrubMenu`` needs per generation. The caller
    ## (the ``apply`` subcommand) assembles a ``seq[GrubGenerationInput]``
    ## by walking ``<state>/generations/`` and reading each
    ## ``manifest.txt``.
    number*: int                       ## the generation number
    activationTimestamp*: int64        ## seconds since epoch; used to
                                       ## render the menuentry title
    activationTimeIso*: string         ## the "YYYY-MM-DD HH:MM:SS"
                                       ## rendering for the menuentry
                                       ## title; empty -> derived from
                                       ## ``activationTimestamp``
    kernelPath*: string                ## absolute path to vmlinuz
                                       ## INSIDE the generation
                                       ## directory
    initrdPath*: string                ## absolute path to initrd.img
                                       ## INSIDE the generation
                                       ## directory
    cmdline*: string                   ## the space-joined kernel
                                       ## cmdline (already rendered by
                                       ## the pipeline)
    label*: string                     ## free-form label override;
                                       ## empty -> "ReproOS"

const
  DefaultMenuLabel = "ReproOS"
  GrubHeader = """# Generated by reproos-rebuild. Do not edit.
# See libs/repro_system_apply/src/repro_system_apply/grub.nim for the
# generator and ReproOS-Generations-And-Foreign-Packages.milestones.org
# "B2: System generation apply pipeline" for the contract.
set timeout=5
"""

proc humanTimestamp(g: GrubGenerationInput): string =
  if g.activationTimeIso.len > 0:
    # Replace the ISO "T" with " " so the GRUB label reads naturally.
    return g.activationTimeIso.replace("T", " ").replace("Z", "")
  if g.activationTimestamp == 0:
    return ""
  try:
    return fromUnix(g.activationTimestamp).utc.format(
      "yyyy-MM-dd HH:mm:ss")
  except CatchableError:
    return ""

proc renderMenuentry(g: GrubGenerationInput;
                     entryId: string;
                     titleSuffix: string): string =
  ## Render one GRUB menuentry. ``entryId`` becomes the GRUB-internal
  ## ``--id`` so ``set default="reproos-gen-N"`` works regardless of
  ## menu position; ``titleSuffix`` is appended after the human time
  ## (e.g. ``"(boot-prev fallback)"``).
  let label = if g.label.len > 0: g.label else: DefaultMenuLabel
  let ts = humanTimestamp(g)
  var title = label & " generation " & $g.number
  if ts.len > 0:
    title.add " — " & ts
  if titleSuffix.len > 0:
    title.add " " & titleSuffix
  var lines: seq[string]
  lines.add "menuentry '" & title & "' --id '" & entryId & "' {"
  lines.add "    linux  " & g.kernelPath & " " & g.cmdline
  lines.add "    initrd " & g.initrdPath
  lines.add "}"
  lines.join("\n") & "\n"

proc generationEntryId*(number: int): string =
  "reproos-gen-" & $number

const BootPrevEntryId* = "reproos-boot-prev"

proc generateGrubMenu*(generations: seq[GrubGenerationInput];
                      current: int): string =
  ## Emit a full ``/boot/grub/grub.cfg``. ``generations`` is the list
  ## of recorded generations; ``current`` is the generation number
  ## that should be the default boot target (i.e. the
  ## ``staged-next`` generation, or — if no apply is staged — the
  ## currently-confirmed generation). One ``boot-prev`` recovery
  ## entry is appended at the end and is also configured as the
  ## ``fallback`` target.
  if generations.len == 0:
    return GrubHeader & "# (no generations recorded yet)\n"
  var sorted = generations
  sorted.sort(proc(a, b: GrubGenerationInput): int = cmp(b.number, a.number))
  var out_buf = GrubHeader
  # Default entry selection.
  let defaultId = generationEntryId(current)
  out_buf.add "set default=\"" & defaultId & "\"\n"
  # Boot-failure fallback: pick the second-newest generation if
  # available; otherwise fall back to the same default (best effort
  # only — a single-generation system has no previous to fall back
  # to).
  var prevId = defaultId
  for g in sorted:
    if g.number != current:
      prevId = generationEntryId(g.number)
      break
  out_buf.add "set fallback=\"" & BootPrevEntryId & "\"\n"
  out_buf.add "\n"
  for g in sorted:
    out_buf.add renderMenuentry(g, generationEntryId(g.number), "")
    out_buf.add "\n"
  # boot-prev recovery entry — duplicates the previous-newest
  # generation's kernel + cmdline so the operator can pick it from
  # the menu manually OR the GRUB fallback wiring activates it
  # automatically.
  for g in sorted:
    let id = generationEntryId(g.number)
    if id == prevId:
      out_buf.add renderMenuentry(g, BootPrevEntryId,
        "(boot-prev fallback)")
      break
  out_buf

# ---------------------------------------------------------------------------
# Walking the state directory to assemble the input list.
# ---------------------------------------------------------------------------

proc enumerateGenerations*(stateDir: string): seq[GrubGenerationInput] =
  ## Scan ``<state>/generations/`` for integer-named directories,
  ## parse each ``manifest.txt``, and return the per-generation
  ## ``GrubGenerationInput`` records the GRUB generator consumes.
  ## Generations whose manifest is missing or malformed are silently
  ## skipped — the caller (the CLI) decides whether to warn.
  let root = generationsRoot(stateDir)
  if not dirExists(root): return
  for kind, path in walkDir(root):
    if kind != pcDir: continue
    let name = path.lastPathPart
    var n: int
    try: n = parseInt(name)
    except ValueError: continue
    let mp = path / ManifestFileName
    if not fileExists(mp): continue
    let manifest = parseManifest(readFile(mp))
    var input = GrubGenerationInput(number: n,
      activationTimestamp: manifest.activationTimestamp,
      activationTimeIso: manifest.activationTimeIso,
      kernelPath: path / "boot" / "vmlinuz",
      initrdPath: path / "boot" / "initrd.img",
      cmdline: manifest.kernelCmdline.parts.join(" "))
    result.add input
