## M21 — drift-check: CodeTracer's vendored copy of the incremental engine MUST
## be byte-identical to `sync(canonical)`.
##
## `reprobuild/libs/repro_ct_incremental` is the single source of truth; the
## codetracer copy under `src/ct_test/incremental/` is GENERATED by
## `tools/sync_ct_test_vendor.nim`. This test fails if the two have drifted, so
## an algorithm change in one cannot silently diverge from the other.
##
## It lives in reprobuild (which already references the codetracer sibling via
## `live_record.WorkspaceRoot`) because only here can it see BOTH trees. It does
## NOT silently pass when the codetracer sibling is absent: a missing checkout or
## vendored dir FAILS the test with a clear diagnostic (the sibling is a
## reprobuild-CI requirement for this campaign).
##
## Two assertions:
##   1. POSITIVE — `sync_ct_test_vendor --check` against the REAL codetracer
##      checkout exits 0 (the committed copy equals `sync(canonical)`).
##   2. NEGATIVE (self-test) — copy the vendored tree into a scratch dir, perturb
##      one vendored file, and confirm `--check` against the scratch dir exits
##      non-zero. This proves the check actually DETECTS drift (it is not a
##      vacuous pass), without ever mutating the real tree.

import std/[unittest, os, osproc, strutils]

const
  thisFile = currentSourcePath()
  testsDir = thisFile.parentDir
  libRoot = testsDir.parentDir
  syncToolNim = libRoot / "tools" / "sync_ct_test_vendor.nim"
  vendorRelDir = "src/ct_test/incremental"

  # The workspace sibling that holds the codetracer checkout. Mirrors
  # `live_record.WorkspaceRoot`; overridable for non-default layouts/CI.
  defaultWorkspaceRoot = "/Users/zahary/m/dev"

proc nimExe(): string =
  ## The `nim` to drive the generator compile with. Mirrors the full-suite
  ## driver's discovery so this test builds the same way under `nim c -r`.
  let envNim = getEnv("NIM")
  if envNim.len > 0 and fileExists(envNim): return envNim
  let onPath = findExe("nim")
  if onPath.len > 0: return onPath
  const fallback =
    "/nix/store/0a3x96yrzlpyhhx567ljbp6mpiv2gbi9-arm64-apple-darwin-nim-wrapper-2.2.4/bin/nim"
  if fileExists(fallback): return fallback
  "nim"

proc codetracerCheckout(): string =
  ## The codetracer checkout to verify. `$CODETRACER_CHECKOUT` wins; else the
  ## workspace sibling under `$REPROBUILD_WORKSPACE_ROOT` (default
  ## `/Users/zahary/m/dev`).
  let explicit = getEnv("CODETRACER_CHECKOUT")
  if explicit.len > 0: return explicit
  let root = getEnv("REPROBUILD_WORKSPACE_ROOT", defaultWorkspaceRoot)
  root / "codetracer"

proc buildSyncTool(): string =
  ## Compile the generator once into a temp binary; return its path.
  let outBin = getTempDir() / "sync_ct_test_vendor_drift_check"
  let (output, code) = execCmdEx(
    quoteShell(nimExe()) & " c --hints:off --warnings:off -o:" &
    quoteShell(outBin) & " " & quoteShell(syncToolNim))
  doAssert code == 0,
    "failed to compile the sync generator " & syncToolNim & ":\n" & output
  outBin

proc runCheck(bin, checkout: string): tuple[output: string, exitCode: int] =
  ## Run the generator in `--check` mode against `checkout`.
  execCmdEx(quoteShell(bin) & " --check " & quoteShell(checkout))

suite "M21 ct_test vendor drift-check":

  test "codetracer_vendor_is_in_sync_with_canonical":
    let checkout = codetracerCheckout()
    let vendorDir = checkout / vendorRelDir

    # NOT a silent skip: the codetracer sibling is a reprobuild-CI requirement
    # for this campaign. A missing checkout/vendored dir FAILS loudly.
    check fileExists(syncToolNim)
    if not dirExists(vendorDir):
      checkpoint("codetracer vendored dir not found: " & vendorDir &
        "\nThis drift-check requires the codetracer sibling checkout. Set " &
        "$CODETRACER_CHECKOUT or place codetracer next to reprobuild under " &
        "$REPROBUILD_WORKSPACE_ROOT (default " & defaultWorkspaceRoot & ").")
      check dirExists(vendorDir)  # fails the test with the diagnostic above
    else:
      let bin = buildSyncTool()

      # 1. POSITIVE: the committed copy equals sync(canonical).
      let (output, code) = runCheck(bin, checkout)
      if code != 0:
        checkpoint("DRIFT DETECTED — codetracer vendored copy differs from " &
          "sync(canonical). Regenerate with tools/sync_ct_test_vendor.sh.\n" &
          output)
      check code == 0

      # 2. NEGATIVE self-test: perturb a COPY and confirm the check fails. This
      #    proves the drift-check is not a vacuous pass. The real tree is never
      #    touched — we mirror only the vendored dir into a scratch checkout.
      let scratch = getTempDir() / "ct_vendor_drift_selftest"
      removeDir(scratch)
      let scratchVendor = scratch / vendorRelDir
      createDir(scratchVendor)
      for kind, path in walkDir(vendorDir):
        if kind in {pcFile, pcLinkToFile}:
          copyFile(path, scratchVendor / path.extractFilename)
      # Sanity: an unperturbed scratch copy is itself in sync.
      let (preOut, preCode) = runCheck(bin, scratch)
      if preCode != 0:
        checkpoint("scratch copy unexpectedly drifted before perturbation:\n" & preOut)
      check preCode == 0
      # Perturb engine.nim (append a stray comment line).
      let perturbed = scratchVendor / "engine.nim"
      writeFile(perturbed, readFile(perturbed) & "\n## DRIFT-CHECK SELFTEST PERTURBATION\n")
      let (postOut, postCode) = runCheck(bin, scratch)
      check postCode != 0
      check "engine.nim" in postOut
      removeDir(scratch)
