<#
M3 HOSTING+REPOS+INSTALLER gate, Windows/Scoop arm.

  pwsh -NoProfile -File tools/multi-distro-harness/tests/m3_install_scoop.ps1

Proves, with Scoop's own actions, output and exit codes:

  S1  the installer registers a Scoop bucket and Scoop installs reprobuild
  S2  a SECOND installer run changes nothing (measured, not asserted)
  S3  publishing a newer manifest makes `scoop status` report an update
  S4  `scoop update reprobuild` MOVES the box to the newer release
  S5  a TAMPERED archive is REJECTED by Scoop's own hash check
  S6  -Uninstall leaves no app and no bucket

with the control that makes S1 and S5 mean anything:

  N0  a manifest whose hash does not match the artifact is REJECTED,
      and the GENUINE one with the same URL is ACCEPTED. Without the
      pair, S5 could be passing because the download failed.

## The arm reports on ITSELF, two ways (N54)

A harness that dies must not look green, and must not look absent either.
Two independent guards, at the summary:

  * a terminating error anywhere in the body is CAUGHT and reported as
    `HARNESS DIED EARLY`, with the message and position. Before this, a
    `throw` unwound through `finally { Cleanup }` and killed the script
    there -- exit 1, stack trace, and NO summary line at all, so the
    check-count guard below never even evaluated;
  * a run that finished without throwing but performed fewer checks than
    the floor is a FAILURE too. That is a different fault (a branch that
    skipped its assertions) and neither guard implies the other.

Both were verified by injection: a `throw` after the S1 banner produces
the first, and raising the floor on a complete run produces the second.

## A REAL local bucket, not a placeholder

runquota's packaging leaves `@SCOOP_URL@` unsubstituted because no bucket
exists to publish to. A bucket is only a git repository containing
bucket/<app>.json, so one can be stood up locally -- and is, here. The
manifest is generated by the real release step
(scripts/release/repro-publish-repos.sh --ecosystem scoop) with its URL
pointed at a local HTTP server, so nothing is templated out.

## The user's own Scoop install is NOT touched

$env:SCOOP is redirected to a scratch root for the whole arm, so the apps
and buckets created here live and die in a temp directory. The arm asserts
the redirection took effect before installing anything: without that
check, a failed redirect would silently install into the developer's real
Scoop root.
#>
[CmdletBinding()]
param(
  [int]$Port = 8733,
  [string]$WorkRoot = ''
)

$ErrorActionPreference = 'Continue'
Set-StrictMode -Version Latest

$RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..\..')).Path
$InstallPs1 = Join-Path $RepoRoot 'scripts\install\repro-install.ps1'
$Publish = Join-Path $RepoRoot 'scripts\release\repro-publish-repos.sh'
$SignDir = Join-Path $RepoRoot 'scripts\release-signing'

if (-not $WorkRoot) { $WorkRoot = Join-Path $env:TEMP 'm3-install-scoop' }
$Www = Join-Path $WorkRoot 'www'
$Base = "http://127.0.0.1:$Port"
$V1 = '0.1.3'
$V2 = '0.1.4'
$AppName = 'reprobuild'
$BucketName = 'reprobuild'

$script:checks = 0
$script:fails = 0
# Set by the `catch` around the arm body when a terminating error kills the
# run. It is what turns an ABORT into a reported FAILURE: see the
# "TWO SEPARATE GUARDS" block above the summary.
$script:aborted = $null
# The FLOOR a complete run must clear -- not the number it performs. A
# complete green run at this revision performs 58 checks (measured, twice);
# the floor is left below that so adding or removing one assertion is not a
# red line, and far enough below nothing that an arm which stopped half way
# could clear it.
#
# N54: this guard covers a run that COMPLETED but performed FEWER CHECKS
# THAN EXPECTED -- a branch that quietly skipped its assertions, a
# refactor that dropped a Step, a condition that short-circuited an
# AssertX. It does NOT, on its own, catch an arm that DIES: a terminating
# error unwinds straight through `finally { Cleanup }` and the summary
# below is never reached at all, so the comparison never runs. That is
# what `$script:aborted` and the `catch` are for, and the two are
# independent. Raising this number is the way to prove the FIRST half
# fires; injecting a `throw` is the way to prove the SECOND.
$script:ExpectedMinChecks = 45
function Step { param([string]$m) Write-Host "`n=== $m ===" }
function Ok   { param([string]$m) $script:checks++; Write-Host "PASS  $m" }
function Bad  { param([string]$m) $script:checks++; $script:fails++; Write-Host "FAIL  $m" }
function AssertEq {
  param($Got, $Want, [string]$What)
  if ([string]$Got -eq [string]$Want) { Ok "$What (= $Got)" } else { Bad "${What}: expected '$Want', got '$Got'" }
}
function AssertNe {
  param($A, $B, [string]$What)
  if ([string]$A -ne [string]$B) { Ok "$What ('$A' != '$B')" } else { Bad "${What}: both are '$A'" }
}
function AssertFile { param([string]$p, [string]$what)
  if (Test-Path -LiteralPath $p) { Ok "$what exists: $p" } else { Bad "$what missing: $p" } }
function AssertAbsent { param([string]$p, [string]$what)
  if (-not (Test-Path -LiteralPath $p)) { Ok "$what is absent: $p" } else { Bad "$what still present: $p" } }
# Counts, never truthiness: a regex that matched nothing is a vacuous pass.
function AssertMatches {
  param([string]$Text, [string]$Pattern, [string]$What)
  $n = ([regex]::Matches($Text, $Pattern, 'IgnoreCase')).Count
  if ($n -ge 1) { Ok "$What (matched $n occurrence(s) on '$Pattern')" }
  else {
    Bad "${What}: pattern '$Pattern' matched 0 times"
    Write-Host "vvv text vvv"; Write-Host ($Text -split "`n" | Select-Object -First 40 | Out-String); Write-Host "^^^ end ^^^"
  }
}

# ---------------------------------------------------------------------
Step 'preconditions'
# ---------------------------------------------------------------------
foreach ($f in @($InstallPs1, $Publish, (Join-Path $SignDir 'make-test-key.sh'))) {
  if (-not (Test-Path -LiteralPath $f)) { Write-Host "missing required file: $f"; exit 1 }
}
foreach ($c in @('scoop', 'git', 'python')) {
  if (-not (Get-Command $c -ErrorAction SilentlyContinue)) {
    if ($c -eq 'python') {
      if (-not (Get-Command 'python3' -ErrorAction SilentlyContinue)) {
        Write-Host "missing required tool: python/python3 (needed for the local HTTP server)"; exit 1
      }
    } else { Write-Host "missing required tool: $c"; exit 1 }
  }
}
$Py = if (Get-Command 'python' -ErrorAction SilentlyContinue) { 'python' } else { 'python3' }
# The repo metadata generator is a POSIX shell script; on Windows it runs
# under Git for Windows' sh, which release.yml already assumes.
$Sh = (Get-Command 'sh' -ErrorAction SilentlyContinue)
if (-not $Sh) { Write-Host 'missing required tool: sh (Git for Windows)'; exit 1 }
$ShExe = $Sh.Source
Write-Host "scoop=$((scoop --version 2>&1 | Select-Object -First 1)) git=$(git --version) sh=$ShExe python=$Py"

if (Test-Path -LiteralPath $WorkRoot) { Remove-Item -LiteralPath $WorkRoot -Recurse -Force -ErrorAction SilentlyContinue }
New-Item -ItemType Directory -Path $Www -Force | Out-Null

# ---------------------------------------------------------------------
Step 'isolate SCOOP so the developer''s real install is untouched'
# ---------------------------------------------------------------------
$RealScoop = $env:SCOOP
$ScoopRoot = Join-Path $WorkRoot 'scoop'
New-Item -ItemType Directory -Path $ScoopRoot -Force | Out-Null
$env:SCOOP = $ScoopRoot
# Scoop expects its root to already have this skeleton; pointing $SCOOP
# at a bare empty directory makes `scoop bucket add` die inside Scoop's
# own commands.ps1 with "Cannot find path ...\shims". Creating the
# directories is all that is needed -- Scoop's CODE still comes from the
# real installation, only its DATA is redirected here.
foreach ($d in @('shims', 'buckets', 'apps', 'cache', 'persist')) {
  New-Item -ItemType Directory -Path (Join-Path $ScoopRoot $d) -Force | Out-Null
}
# Scoop resolves its SUPPORTING FILES out of $SCOOP\apps\scoop\current --
# notably supporting\shims\kiennq\shim.exe, which it copies when creating
# an app's shim. Without it `scoop install` gets as far as downloading,
# hash-checking and extracting, then fails at "Creating shim for 'repro'",
# and the app is left "not installed correctly" -- which in turn makes
# `scoop update` refuse it and `scoop uninstall` fail. So Scoop's own app
# tree is copied into the scratch root.
#
# Copied, not symlinked, and never written back: the real installation is
# only ever read. The final step of this arm asserts the real root's
# bucket count is unchanged.
$RealRootForCopy = $(if ($env:SCOOP -and $RealScoop) { $RealScoop } else { Join-Path $env:USERPROFILE 'scoop' })
$RealScoopApp = Join-Path $RealRootForCopy 'apps\scoop'
if (Test-Path -LiteralPath $RealScoopApp) {
  Copy-Item -LiteralPath $RealScoopApp -Destination (Join-Path $ScoopRoot 'apps\scoop') -Recurse -Force -ErrorAction SilentlyContinue
}
$ShimSrc = Join-Path $ScoopRoot 'apps\scoop\current\supporting\shims\kiennq\shim.exe'
# Asserted: if this is missing, every install below fails at the shim step
# and the arm's later phases would report confusing, unrelated failures.
AssertFile $ShimSrc 'the scratch Scoop root has Scoop''s own shim helper'
# `scoop update <app>` runs "Updating Buckets..." first, and with no
# 'main' bucket present it tries to convert one, fails with
# "ERROR 'main' bucket not found. / Failed to remove local 'main' bucket."
# and ABORTS before it ever looks at our app. So a minimal, empty 'main'
# bucket is created as a git repo to satisfy that maintenance pass.
#
# It is empty on purpose: cloning the real ScoopInstaller/Main would pull
# ~1600 manifests over the network for no benefit, and an empty bucket
# cannot accidentally supply the package under test -- every install below
# is addressed as `reprobuild/reprobuild`, so the app can only come from
# OUR bucket.
# It must be a CLONE, not a bare `git init`: Scoop's bucket refresh runs
# `git pull`, and a repo with no upstream fails with "There is no tracking
# information for the current branch", which aborts `scoop install` before
# it installs anything. So an origin is created and cloned from.
$MainOrigin = Join-Path $WorkRoot 'main-bucket-origin'
New-Item -ItemType Directory -Path (Join-Path $MainOrigin 'bucket') -Force | Out-Null
Set-Content -LiteralPath (Join-Path $MainOrigin 'bucket\.gitkeep') -Value '' -NoNewline
Push-Location $MainOrigin
& git init -q 2>&1 | Out-Null
& git config user.email 'm3-gate@reprobuild.invalid' | Out-Null
& git config user.name 'M3 Gate' | Out-Null
& git add -A 2>&1 | Out-Null
& git -c commit.gpgsign=false commit -q -m 'empty placeholder main bucket' 2>&1 | Out-Null
Pop-Location
$MainBucket = Join-Path $ScoopRoot 'buckets\main'
# protocol.file.allow=always: git >= 2.38 refuses local-path transport in
# some contexts by default.
& git -c protocol.file.allow=always clone -q ($MainOrigin -replace '\\','/') ($MainBucket -replace '\\','/') 2>&1 | Out-Null
Push-Location $MainBucket
& git config user.email 'm3-gate@reprobuild.invalid' | Out-Null
& git config user.name 'M3 Gate' | Out-Null
Pop-Location
AssertFile (Join-Path $MainBucket '.git') 'the placeholder main bucket is a git clone (has an upstream)'
# ASSERTED, not assumed: if the redirect did not take, everything below
# would install into the developer's real Scoop root.
AssertEq $env:SCOOP $ScoopRoot 'SCOOP is redirected to a scratch root'
AssertFile (Join-Path $ScoopRoot 'buckets') 'the scratch Scoop root has a buckets/ directory'
AssertNe $env:SCOOP $RealScoop 'the scratch root differs from the real SCOOP root'
# `Join-Path (if ...)` is a parse-time trap: `if` is a statement and
# cannot be a command argument, and PowerShell reports it only at run
# time as "The term 'if' is not recognized". Use a subexpression.
$RealScoopRoot = $(if ($RealScoop) { $RealScoop } else { Join-Path $env:USERPROFILE 'scoop' })
$RealBuckets = Join-Path $RealScoopRoot 'buckets'
$RealBucketBefore = $(if (Test-Path -LiteralPath $RealBuckets) {
  @(Get-ChildItem -LiteralPath $RealBuckets -Directory).Count } else { 0 })

$HttpProc = $null
function Stop-Http { if ($script:HttpProc -and -not $script:HttpProc.HasExited) { $script:HttpProc.Kill(); $script:HttpProc.WaitForExit(3000) } }
function Cleanup {
  Stop-Http
  try {
    if (Get-Command scoop -ErrorAction SilentlyContinue) {
      & scoop uninstall $AppName 6>$null 2>$null | Out-Null
      & scoop bucket rm $BucketName 6>$null 2>$null | Out-Null
    }
  } catch { }
  $env:SCOOP = $RealScoop
}

try {

# ---------------------------------------------------------------------
Step 'build two fixture Windows release archives (release.yml asset shape)'
# ---------------------------------------------------------------------
function New-FixtureZip {
  param([string]$Ver)
  $top = "reprobuild-$Ver-windows-x86_64"
  $d = Join-Path $WorkRoot "stage\$top"
  if (Test-Path -LiteralPath $d) { Remove-Item -LiteralPath $d -Recurse -Force }
  New-Item -ItemType Directory -Path (Join-Path $d 'bin') -Force | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $d 'lib') -Force | Out-Null
  # A .exe that reports its version, so the upgrade can be asserted
  # against INSTALLED BYTES. A .cmd is used rather than a compiled exe
  # because building real reprobuild is a heavy compile and this arm's
  # subject is the hosting/bucket/update machinery -- stated plainly, with
  # the cost: this does NOT prove reprobuild builds on Windows.
  Set-Content -LiteralPath (Join-Path $d 'bin\repro.exe') -Value "fixture-binary-$Ver" -NoNewline
  Set-Content -LiteralPath (Join-Path $d 'bin\repro-version.txt') -Value $Ver -NoNewline
  Set-Content -LiteralPath (Join-Path $d 'lib\reprofixture.dll') -Value "fixture-lib-$Ver" -NoNewline
  $zip = Join-Path $WorkRoot "pkgs-$Ver\$top.zip"
  New-Item -ItemType Directory -Path (Split-Path -Parent $zip) -Force | Out-Null
  Compress-Archive -Path $d -DestinationPath $zip -Force
  return $zip
}
$Zip1 = New-FixtureZip -Ver $V1
$Zip2 = New-FixtureZip -Ver $V2
AssertFile $Zip1 "fixture archive $V1"
AssertFile $Zip2 "fixture archive $V2"

# The archives are also the download surface the manifest points at.
foreach ($v in @($V1, $V2)) {
  $dl = Join-Path $Www "downloads\v$v"
  New-Item -ItemType Directory -Path $dl -Force | Out-Null
}
Copy-Item -LiteralPath $Zip1 -Destination (Join-Path $Www "downloads\v$V1") -Force
Copy-Item -LiteralPath $Zip2 -Destination (Join-Path $Www "downloads\v$V2") -Force

# ---------------------------------------------------------------------
Step "generate the $V1 Scoop manifest with the REAL release step"
# ---------------------------------------------------------------------
function Invoke-PublishScoop {
  param([string]$Ver, [string]$PkgDir, [string]$RepoRootDir)
  # No --key and no GNUPGHOME: a Scoop manifest is not signed, and the
  # publish step asks for a signing key only for the ecosystems that
  # actually sign. Passing one here would be accepted and never used.
  $pargs = @(
    ($Publish -replace '\\','/'),
    '--version', $Ver,
    '--packages', ($PkgDir -replace '\\','/'),
    '--ecosystem', 'scoop',
    '--repo-root', ($RepoRootDir -replace '\\','/'),
    '--target', ('local:' + ($Www -replace '\\','/')),
    '--scoop-downloads-base', "$Base/downloads",
    '--fetch-existing'
  )
  $out = & $ShExe @pargs 2>&1 | Out-String
  return $out
}
$pub1 = Invoke-PublishScoop -Ver $V1 -PkgDir (Join-Path $WorkRoot "pkgs-$V1") -RepoRootDir (Join-Path $WorkRoot 'repo1')
Write-Host $pub1
$ManifestPath = Join-Path $Www 'scoop\bucket\reprobuild.json'
AssertFile $ManifestPath 'published Scoop manifest'
AssertMatches $pub1 'scoop manifest: version=0\.1\.3' 'the publish step reported the manifest version'
$m1 = Get-Content -LiteralPath $ManifestPath -Raw
AssertMatches $m1 '"version":\s*"0\.1\.3"' 'manifest declares 0.1.3'
AssertMatches $m1 '"hash":\s*"sha256:[0-9a-f]{64}"' 'manifest carries a real sha256'
# The whole point of a local bucket: no placeholder survives.
AssertEq ([regex]::Matches($m1, '@SCOOP_URL@|@SCOOP_SHA256@').Count) 0 'manifest carries NO unsubstituted placeholder'
$expected1 = (Get-FileHash -Algorithm SHA256 -LiteralPath $Zip1).Hash.ToLowerInvariant()
AssertMatches $m1 ([regex]::Escape($expected1)) 'the manifest hash is the real digest of the archive'

# ---------------------------------------------------------------------
Step 'make the published bucket a git repository (what a bucket IS)'
# ---------------------------------------------------------------------
$BucketDir = Join-Path $Www 'scoop'
Push-Location $BucketDir
& git init -q 2>&1 | Out-Null
& git config user.email 'm3-gate@reprobuild.invalid' | Out-Null
& git config user.name 'M3 Gate' | Out-Null
& git add -A 2>&1 | Out-Null
& git -c commit.gpgsign=false commit -q -m "reprobuild $V1" 2>&1 | Out-Null
$headOk = (& git rev-parse --short HEAD 2>&1)
Pop-Location
AssertMatches "$headOk" '^[0-9a-f]{7,}$' 'the bucket is a git repo with a commit'

# ---------------------------------------------------------------------
Step 'serve the download surface over local HTTP (stands in for R2)'
# ---------------------------------------------------------------------
# N51 -- THE SERVER THIS STEP ASSERTS MUST BE THE SERVER THIS STEP STARTED.
#
# The dnf arm was measured failing this way: a stale `python3 -m http.server`
# from an EARLIER run still held the port, this run's own server died at once
# with "Address already in use", and the probe -- which asked only whether the
# URL answered -- printed PASS. Everything after it ran against the orphan.
# This arm had the identical shape (start a server, poll a URL, assert the
# URL) and is fixed with it.
#
# A unique token in the served tree would NOT settle this: $Www is a stable
# per-run path that a stale server rooted at the same string keeps serving, so
# it would answer for the token too. What is asserted instead:
#   (1) the port is FREE before we bind -- a pre-bound port is REFUSED here,
#       never adopted. On Windows this is the check that does the work;
#   (2) our own process has not exited after the readiness poll;
#   (3) the port answers;
#   (4) the set of LISTENING owner pids is exactly ours.
#
# WINDOWS DIFFERS FROM THE POSIX ARMS HERE, MEASURED RATHER THAN ASSUMED.
# On Linux a second `python3 -m http.server` on a held port dies at once with
# `[Errno 98] Address already in use`. On Windows it does NOT: python sets
# SO_REUSEADDR, the bind SUCCEEDS, and the port ends up with TWO listening
# sockets. Three runs on this host, a fresh port each time, first server "A"
# already holding it and second server "B" started after:
#
#   port 8811  A=63640 B=47780  A.HasExited=False  B.HasExited=False
#              netstat LISTENING pids = [47780, 63640]     served by A
#   port 8812  A=28108 B=15524  A.HasExited=False  B.HasExited=False
#              netstat LISTENING pids = [15524, 28108]     served by A
#   port 8813  A=4760  B=7632   A.HasExited=False  B.HasExited=False
#              netstat LISTENING pids = [4760, 7632]       served by A
#
# Two consequences, and both shape the code below:
#
#   * `HasExited` CANNOT catch a stale server on Windows. Our own process is
#     alive, healthy and answering nothing, while the orphan serves the run.
#     Check (2) is worth keeping for a server that dies for some OTHER reason,
#     but it is not the guard against this one.
#   * `Get-NetTCPConnection -State Listen` returned ONE of those two sockets
#     every time -- and WHICH one is arbitrary: the stale A on 8811 and 8813,
#     ours B on 8812. Asking it for "the" owner and comparing to our pid would
#     therefore have printed PASS on 8812 while server A served every byte.
#     That is the exact false green this whole step exists to delete, so the
#     enumeration below uses `netstat -ano`, which reported BOTH pids in all
#     three runs, and demands the set be exactly ours rather than "contains".
function Test-PortBound {
  param([int]$ThePort)
  $c = New-Object System.Net.Sockets.TcpClient
  try {
    $iar = $c.BeginConnect('127.0.0.1', $ThePort, $null, $null)
    if (-not $iar.AsyncWaitHandle.WaitOne(2000)) { return $false }
    $c.EndConnect($iar)
    return $true
  } catch { return $false } finally { $c.Close() }
}
function Get-PortListenerPids {
  # EVERY pid with a LISTENING socket on $ThePort, deduplicated and sorted.
  # `netstat -ano` rather than `Get-NetTCPConnection`: see the measurement in
  # the block comment above -- the cmdlet collapsed two listening sockets to
  # one and picked between them arbitrarily, which is a coin flip standing in
  # for an assertion. Returns an empty array if netstat is unavailable or
  # parses to nothing, which the caller reports rather than treats as a pass.
  param([int]$ThePort)
  try {
    return @(netstat -ano |
      Select-String ":$ThePort\s+.*LISTENING" |
      ForEach-Object { ($_ -split '\s+')[-1] } |
      Where-Object { $_ -match '^[0-9]+$' } |
      ForEach-Object { [int]$_ } |
      Sort-Object -Unique)
  } catch { return @() }
}

if (Test-PortBound $Port) {
  Write-Host "FATAL: port $Port is already bound BEFORE this run started its"
  Write-Host "       own server. Refusing to adopt it -- every check below"
  Write-Host "       would have measured the orphan instead of this run."
  $owners = @(Get-PortListenerPids $Port)
  if ($owners.Count -gt 0) {
    Write-Host ("       listening pid(s): " + ($owners -join ', '))
  }
  exit 1
}
Ok "port $Port was FREE before this run bound it (no orphan server adopted)"

$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = (Get-Command $Py).Source
$psi.Arguments = "-m http.server $Port --bind 127.0.0.1"
$psi.WorkingDirectory = $Www
$psi.UseShellExecute = $false
$psi.RedirectStandardOutput = $true
$psi.RedirectStandardError = $true
$script:HttpProc = [System.Diagnostics.Process]::Start($psi)
$served = $false
for ($i = 0; $i -lt 50; $i++) {
  if ($script:HttpProc.HasExited) { break }
  try {
    Invoke-WebRequest -Uri "$Base/downloads/v$V1/reprobuild-$V1-windows-x86_64.zip" -UseBasicParsing -Method Head -TimeoutSec 3 | Out-Null
    $served = $true; break
  } catch { Start-Sleep -Milliseconds 200 }
}
if ($script:HttpProc.HasExited) {
  Bad "the HTTP server THIS run started (pid $($script:HttpProc.Id)) exited with $($script:HttpProc.ExitCode)"
  Write-Host ($script:HttpProc.StandardError.ReadToEnd())
} elseif ($served) {
  Ok "local HTTP server (pid $($script:HttpProc.Id), started by THIS run) serves the archive over $Base"
} else {
  Bad "local HTTP server did not serve $Base"
}
$listenerPids = @(Get-PortListenerPids $Port)
if ($listenerPids.Count -eq 0) {
  Write-Host 'note: netstat listed no LISTENING socket for this port; ownership'
  Write-Host '      rests on the pre-bind refusal asserted above, not on a read.'
} elseif ($listenerPids.Count -eq 1 -and $listenerPids[0] -eq $script:HttpProc.Id) {
  Ok "port $Port is held by OUR server ALONE (the only LISTENING pid is $($listenerPids[0]))"
} else {
  # Deliberately "exactly ours", not "includes ours": under SO_REUSEADDR a
  # second listener can sit alongside ours and take every connection, so a
  # membership test would pass on precisely the failure being looked for.
  Bad ("port $Port has LISTENING pid(s) " + ($listenerPids -join ', ') +
       " -- not exactly the server this run started (pid $($script:HttpProc.Id))")
}

# =====================================================================
Step "S1  the installer registers a bucket and Scoop installs $V1"
# =====================================================================
$s1 = & pwsh -NoProfile -File $InstallPs1 -Method scoop -BaseUrl $Base -BucketUrl ($BucketDir -replace '\\','/') 2>&1 | Out-String
$S1_RC = $LASTEXITCODE
Write-Host $s1
AssertEq $S1_RC 0 'S1 installer exited 0'
AssertMatches $s1 "registering scoop bucket" 'S1 the installer registered the bucket'
$buckets = @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot 'buckets') -Directory -ErrorAction SilentlyContinue | ForEach-Object { $_.Name })
AssertEq ($buckets -contains $BucketName) 'True' 'S1 the bucket is registered in the scratch Scoop root'
$appDir = Join-Path $ScoopRoot "apps\$AppName\current"
AssertFile $appDir 'S1 the app directory exists'
AssertFile (Join-Path $appDir 'bin\repro.exe') 'S1 the payload landed'
function Get-InstalledVersion {
  $p = Join-Path $ScoopRoot "apps\$AppName\current\bin\repro-version.txt"
  if (Test-Path -LiteralPath $p) { return (Get-Content -LiteralPath $p -Raw).Trim() }
  return ''
}
AssertEq (Get-InstalledVersion) $V1 "S1 the INSTALLED PAYLOAD reports $V1"
# Scoop's own view of what it installed.
$list1 = (& scoop list *>&1 | Out-String)
AssertMatches $list1 ([regex]::Escape($V1)) "S1 scoop list reports $V1"

# =====================================================================
Step 'S2  IDEMPOTENCE: a second identical run changes nothing (measured)'
# =====================================================================
$beforeBuckets = @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot 'buckets') -Directory).Count
$beforeApps = @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot 'apps') -Directory).Count
$beforeVersionDirs = @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot "apps\$AppName") -Directory).Count
$beforeVersion = Get-InstalledVersion

$s2 = & pwsh -NoProfile -File $InstallPs1 -Method scoop -BaseUrl $Base -BucketUrl ($BucketDir -replace '\\','/') 2>&1 | Out-String
$S2_RC = $LASTEXITCODE
Write-Host $s2
# VACUITY: "nothing changed" is trivially true of a run that crashed, so
# the exit code is asserted to be 0 first.
AssertEq $S2_RC 0 'S2 second run exited 0 (so "no change" is not "it crashed")'
AssertMatches $s2 'already registered' 'S2 the installer detected the existing bucket instead of re-adding it'
AssertEq @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot 'buckets') -Directory).Count $beforeBuckets 'S2 bucket count unchanged'
# TWO buckets exist by design: the empty placeholder 'main' that Scoop's
# maintenance pass requires, plus ours. What idempotence means here is
# exactly ONE 'reprobuild' bucket, not one bucket in total.
AssertEq @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot 'buckets') -Directory |
             Where-Object { $_.Name -eq $BucketName }).Count 1 'S2 exactly ONE reprobuild bucket'
AssertEq @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot 'apps') -Directory).Count $beforeApps 'S2 app count unchanged'
AssertEq @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot "apps\$AppName") -Directory).Count $beforeVersionDirs 'S2 no extra app version directory'
AssertEq (Get-InstalledVersion) $beforeVersion 'S2 installed payload version unchanged'
AssertMatches $s2 "already installed|is already installed" 'S2 scoop itself said it was already installed'

# =====================================================================
Step "S3  publish $V2 into the bucket; Scoop then reports an update"
# =====================================================================
$pub2 = Invoke-PublishScoop -Ver $V2 -PkgDir (Join-Path $WorkRoot "pkgs-$V2") -RepoRootDir (Join-Path $WorkRoot 'repo2')
Write-Host $pub2
$m2 = Get-Content -LiteralPath $ManifestPath -Raw
AssertMatches $m2 '"version":\s*"0\.1\.4"' 'S3 the published manifest now declares 0.1.4'
$expected2 = (Get-FileHash -Algorithm SHA256 -LiteralPath $Zip2).Hash.ToLowerInvariant()
AssertMatches $m2 ([regex]::Escape($expected2)) 'S3 the manifest hash is the real digest of the NEW archive'

Push-Location $BucketDir
& git add -A 2>&1 | Out-Null
& git -c commit.gpgsign=false commit -q -m "reprobuild $V2" 2>&1 | Out-Null
$srcHead = (& git rev-parse HEAD 2>&1).Trim()
Pop-Location

# A bucket is a git repo and Scoop keeps a CLONE of it under
# $SCOOP/buckets/<name>; refreshing manifests means pulling that clone,
# which is literally what `scoop update` does for buckets.
#
# `scoop update` with no arguments is NOT used here: it also updates
# Scoop ITSELF, and in a redirected $SCOOP root it tries to relocate the
# Scoop installation into the scratch root and fails with
# "Failed to remove local 'main' bucket". The git pull below is the
# bucket half of that command, done directly. The UPGRADE itself (S4)
# remains `scoop update reprobuild` -- Scoop's own action -- which is the
# part that has to be Scoop's rather than ours.
$BucketClone = Join-Path $ScoopRoot "buckets\$BucketName"
AssertFile $BucketClone 'S3 Scoop keeps a clone of the bucket'
Push-Location $BucketClone
& git -c protocol.file.allow=always pull --no-rebase -q 2>&1 | Out-Null
$cloneHead = (& git rev-parse HEAD 2>&1).Trim()
Pop-Location
# The refresh must actually have advanced the clone, or S3/S4 would be
# testing the OLD manifest and S4's "no upgrade offered" would be
# indistinguishable from a broken pull.
AssertEq $cloneHead $srcHead 'S3 the bucket clone advanced to the new commit'
$cloneManifest = Get-Content -LiteralPath (Join-Path $BucketClone 'bucket\reprobuild.json') -Raw
AssertMatches $cloneManifest '"version":\s*"0\.1\.4"' 'S3 the CLONE now carries the 0.1.4 manifest'

$status = (& scoop status *>&1 | Out-String)
Write-Host $status
AssertMatches $status ([regex]::Escape($AppName)) 'S3 scoop status names reprobuild'
AssertMatches $status ([regex]::Escape($V2)) "S3 scoop status offers $V2"

# =====================================================================
Step "S4  scoop update MOVES the box from $V1 to $V2"
# =====================================================================
# VACUITY, the important one: a TRANSITION, not a first install. $V1 is
# asserted installed immediately before, the upgrade is SCOOP's own
# command with no installer involvement, and $V2 is asserted after.
AssertEq (Get-InstalledVersion) $V1 "S4 precondition: $V1 installed before the update"
$s4 = (& scoop update $AppName *>&1 | Out-String)
$S4_RC = $LASTEXITCODE
Write-Host $s4
AssertEq $S4_RC 0 'S4 scoop update exited 0'
AssertMatches $s4 "$([regex]::Escape($V1)).*$([regex]::Escape($V2))|Updating.*$([regex]::Escape($AppName))" 'S4 scoop reported the update transaction'
AssertEq (Get-InstalledVersion) $V2 "S4 the INSTALLED PAYLOAD now reports $V2"
$list2 = (& scoop list *>&1 | Out-String)
AssertMatches $list2 ([regex]::Escape($V2)) "S4 scoop list now reports $V2"

# =====================================================================
Step "S5  a TAMPERED archive is REJECTED by Scoop's own hash check"
# =====================================================================
# Same-size, in-place mutation, so nothing but the hash can fire.
# Derived from the manifest Scoop will actually use, so this step cannot
# end up tampering a file that is not in the install path. (It did, once:
# S4 had left 0.1.3 installed while this tampered 0.1.4, and `scoop
# install` then succeeded on an untouched archive.)
$liveManifest = Get-Content -LiteralPath (Join-Path $BucketClone 'bucket\reprobuild.json') -Raw | ConvertFrom-Json
$liveUrl = $liveManifest.architecture.'64bit'.url
AssertMatches $liveUrl '^http://127\.0\.0\.1:' 'S5 the manifest URL points at the local server'
$liveRel = ($liveUrl -replace '^http://127\.0\.0\.1:\d+/', '') -replace '/', '\'
$targetZip = Join-Path $Www $liveRel
AssertFile $targetZip 'S5 the artifact the manifest points at exists on the server'
Copy-Item -LiteralPath $targetZip -Destination (Join-Path $WorkRoot 'pristine-v2.zip') -Force
$sizeBefore = (Get-Item -LiteralPath $targetZip).Length
$bytes = [System.IO.File]::ReadAllBytes($targetZip)
$off = [int]($bytes.Length / 2)
for ($i = 0; $i -lt 8; $i++) { $bytes[$off + $i] = $bytes[$off + $i] -bxor 0xFF }
[System.IO.File]::WriteAllBytes($targetZip, $bytes)
AssertEq (Get-Item -LiteralPath $targetZip).Length $sizeBefore 'S5 the tampered archive has the SAME byte size'
AssertNe (Get-FileHash -Algorithm SHA256 -LiteralPath $targetZip).Hash `
         (Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $WorkRoot 'pristine-v2.zip')).Hash `
         'S5 the tampered archive does differ in content'

# Remove the app and its cached download, so the tampered bytes are the
# ones Scoop actually fetches. Without clearing the cache this step would
# "pass" by reinstalling the cached GOOD archive.
& scoop uninstall $AppName 6>$null 2>$null | Out-Null
& scoop cache rm $AppName 6>$null 2>$null | Out-Null
$cacheDir = Join-Path $ScoopRoot 'cache'
if (Test-Path -LiteralPath $cacheDir) {
  Get-ChildItem -LiteralPath $cacheDir -Filter "*$AppName*" -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
}
AssertEq @(Get-ChildItem -LiteralPath $cacheDir -Filter "*$AppName*" -ErrorAction SilentlyContinue).Count 0 `
  'S5 the Scoop download cache holds no reprobuild archive (so the tampered bytes are fetched)'

$s5 = (& scoop install "$BucketName/$AppName" *>&1 | Out-String)
$S5_RC = $LASTEXITCODE
Write-Host $s5
AssertNe $S5_RC 0 'S5 scoop install exited non-zero on the tampered archive'
AssertMatches $s5 "hash check failed|Hash check failed|doesn't match|does not match" `
  "S5 scoop reported a HASH CHECK FAILURE in its own words"
AssertAbsent (Join-Path $ScoopRoot "apps\$AppName\current\bin\repro.exe") 'S5 nothing was installed from the tampered archive'

# N0 control: restore the genuine archive; the SAME manifest and URL must
# now install. Without this, S5 could be passing because the download or
# the bucket was broken rather than because the hash was checked.
Copy-Item -LiteralPath (Join-Path $WorkRoot 'pristine-v2.zip') -Destination $targetZip -Force
$n0 = (& scoop install "$BucketName/$AppName" *>&1 | Out-String)
$N0_RC = $LASTEXITCODE
Write-Host $n0
AssertEq $N0_RC 0 'N0 the GENUINE archive installs from the same manifest and URL'
AssertEq (Get-InstalledVersion) $V2 "N0 the restored install reports $V2"

# =====================================================================
Step 'S6  -Uninstall leaves no app and no bucket'
# =====================================================================
AssertFile (Join-Path $ScoopRoot "apps\$AppName\current\bin\repro.exe") 'S6 precondition: the app is installed'
$s6 = & pwsh -NoProfile -File $InstallPs1 -Method scoop -BaseUrl $Base -Uninstall 2>&1 | Out-String
$S6_RC = $LASTEXITCODE
Write-Host $s6
AssertEq $S6_RC 0 'S6 uninstaller exited 0'
AssertAbsent (Join-Path $ScoopRoot "apps\$AppName") 'S6 the Scoop app directory'
$bucketsAfter = @(Get-ChildItem -LiteralPath (Join-Path $ScoopRoot 'buckets') -Directory -ErrorAction SilentlyContinue | ForEach-Object { $_.Name })
AssertEq ($bucketsAfter -contains $BucketName) 'False' 'S6 the Scoop bucket is deregistered'

$s6b = & pwsh -NoProfile -File $InstallPs1 -Method scoop -BaseUrl $Base -Uninstall 2>&1 | Out-String
AssertEq $LASTEXITCODE 0 'S6 a SECOND uninstall is a no-op, not an error'

# ---------------------------------------------------------------------
Step "the developer's real Scoop root was not touched"
# ---------------------------------------------------------------------
$RealBucketAfter = if (Test-Path -LiteralPath $RealBuckets) {
  @(Get-ChildItem -LiteralPath $RealBuckets -Directory).Count } else { 0 }
AssertEq $RealBucketAfter $RealBucketBefore "the real Scoop root still has $RealBucketBefore bucket(s)"

} catch {
  # N54. WITHOUT THIS CATCH the summary below was unreachable from an
  # abort. A terminating error inside the body unwinds through
  # `finally { Cleanup }` and terminates the script there, so `Step
  # 'summary'` never ran, the min-check comparison never evaluated, and
  # the only evidence of the abort was PowerShell's own stack trace plus
  # a non-zero exit -- with NO summary line at all. A caller that greps
  # for "0 failure(s)" saw nothing; a caller that greps for the summary
  # line to decide "did the arm run?" saw nothing either.
  #
  # Catching converts the abort into a recorded FAILURE that reaches the
  # summary. It does not swallow anything: the error's message and
  # position are printed, `Bad` makes `$script:fails` non-zero, and the
  # exit code stays 1.
  #
  # WHAT IT STILL DOES NOT COVER, stated rather than implied: a bare
  # `exit` inside the body. PowerShell runs `finally` and then leaves,
  # so the summary below is skipped exactly as it was before this catch.
  # There is no `exit` in the body today and none should be added --
  # `Bad` is how this arm reports a failure. Moving the summary into
  # `finally` would cover it but would also overwrite the exit code the
  # `exit` chose, which is a worse trade.
  $script:aborted = $_
} finally {
  Cleanup
}

Step 'summary'
# TWO SEPARATE GUARDS, because they catch two different failures and
# neither implies the other (N54):
#
#   1. THE ARM DIED. A terminating error anywhere in the body lands in
#      the `catch` above. Reported here, by name, in the harness's own
#      PASS/FAIL vocabulary -- the same shape M6's buildusers gates use
#      with their EXIT trap ("HARNESS DIED EARLY"). A dead arm must never
#      produce a summary that reads green, and must never produce NO
#      summary either.
#   2. THE ARM COMPLETED BUT WAS SHORT. It reached the end without
#      throwing, yet performed fewer checks than a complete run. Nothing
#      about (1) detects that: no error was raised. This is the check
#      count floor, and it is defence in depth against a silently skipped
#      branch rather than against an abort.
if ($null -ne $script:aborted) {
  $pos = ''
  if ($script:aborted.InvocationInfo) { $pos = ($script:aborted.InvocationInfo.PositionMessage -replace "`r?`n", ' ').Trim() }
  Bad ("HARNESS DIED EARLY after {0} check(s): {1} {2}" -f ($script:checks), ($script:aborted.Exception.Message), $pos)
  Write-Host 'vvv terminating error vvv'
  Write-Host ($script:aborted | Out-String)
  Write-Host '^^^ end ^^^'
}
if ($script:checks -lt $script:ExpectedMinChecks) {
  Bad ("the arm performed only {0} checks; a complete run performs at least {1}. It exited early or skipped assertions -- treat this as a FAILURE, not a pass." -f ($script:checks), $script:ExpectedMinChecks)
}
Write-Host ("m3_install_scoop: {0} checks, {1} failure(s)" -f $script:checks, $script:fails)
if ($script:fails -gt 0) { exit 1 }
exit 0
