version = "0.1.0"
author = "Metacraft Labs"
description = "Reprobuild RBPI profile-intent binary envelope (M83 Phase B)"
license = "MIT"
srcDir = "src"
requires "nim >= 2.2.0"
requires "repro_profile"
requires "cbor"
requires "blake3"
