## Auto-loading a foreign environment when a project has no `repro.nim`.
##
## Two configuration flags — one for `.envrc`, one for `flake.nix` — let a
## directory that Reprobuild knows nothing about still get a dev environment.
## Precedence is fixed and total:
##
##     repro.nim  >  .envrc  >  flake.nix
##
## `repro.nim` wins because it is the project's own answer, and a project that
## has written one has already said what its environment is; auto-loading over
## the top of it would be Reprobuild overruling the recipe. `.envrc` beats
## `flake.nix` because an `.envrc` that exists is usually a SUPERSET of the
## flake — in this very workspace `reprobuild/.envrc` runs `use flake` and then
## adds override arguments, `.env` and a fingerprint watch, so activating the
## flake alone would produce a strictly smaller environment than the one the
## project is actually developed in.
##
## ## Auto-load is a synthesised `repro.nim`, not a second mechanism
##
## `synthesizedProjectFileText` returns a real recipe whose `devEnv:` body is
## the SAME one-liner a hand-written `repro.nim` would contain. Auto-load then
## runs the ordinary dev-env edge over it: the same provider compile, the same
## monitored introspection, the same cached artifact, the same invalidation.
## There is one code path with three entry points (hand-written `repro.nim`,
## auto-loaded `.envrc`, auto-loaded `flake.nix`), not a parallel activation
## mechanism that has to be kept in step with the real one.
##
## The synthesised file is written into `.repro/`, never next to the user's
## sources: it is derived state, and a `repro.nim` appearing in a directory the
## user did not put one in would change what every other verb resolves.

import std/os

import repro_core/paths

type
  ForeignEnvSource* = enum
    ## Which foreign environment auto-load activates, if any.
    fesNone      ## Nothing to auto-load (or a `repro.nim` already answers).
    fesEnvrc     ## `.envrc`, through `direnv export bash`.
    fesFlake     ## `flake.nix`, through `nix print-dev-env`.

  ForeignEnvAutoLoad* = object
    ## The two flags, resolved. Separate rather than one tri-state because a
    ## project may well want the flake auto-loaded and never want an arbitrary
    ## `.envrc` executed on its behalf (or the reverse), and a single knob
    ## cannot express either preference.
    envrc*: bool
    flake*: bool

const
  SynthesizedProjectFileDirName* = "foreign-env"
  SynthesizedProjectFileName* = "repro.nim"
  SynthesizedPackageName* = "foreign_env_project"
    ## NOT `foreign_env`: the synthesised recipe imports the module of that
    ## name, and Nim's identifier equality is case- and underscore-insensitive,
    ## so `package foreign_env:` fails to compile with
    ## `redefinition of 'foreign_env'` against its own import line.

proc synthesizedProjectFileDir*(projectRoot: string): string =
  projectRoot / ".repro" / SynthesizedProjectFileDirName

proc synthesizedProjectFilePath*(projectRoot: string): string =
  ## Where the synthesised recipe lands. Named `repro.nim` so that everything
  ## downstream — the provider compile, the recipe-content digest, diagnostics
  ## that print the module path — sees an ordinary project file.
  synthesizedProjectFileDir(projectRoot) / SynthesizedProjectFileName

proc chooseForeignEnvSource*(hasProjectFile, hasEnvrc, hasFlake: bool;
                             autoLoad: ForeignEnvAutoLoad): ForeignEnvSource =
  ## The whole precedence rule, in one place and pure so it is asserted rather
  ## than described.
  if hasProjectFile:
    return fesNone
  if autoLoad.envrc and hasEnvrc:
    return fesEnvrc
  if autoLoad.flake and hasFlake:
    return fesFlake
  fesNone

proc foreignEnvOneLiner*(source: ForeignEnvSource): string =
  ## The exact `devEnv:` body for each source — one call, no arguments. This
  ## string is the one-liner claim made checkable: if activating a flake ever
  ## stops being expressible in one line, this proc stops being able to return
  ## one.
  case source
  of fesNone: ""
  of fesEnvrc: "useEnvrc()"
  of fesFlake: "useFlakeDevShell()"

proc synthesizedProjectFileText*(source: ForeignEnvSource;
                                 packageName = SynthesizedPackageName): string =
  ## The synthesised recipe. Deliberately minimal: a package, a `devEnv:`
  ## block, and the one-liner. No `uses:`, because the point of the degenerate
  ## end is that the FOREIGN environment defines everything in the shell.
  let call = foreignEnvOneLiner(source)
  if call.len == 0:
    return ""
  "## Generated by Reprobuild (NF-4 foreign-environment auto-load).\n" &
  "##\n" &
  "## This directory has no repro.nim, and auto-load is enabled for the\n" &
  "## foreign environment this file activates. It is derived state: it is\n" &
  "## rewritten whenever the decision changes and is not meant to be edited.\n" &
  "## Writing a real repro.nim in the project root replaces it — a project\n" &
  "## file always wins over auto-load.\n" &
  "\n" &
  "import repro_project_dsl\n" &
  "import repro_dsl_stdlib/foreign_env\n" &
  "\n" &
  "package " & packageName & ":\n" &
  "  devEnv:\n" &
  "    " & call & "\n"

proc detectForeignEnvSource*(projectRoot: string;
                             autoLoad: ForeignEnvAutoLoad): ForeignEnvSource =
  ## `chooseForeignEnvSource` against the real filesystem. The project-file
  ## probe accepts either spelling, matching `repro_core.resolveProjectFile`.
  let hasProjectFile =
    fileExists(extendedPath(projectRoot / "repro.nim")) or
    fileExists(extendedPath(projectRoot / "reprobuild.nim"))
  chooseForeignEnvSource(hasProjectFile,
    fileExists(extendedPath(projectRoot / ".envrc")),
    fileExists(extendedPath(projectRoot / "flake.nix")),
    autoLoad)

proc ensureSynthesizedProjectFile*(projectRoot: string;
                                   source: ForeignEnvSource): string =
  ## Materialise the synthesised recipe and return its path (empty when there
  ## is nothing to synthesise). Rewrites only when the content differs, so a
  ## repeated shell entry does not touch the file's mtime — the provider
  ## compile is keyed on this file, and churning it would rebuild the provider
  ## on every prompt.
  let text = synthesizedProjectFileText(source)
  if text.len == 0:
    return ""
  let dir = synthesizedProjectFileDir(projectRoot)
  createDir(extendedPath(dir))
  let path = synthesizedProjectFilePath(projectRoot)
  var existing = ""
  if fileExists(extendedPath(path)):
    try:
      existing = readFile(extendedPath(path))
    except CatchableError:
      existing = ""
  if existing != text:
    writeFile(extendedPath(path), text)
  path
