#!/usr/bin/env bash
set -euo pipefail

# ``scripts/run_tests.sh`` is a thin shim around the protocol-level
# parallel runner at ``tools/test-runner/repro_test_runner.nim``. The
# build phase builds sibling daemons + test helpers, then runs
# ``repro build test`` for every test binary (the typed-output edge
# graph generated by ``scripts/generate_test_edges.nim`` declares each
# test as a ``buildNimUnittest.build`` call; tests that need
# ``--define:reproProviderMode`` pass it through the adapter's
# ``defines`` parameter, so the full suite is routed through reprobuild
# with no path-based shell carry-forward). Execution is delegated to
# the new runner, which speaks the Tier-1 binary protocol shipped in
# ``ct_test_unittest_parallel`` and fans out per-test ``--run``
# invocations across ``nproc`` workers.
#
# Migration note (Project-DSL-Composition M6, in flight): the data-table
# shape exported by ``repro_tests.nim`` (a ``seq[TestSpec]`` const) is
# now consumed by ``repro.nim``'s ``build:`` loop; the
# ``include "repro.tests.nim"`` line that previously stitched the
# fragment into the package body is gone. CI's ``Test`` job will
# eventually switch to ``./build/bin/repro build test`` (the next
# follow-on after M6's verification tests pass on a fresh checkout);
# until then this shim remains the primary driver.
#
# The only build-phase carry-forward that remains is the macOS arm64
# HCR codesign workaround for three ``t_hcr_*`` / ``t_e2e_repro_watch_hcr_*``
# tests that need ``--passC:-fpatchable-function-entry=16,0`` plus
# ``--passL:-Wl,-segprot,__HCR,rwx,rwx``; the typed-tool ``defines:``
# slot only carries ``-d:`` defines, not arbitrary ``--passC`` /
# ``--passL`` flags. This is platform-specific and stays separate.

mkdir -p build/test-bin build/nimcache test-logs

bash ./scripts/build_apps.sh

# Build out-of-repo test prerequisites BEFORE compiling the suite.
build_sibling() {
  local sibling_dir="$1"
  local marker_path="$2"
  if [[ ! -d "${sibling_dir}" ]]; then
    return 0
  fi
  if [[ -x "${marker_path}" ]]; then
    return 0
  fi
  printf 'Building prerequisite: %s\n' "${sibling_dir}" >&2
  (cd "${sibling_dir}" && just build)
}

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*|Windows_NT)
    exe_ext=".exe"
    ;;
  *)
    exe_ext=""
    ;;
esac
build_sibling "../runquota" "../runquota/build/bin/runquotad${exe_ext}"

# Test-side helper binaries that more than one suite reuses.
build_test_helper() {
  local source_path="$1"
  local output_path="$2"
  local cache_name="$3"
  if [[ -x "${output_path}" ]]; then
    return 0
  fi
  printf 'Building test helper: %s\n' "${output_path}" >&2
  nim c \
    --threads:on \
    --hints:off \
    --warnings:off \
    --nimcache:"build/nimcache/${cache_name}" \
    --out:"${output_path}" \
    "${source_path}"
}

build_test_helper \
  "tests/fixtures/local-daemons-control-plane/live-endpoint-helper/live_endpoint_helper.nim" \
  "build/test-bin/live_endpoint_helper${exe_ext}" \
  "live_endpoint_helper"
build_test_helper \
  "tests/fixtures/local-daemons-control-plane/fake-protocol-daemon-helper/fake_protocol_daemon_helper.nim" \
  "build/test-bin/fake_protocol_daemon_helper${exe_ext}" \
  "fake_protocol_daemon_helper"

if [[ -f tests/e2e/home-generations/harness_apply_lock_holder.nim ]]; then
  nim c \
    --threads:on \
    --hints:off \
    --nimcache:build/nimcache/harness_apply_lock_holder \
    --out:build/test-bin/harness_apply_lock_holder \
    tests/e2e/home-generations/harness_apply_lock_holder.nim
fi

# macOS arm64 HCR codesign workaround: three tests need
# --passC:-fpatchable-function-entry=16,0 plus
# --passL:-Wl,-segprot,__HCR,rwx,rwx that the typed-tool defines: slot
# can't carry. These compile via direct ``nim c`` on Apple Silicon and
# are skipped (already built via repro build test) on every other
# platform.
hcr_extra_flags() {
  local test_name="$1"
  if [[ "${test_name}" == "t_hcr_agent_process_target" ||
        "${test_name}" == "t_e2e_repro_watch_hcr_multi_target_independent_patches" ||
        "${test_name}" == "t_e2e_repro_watch_hcr_one_target_agent_inject_failure" ]] &&
      [[ "$(uname -s)" == "Darwin" ]] &&
      [[ "$(uname -m)" == "arm64" || "$(uname -m)" == "aarch64" ]]; then
    printf '%s\n' "--passC:-fpatchable-function-entry=16,0"
    printf '%s\n' "--passL:-Wl,-segprot,__HCR,rwx,rwx"
  fi
}

compile_hcr_workaround() {
  local test_file="$1"
  local test_name
  test_name="$(basename "${test_file}" .nim)"
  local extra_flags=()
  while IFS= read -r flag; do
    [[ -n "${flag}" ]] && extra_flags+=("${flag}")
  done < <(hcr_extra_flags "${test_name}")
  printf 'Compiling HCR-workaround test: %s\n' "${test_file}" >&2
  nim c \
    --threads:on \
    --hints:off \
    --warnings:off \
    ${extra_flags[@]+"${extra_flags[@]}"} \
    --nimcache:"build/nimcache/${test_name}" \
    --out:"build/test-bin/${test_name}" \
    "${test_file}"
}

# Build the engine-driven test binaries (the entire suite minus the
# macOS arm64 HCR workaround tests).
printf 'Building test binaries via repro build test\n' >&2
./build/bin/repro build test

# macOS arm64 HCR workaround: rebuild three specific tests via direct
# ``nim c`` so they pick up the patchable-function-entry + segprot
# flags repro build test cannot supply. No-op on Linux / other archs.
if [[ "$(uname -s)" == "Darwin" &&
      ( "$(uname -m)" == "arm64" || "$(uname -m)" == "aarch64" ) ]]; then
  while IFS= read -r -d '' test_file; do
    test_name="$(basename "${test_file}" .nim)"
    if [[ -n "$(hcr_extra_flags "${test_name}")" ]]; then
      compile_hcr_workaround "${test_file}"
    fi
  done < <(
    find tests -type f -name 't_*.nim' -print0
    find libs -path '*/tests/t_*.nim' -type f -print0
  )
fi

# Python tests run before the Nim suite so a Python regression surfaces
# fast and doesn't get buried in the Nim output.
while IFS= read -r -d '' test_file; do
  python3 "${test_file}"
done < <(
  find tests -type f -name 'test_*.py' -print0
)

# M4: prefer ct-test-runner from the sibling ``ct-test`` repo. The
# protocol contract is identical to the M3 internal runner (both speak
# the Tier-1 Standard --list-json/--run/$NIMTEST_RESULT_FILE wire), so
# the cut-over is the equivalent of swapping which binary is invoked.
# If ct-test-runner isn't built (e.g. workspace without ct-test
# checked out, or pre-build environment), fall back to the M3 internal
# runner at ``tools/test-runner/repro_test_runner.nim``. The fallback
# keeps the build green during the transition and is removed once the
# wider workspace catalog wires ct-test-runner as a typed ``uses:``
# dependency.
ct_test_runner="../ct-test/build/bin/ct-test-runner${exe_ext}"
if [[ -x "${ct_test_runner}" ]]; then
  printf 'Using ct-test-runner: %s\n' "${ct_test_runner}" >&2
  "${ct_test_runner}" run \
    --bin-dir=build/test-bin \
    --summary-json=test-logs/parallel-run.json \
    --results-dir=test-logs/results
else
  printf 'ct-test-runner not built; falling back to M3 internal runner\n' >&2
  runner_bin="build/bin/repro_test_runner${exe_ext}"
  if [[ ! -x "${runner_bin}" ]]; then
    printf 'Building M3 fallback runner: %s\n' "${runner_bin}" >&2
    nim c \
      -d:release \
      --threads:on \
      --hints:off \
      --warnings:off \
      --nimcache:build/nimcache/repro_test_runner \
      --out:"${runner_bin}" \
      tools/test-runner/repro_test_runner.nim
  fi
  # The runner already ran ``repro build test`` for us above; tell it to
  # skip its own build step so we don't double-build.
  "${runner_bin}" \
    --no-build \
    --bin-dir=build/test-bin \
    --summary-json=test-logs/parallel-run.json \
    --results-dir=test-logs/results
fi
