#requires -Version 5
# End-to-end M17/M28 verification: build the c-cpp-autotools/hello-binary
# example via the Tier 2b dispatch path and run the produced executable.
#
# Mechanics:
#
#   1. Source D:/metacraft/env.ps1 so gcc/repro are on PATH.
#   2. Probe for gcc + make (+ autoreconf when no ``configure`` is
#      checked in) + sh. SKIP exit 0 if any required tool is missing.
#   3. Wipe any prior .repro/ scratch + leftover generated configure
#      machinery so the build runs cold.
#   4. Invoke repro.exe build <fixture>#default --tool-provisioning=path.
#   5. Assert exit code 0.
#   6. M28: locate the produced ``hello.exe`` under the per-member
#      scratch directory ``<fixture>/.repro/build/hello/`` (the per-
#      source lift's link-action output) and run it; assert stdout
#      contains ``hello from c-cpp-autotools-hello-binary``.
#
# Per reprobuild-specs/Standard-Provider-Implementation.milestones.org
# §M17 + §M28 verifications "e2e_c_cpp_autotools_hello_binary_builds_via_standard_provider"
# and "e2e_autotools_per_source_lift".

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\..\..\env.ps1"

$repoRoot       = (Resolve-Path "$PSScriptRoot\..").Path
$metacraftRoot  = (Resolve-Path "$PSScriptRoot\..\..").Path
$reproExe       = Join-Path $repoRoot 'build\bin\repro.exe'
$providerExe    = Join-Path $repoRoot 'build\bin\repro-standard-provider.exe'
$fixture        = Join-Path $metacraftRoot 'reprobuild-examples\c-cpp-autotools\hello-binary'
$scratchInsideFixture = Join-Path $fixture '.repro'
$expectedGreeting = 'hello from c-cpp-autotools-hello-binary'

# --- preflight ---
if (-not (Test-Path -LiteralPath $reproExe)) {
  Write-Host "FAIL: missing $reproExe -- run scripts\build_apps.sh first"
  exit 1
}
if (-not (Test-Path -LiteralPath $providerExe)) {
  Write-Host "FAIL: missing $providerExe -- run scripts\build_apps.sh first"
  exit 1
}
if (-not (Test-Path -LiteralPath (Join-Path $fixture 'reprobuild.nim'))) {
  Write-Host "FAIL: fixture missing at $fixture"
  exit 1
}

# --- toolchain probe ---
# env.ps1 only adds the MinGW64 path; autotools needs the POSIX side of
# MSYS2 too (sh.exe + make.exe under usr/bin). Fall back to the managed
# install path when those tools aren't already on PATH.
$msys2UsrBin = 'D:\metacraft-dev-deps\msys2\msys64\usr\bin'
if ((Test-Path -LiteralPath (Join-Path $msys2UsrBin 'make.exe')) -and
    (Test-Path -LiteralPath (Join-Path $msys2UsrBin 'sh.exe'))) {
  if (-not ($env:PATH -split ';' | Where-Object { $_ -ieq $msys2UsrBin })) {
    $env:PATH = "$msys2UsrBin;$env:PATH"
  }
}

$gcc = Get-Command gcc -ErrorAction SilentlyContinue
$clang = $null
if (-not $gcc) {
  $clang = Get-Command clang -ErrorAction SilentlyContinue
}
if (-not $gcc -and -not $clang) {
  Write-Host "SKIP: neither gcc nor clang on PATH"
  exit 0
}

$make = Get-Command make -ErrorAction SilentlyContinue
$mingwMake = $null
if (-not $make) {
  $mingwMake = Get-Command mingw32-make -ErrorAction SilentlyContinue
}
if (-not $make -and -not $mingwMake) {
  Write-Host "SKIP: neither 'make' nor 'mingw32-make' on PATH"
  exit 0
}

$sh = Get-Command sh -ErrorAction SilentlyContinue
if (-not $sh) {
  Write-Host "SKIP: 'sh' not on PATH (POSIX shell required for autotools)"
  exit 0
}

$hasConfigure = Test-Path -LiteralPath (Join-Path $fixture 'configure')
$autoreconf = Get-Command autoreconf -ErrorAction SilentlyContinue
if (-not $hasConfigure -and -not $autoreconf) {
  Write-Host "SKIP: no checked-in 'configure' script and 'autoreconf' not on PATH (run windows/ensure-msys2-autotools.ps1 to provision autoconf + automake into D:/metacraft-dev-deps/msys2/msys64/usr/bin)"
  exit 0
}
# M17 fixture is repo-checkout shape (no committed configure); the
# script-level wipe below removes any released-tarball artefacts a prior
# autoreconf run might have left in the source tree. The convention's
# configure action regenerates them on every run.

Write-Host "==> autotools toolchain available; proceeding"

# --- step 1: clean prior scratch + autotools-generated detritus ---
# The M17 fixture is repo-checkout shape (only ``configure.ac`` +
# ``Makefile.am`` + ``src/`` are committed); every other file is
# generated by autoreconf or configure on every run.
if (Test-Path -LiteralPath $scratchInsideFixture) {
  Write-Host "wiping prior scratch dir $scratchInsideFixture"
  Remove-Item -LiteralPath $scratchInsideFixture -Recurse -Force
}
foreach ($leftover in @('Makefile', 'Makefile.in', 'config.log',
    'config.status', 'aclocal.m4', 'configure', 'confdefs.h',
    'hello', 'hello.exe')) {
  $path = Join-Path $fixture $leftover
  if (Test-Path -LiteralPath $path) {
    Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
  }
}
foreach ($leftoverDir in @('autom4te.cache', 'build-aux', '.deps')) {
  $path = Join-Path $fixture $leftoverDir
  if (Test-Path -LiteralPath $path) {
    Remove-Item -LiteralPath $path -Recurse -Force -ErrorAction SilentlyContinue
  }
}
# Wipe any per-source .o files left under src/.
$srcObjs = Get-ChildItem -LiteralPath (Join-Path $fixture 'src') -Filter '*.o' -ErrorAction SilentlyContinue
foreach ($obj in $srcObjs) {
  Remove-Item -LiteralPath $obj.FullName -Force -ErrorAction SilentlyContinue
}

# --- step 2: invoke `repro build` ---
$reproTarget = "$fixture#default"
$stdoutCapture = Join-Path $repoRoot 'build\validate-standard-provider-c-cpp-autotools-hello.stdout.txt'
$stderrCapture = Join-Path $repoRoot 'build\validate-standard-provider-c-cpp-autotools-hello.stderr.txt'
New-Item -ItemType Directory -Force -Path (Split-Path $stdoutCapture) | Out-Null

Write-Host "==> launching repro.exe build $reproTarget"
$proc = Start-Process -FilePath $reproExe -ArgumentList @(
    'build', $reproTarget,
    '--tool-provisioning=path',
    '--log=actions'
  ) -NoNewWindow -PassThru -Wait `
  -WorkingDirectory $repoRoot `
  -RedirectStandardOutput $stdoutCapture `
  -RedirectStandardError  $stderrCapture
$exitCode = $proc.ExitCode

Write-Host "--- repro exit code: $exitCode"
if (Test-Path $stdoutCapture) {
  Write-Host "--- repro stdout (last 25 lines):"
  Get-Content -LiteralPath $stdoutCapture -Tail 25 | ForEach-Object { Write-Host $_ }
}
if (Test-Path $stderrCapture) {
  $stderrTail = Get-Content -LiteralPath $stderrCapture -Tail 25
  if ($stderrTail) {
    Write-Host "--- repro stderr (last 25 lines):"
    foreach ($line in $stderrTail) { Write-Host $line }
  }
}

if ($exitCode -ne 0) {
  Write-Host "FAIL: repro build exited with code $exitCode"
  exit 1
}

# --- step 3: locate produced binary ---
# M28 per-source lift drops the executable under the per-member scratch
# dir (mirroring c-cpp-make's layout); the in-tree generated Makefile
# location used by the previous coarse-make surface is no longer
# authoritative.
$memberScratch = Join-Path $fixture (Join-Path '.repro\build' 'hello')
$candidates = @(
  Join-Path $memberScratch 'hello.exe'
  Join-Path $memberScratch 'hello'
  # Fallback: pre-M28 in-tree shape, in case a stale generated Makefile
  # still drops the binary at the fixture root.
  Join-Path $fixture 'hello.exe'
  Join-Path $fixture 'hello'
)
$producedBinary = $null
foreach ($candidate in $candidates) {
  if (Test-Path -LiteralPath $candidate) {
    $producedBinary = $candidate
    break
  }
}
if (-not $producedBinary) {
  Write-Host "FAIL: expected binary not found at any of:"
  foreach ($c in $candidates) { Write-Host "    $c" }
  Write-Host "--- contents of ${memberScratch}:"
  if (Test-Path -LiteralPath $memberScratch) {
    Get-ChildItem -LiteralPath $memberScratch | ForEach-Object { Write-Host "  $($_.Name)" }
  } else {
    Write-Host "  (directory does not exist)"
  }
  Write-Host "--- contents of $fixture (depth 1):"
  Get-ChildItem -LiteralPath $fixture | ForEach-Object { Write-Host "  $($_.Name)" }
  exit 1
}
Write-Host "produced binary: $producedBinary"
Write-Host "  size: $((Get-Item $producedBinary).Length) bytes"

# --- step 3b: M28 per-source lift assertion ---
# Verify the convention emitted a per-source compile artefact (the obj
# directory exists with at least one .o file) — i.e. the lift didn't
# silently fall back to a coarse ``make`` invocation.
$objDir = Join-Path $memberScratch 'obj'
if (Test-Path -LiteralPath $objDir) {
  $objs = @(Get-ChildItem -LiteralPath $objDir -Filter '*.o' -ErrorAction SilentlyContinue)
  if ($objs.Count -lt 1) {
    Write-Host "FAIL: M28 per-source lift expected >= 1 .o under $objDir; got 0"
    exit 1
  }
  Write-Host "M28 per-source lift artefacts:"
  foreach ($o in $objs) { Write-Host "  $($o.Name) ($($o.Length) bytes)" }
} else {
  Write-Host "FAIL: M28 per-source obj/ directory missing at $objDir"
  exit 1
}

# --- step 4: run and assert greeting ---
Write-Host "==> running $producedBinary"
$output = & $producedBinary 2>&1 | Out-String
$runExit = $LASTEXITCODE
Write-Host "--- binary exit code: $runExit"
Write-Host "--- binary stdout:"
Write-Host $output

if ($runExit -ne 0) {
  Write-Host "FAIL: produced binary exited with code $runExit"
  exit 1
}
if ($output -notmatch [regex]::Escape($expectedGreeting)) {
  Write-Host "FAIL: produced binary stdout does not contain '$expectedGreeting'"
  exit 1
}

Write-Host ""
Write-Host "PASS: c-cpp-autotools/hello-binary built via standard provider; greeting matched"
exit 0
