## Source-from-tarball pkgconf recipe — M9.N Batch D build-tool slice.
##
## pkgconf is the modern, ISC-licensed replacement for the original
## freedesktop ``pkg-config`` C utility: it reads ``.pc`` package
## metadata files under ``/usr/lib/pkgconfig/`` +
## ``/usr/share/pkgconfig/`` and synthesises the compiler + linker
## flags downstream consumers need. Every autotools- /
## meson- / cmake-driven recipe in ``recipes/packages/source/`` that
## probes a system library at configure time shells through pkgconf
## (or its symlinked ``pkg-config`` alias).
##
## ## Convention chosen — ``from-source-autotools``
##
## pkgconf is itself an autotools-driven project: the upstream
## release tarball ships a ``./configure`` script generated by
## autoconf + ``Makefile.in`` files generated by automake. The
## ``from-source-autotools`` convention (M9.L.2) claims the recipe
## via the populated ``configureFlags:`` channel.
##
## ## Why pkgconf matters for the v1 desktop story
##
## pkgconf is the package-metadata-probe utility every modern
## C / C++ build system relies on. Every autotools recipe that
## declares ``PKG_CHECK_MODULES`` shells out to pkgconf. Every meson
## recipe with a ``dependency('foo')`` call shells out to pkgconf.
## Every cmake recipe with ``find_package(PkgConfig REQUIRED)`` +
## ``pkg_check_modules(...)`` shells out to pkgconf.
## Bootstrapping pkgconf from source closes the
## ``uses: "pkg-config"`` toolchain floor every C / C++ recipe pins.
##
## ## sha256 strategy
##
## The fetch URL points at the upstream distfiles.ariadne.space
## release tarball ``pkgconf-2.3.0.tar.xz``. The sha256 was computed
## locally by downloading the tarball and running ``sha256sum`` over
## the bytes. nixpkgs's ``pkgs/by-name/li/libpkgconf/package.nix``
## pins pkgconf 2.5.1 (via the github.com archive URL with SRI
## ``sha256-eXIbrcrRmH3q2cNgnrSHerm1iCHAa9rLgk8siJfBHyo=``), NOT the
## 2.3.0 release the task brief requests, so the nixpkgs cross-check
## is deferred to the follow-up pass that lifts pkgconf to nixpkgs's
## 2.5 line.
##
## ## Version choice — 2.3.0 (per task brief)
##
## pkgconf releases are cut on github.com/pkgconf/pkgconf under
## tags of the form ``pkgconf-<X>.<Y>.<Z>``. 2.3.0 is the version
## the task brief requests; anything ``>=1.8`` covers every
## consumer's ``pkg-config`` pinning (pkgconf is API-compatible with
## the freedesktop pkg-config protocol).
##
## ## Artifacts
##
## pkgconf exposes one load-bearing CLI binary + one library on
## disk:
##
##   * ``pkgconf``    — ``$PREFIX/bin/pkgconf``, the CLI driver every
##                       configure / meson / cmake build system
##                       invokes (often via a ``pkg-config`` symlink
##                       added by the install body — symlink left as
##                       a follow-up).
##   * ``libpkgconf`` — ``$PREFIX/lib/libpkgconf.so``, the pkgconf
##                       internals exposed as a C library so other
##                       tooling (IDEs, build-system generators) can
##                       query ``.pc`` metadata without shelling out
##                       to the CLI.
##
## ## Configurables
##
## v1 ships THREE configure flags mirroring the modern-desktop
## baseline + the system-library-path discovery the brief specifies:
##
##   * ``--disable-static``                       — skip the static
##                                                   archive.
##   * ``--with-system-libdir=/lib:/usr/lib``     — set the default
##                                                   system library
##                                                   search path so
##                                                   pkgconf knows
##                                                   which RPATH-
##                                                   embedded library
##                                                   dirs are
##                                                   default-system.
##   * ``--with-system-includedir=/usr/include``  — set the default
##                                                   system include
##                                                   search path so
##                                                   pkgconf knows
##                                                   which ``-I`` dirs
##                                                   are default-
##                                                   system.

import repro_project_dsl

# ---------------------------------------------------------------------------
# Package declaration
# ---------------------------------------------------------------------------

package pkgconfSource:
  ## From-source pkgconf — M9.N Batch D build-tool slice.
  ##
  ## Tier-2b from-source-autotools convention consumer: the
  ## convention layer reads the ``fetch:`` block (registered via
  ## ``registeredFetchSpec``) and the ``configureFlags:`` block
  ## (registered via ``registeredBuildFlags`` on the ``"configure"``
  ## channel) and lowers them into fetch + configure + build + install
  ## BuildActions. Mixed-kind one-executable + one-library artifact
  ## recipe.

  versions:
    ## Pinned upstream tag. ``sourceUrl`` records the canonical
    ## distfiles.ariadne.space release tarball URL;
    ## ``sourceRepository`` points at the canonical github.com
    ## project tree.
    "2.3.0":
      sourceRevision = "pkgconf-2.3.0"
      sourceUrl = "https://distfiles.ariadne.space/pkgconf/pkgconf-2.3.0.tar.xz"
      sourceRepository = "https://github.com/pkgconf/pkgconf"

  fetch:
    ## Live upstream URL. The vendor/ directory is reserved for a
    ## follow-up vendoring pass.
    ##
    ## sha256 computed locally over the upstream
    ## distfiles.ariadne.space tarball; nixpkgs cross-check deferred
    ## because nixpkgs pins pkgconf 2.5.1 (not the 2.3.0 the task
    ## brief requests).
    url: "https://distfiles.ariadne.space/pkgconf/pkgconf-2.3.0.tar.xz"
    sha256: "3a9080ac51d03615e7c1910a0a2a8df08424892b5f13b0628a204d3fcce0ea8b"
    extractStrip: 1

  uses:
    ## autoconf generates the upstream ``configure`` script when the
    ## release tarball ships a stale ``configure.ac``.
    "autoconf"
    ## automake provides the ``Makefile.in`` templates.
    "automake"
    ## libtool drives the shared-library build for libpkgconf.
    "libtool"
    ## make is the build-system driver.
    "make"
    ## gcc is the host C toolchain — pkgconf is C99.
    "gcc >=11"

  configureFlags:
    ## Flag set per the task brief. Order is load-bearing: the
    ## ``./configure`` script evaluates options left-to-right.
    ##
    ## ``--disable-static`` skips the static archive of libpkgconf.
    ## ``--with-system-libdir=/lib:/usr/lib`` sets the default system
    ##  library search path.
    ## ``--with-system-includedir=/usr/include`` sets the default
    ##  system include search path.
    "--disable-static"
    "--with-system-libdir=/lib:/usr/lib"
    "--with-system-includedir=/usr/include"

  executable pkgconf:
    ## ``$PREFIX/bin/pkgconf`` — the CLI driver every configure /
    ## meson / cmake build system invokes. A ``pkg-config`` symlink
    ## is conventionally added by the install body but lives in a
    ## follow-up (the v1 stage-copy step only handles the direct
    ## binary). v1 records the artifact only.
    discard

  library libpkgconf:
    ## ``$PREFIX/lib/libpkgconf.so`` — the pkgconf internals exposed
    ## as a C library so other tooling can query ``.pc`` metadata
    ## without shelling out to the CLI. v1 records the artifact
    ## only.
    discard
