version = "0.1.0"
author = "Metacraft Labs"
description = "Reprobuild generic external-provider resource lane (Composable-Resource-Types slice 2)"
license = "MIT"
srcDir = "src"
requires "nim >= 2.2.0"
