# SPDX-License-Identifier: AGPL-3.0-or-later
# Pinned verbatim payload from CodeTracer commit
# 01068538c9986b40c8c8fbac28555eac7751ccc2, config.nims.
# Source: https://github.com/metacraft-labs/codetracer/blob/01068538c9986b40c8c8fbac28555eac7751ccc2/config.nims
#
# Keep every byte after this provenance header identical to the public source.
import std/[os, strutils]

proc addPathIfDir(path: string) =
  if path.len > 0 and dirExists(path):
    switch("path", path)

let repoRoot = currentSourcePath().parentDir()
let workspaceRoot = repoRoot.parentDir()

# Compiler switches previously in nim.cfg (deleted in dev when transitioning to
# reprobuild-managed config).  nim-serialization / nim-confutils require
# nimOldCaseObjects on Nim 2.x; the warning suppressions match the old nim.cfg.
switch("define", "nimOldCaseObjects")
switch("warning", "LockLevel:off")

# Paths that were previously in nim.cfg (deleted in dev when transitioning to
# reprobuild-managed config).  They are re-declared here so that both the legacy
# tup build and any nim invocations outside tup can still find these modules.
# When repro.paths is generated by reprobuild these will be redundant but harmless.
addPathIfDir(repoRoot / "src/frontend")       # kdom.nim and other JS-target stdlib shims
addPathIfDir(repoRoot / "libs/NimYAML")
addPathIfDir(repoRoot / "libs/asynctools")
addPathIfDir(repoRoot / "libs/nim")
addPathIfDir(repoRoot / "libs/nim-chronicles")
addPathIfDir(repoRoot / "libs/nim-faststreams")
addPathIfDir(repoRoot / "libs/nim-json-serialization")
addPathIfDir(repoRoot / "libs/nim-serialization")
addPathIfDir(repoRoot / "libs/nim-prompt")
addPathIfDir(repoRoot / "libs/nim-stew")
addPathIfDir(repoRoot / "libs/nim-unicodedb/src")
addPathIfDir(repoRoot / "libs/poly")
addPathIfDir(repoRoot / "libs/quicktest")
addPathIfDir(repoRoot / "libs/chronos")
addPathIfDir(repoRoot / "libs/parsetoml/src")
addPathIfDir(repoRoot / "libs/nim-result")
addPathIfDir(repoRoot / "libs/nim-confutils")
addPathIfDir(repoRoot / "libs/nimcrypto")
addPathIfDir(repoRoot / "libs/zip")
addPathIfDir(repoRoot / "libs/jsony/src")
addPathIfDir(repoRoot / "libs/nim-uuid4/src")
addPathIfDir(workspaceRoot / "isonim/src")
# Nim resolves later --path entries first. Prefer an explicit IsoNim source
# when validating a pinned dependency or an isolated worktree; normal
# workspace development still falls back to the sibling checkout above.
addPathIfDir(getEnv("ISONIM_SRC"))
addPathIfDir(workspaceRoot / "isonim-tui/src")
addPathIfDir(getEnv("ISONIM_TUI_SRC"))
addPathIfDir(workspaceRoot / "isonim-gpui/src")
addPathIfDir(getEnv("ISONIM_GPUI_SRC"))
addPathIfDir(workspaceRoot / "nim-termctl/src")
addPathIfDir(workspaceRoot / "nim-pty/src")
addPathIfDir(workspaceRoot / "nim-everywhere/src")
addPathIfDir(workspaceRoot / "nim-acp/src")
addPathIfDir(workspaceRoot / "nim-agent-harbor/src")
addPathIfDir(workspaceRoot / "nim-agents/src")

# Include paths dynamically generated by reprobuild
let reprobuildPathsFile = repoRoot / "reprobuild.paths"
if fileExists(reprobuildPathsFile):
  for line in readFile(reprobuildPathsFile).splitLines():
    let path = line.strip()
    addPathIfDir(path)

# The top-level `ct` entry point imports `src/ct_test/incremental_cli`.
# Nim loads config files from the main module's directory, not from imported
# module directories, so `src/ct_test/nim.cfg` is not seen when compiling `ct`.
# Mirror the sibling discovery used by the dev shell: the workspace sibling
# checkout, then an explicit source path that OVERRIDES it.  Nim searches later
# `--path` entries first, so each `getEnv` line has to come AFTER the sibling it
# is meant to override, the way the `ISONIM_SRC` pair above is written.  Ordered
# the other way the variable is inert whenever the sibling directory exists —
# which is the normal case in a workspace checkout — so a build pinned to a
# particular revision of a dependency silently compiles against the sibling's
# revision instead, with nothing in the output saying so.
addPathIfDir(workspaceRoot / "codetracer-trace-format-nim" / "src")
addPathIfDir(getEnv("CODETRACER_TRACE_FORMAT_NIM_SRC"))
addPathIfDir(workspaceRoot / "io-mon" / "src")
addPathIfDir(getEnv("IO_MON_SRC"))
addPathIfDir(workspaceRoot / "nim-shm-queue" / "src")
addPathIfDir(getEnv("SHM_QUEUE_SRC"))
# io-mon's writer now imports `shm_gset/transport` (the grow-only shared-memory
# set that backs io-mon's Linux dependency-capture channel), in addition to
# `shm_queue`. Thread nim-shm-gset onto the path the same way, or the `ct`
# compile fails with `cannot open file: shm_gset/transport`.
addPathIfDir(workspaceRoot / "nim-shm-gset" / "src")
addPathIfDir(getEnv("SHM_GSET_SRC"))
addPathIfDir(workspaceRoot / "nim-stackable-hooks" / "src")
addPathIfDir(getEnv("NIM_STACKABLE_HOOKS_SRC"))

const runquotaLibs = [
  "runquota_process",
  "runquota_core",
  "runquota_host",
  "runquota_host_macos",
  "runquota_host_linux",
  "runquota_host_windows",
  "runquota_codec",
  "runquota_protocol",
]

let runquotaSrc = getEnv("RUNQUOTA_SRC")
for lib in runquotaLibs:
  addPathIfDir(runquotaSrc / "libs" / lib / "src")
  addPathIfDir(workspaceRoot / "runquota" / "libs" / lib / "src")

# The trace-format Nim reader uses the `results` package >= 0.5. Keep this
# ahead of the repo-vendored `libs/nim-result` when available. CodeTracer code
# should import `results` directly; the deprecated singular `result` shim is not
# present in newer releases.
addPathIfDir(getEnv("CODETRACER_RESULTS_SRC"))
let pkgs2 = getHomeDir() / ".nimble" / "pkgs2"
if dirExists(pkgs2):
  var best = ""
  for kind, path in walkDir(pkgs2):
    if kind == pcDir and path.lastPathPart.startsWith("results-0.5"):
      if best.len == 0 or path.lastPathPart > best.lastPathPart:
        best = path
  addPathIfDir(best)

block:
  let nixCflags = getEnv("NIX_CFLAGS_COMPILE")
  if nixCflags.len > 0:
    let toks = nixCflags.splitWhitespace()
    var i = 0
    while i < toks.len:
      if toks[i] == "-isystem" and i + 1 < toks.len:
        let dir = toks[i + 1]
        if "zstd" in dir:
          switch("passC", "-isystem " & dir)
        i += 2
      else:
        i += 1

# >>> repro:project:codeTracer:repro-paths-bootstrap:v1 >>>
when withDir(thisDir(), system.fileExists("repro.paths")):
  include "repro.paths"
# <<< repro:project:codeTracer:repro-paths-bootstrap:v1 <<<

## Worktree-local nimcache: every Nim compile inside this checkout keeps its
## intermediate files (its nimcache) INSIDE this checkout.
##
## WHY.  Nim's default nimcache is `$XDG_CACHE_HOME/nim/<project>_d` (`_r` for
## -d:release; `%USERPROFILE%\nimcache\<project>_d` on Windows).  It is keyed by
## the project NAME only, and the generated file names inside it do not depend
## on the checkout path either.  So two worktrees or clones of this repository
## that build the same project at the same time write, compile and link each
## other's intermediate files.  Measured on 2026-09-26 in a sibling repository:
## ten concurrent builds of two worktrees that differed in a few places gave
## four correct binaries, two that exited 0 with the OTHER worktree's code
## linked in (one of them a mix of both), two compile failures on
## half-rewritten generated C and two link failures.
##
## WHAT.  `<checkout>/.nimcache/<directory of the main module, relative to the
## checkout>/<module name><suffix>`, where the suffix is Nim's own: `_check`
## for `nim check`, `_r` for -d:release or -d:danger, `_d` otherwise.  The
## directory is part of the key, so same-named modules in different directories
## no longer share a cache either.  Only the intermediates move; build outputs
## stay where they were.  An explicit `--nimcache:` on the command line still
## wins, because Nim applies the command line again after the config files.
## `nim js` and project-less invocations are left alone.
##
## HOW IT IS PICKED UP.  Nim runs the `config.nims` of every PARENT directory of
## the compiled module, outermost first, then the one in the module's own
## directory.  So this file applies to every compile under this checkout,
## `just`, the CI lanes, CI and a bare `nim c` alike, whatever the working directory.
## `--skipParentCfg` switches it off for modules below the checkout root, so a
## recipe that passes that flag must name its own checkout-local `--nimcache:`.
## `ci/lib/run-nim-test-lane.sh` keeps naming its own per-checkout cache under
## /tmp/ct-nim-cache/<checkout>-<checksum of its path>, which still wins.  The one
## `--skipParentCfg` use (`ci/lib/system-io-surface.sh`) is a project-less `nim dump`.
## `src/common/nimcache_is_worktree_local_test.nim` checks the layout, and fails if the
## config is bypassed; its `--skipParentCfg` negative control proves the probe
## can see a shared cache at all.
##
## WINDOWS.  Nim turns the `/` below into `\` on a Windows host.  The layout adds
## `\.nimcache\<module dir>\<module>_d\` in front of Nim's own object file names,
## so keep the checkout root short (about 80 characters) to stay inside MAX_PATH.
block worktreeLocalNimcache:
  var project = projectName()
  if project.len > 4 and project[^4 .. ^1] == ".nim":
    project = project[0 ..< ^4]
  # No project (`nim dump` with no file): nothing to place.  The JS backend
  # has its own convention (a cache next to its output).  `nim e` never
  # generates C, so it never creates the directory.
  if project.len == 0 or getCommand() == "js":
    break worktreeLocalNimcache

  # Plain "/" joins, NOT std/os `/`: NimScript's `/` follows the TARGET OS,
  # so a `--os:windows` cross-compile on a POSIX host would get backslashes.
  let root = thisDir()
  let projDir = projectDir()
  var rel = ""
  if projDir.len >= root.len and projDir[0 ..< root.len] == root:
    rel = projDir[root.len .. ^1]
  else:
    # Cannot happen for a project Nim found this file for (this file is read
    # because it sits in a parent of the project directory).  Stay inside
    # the checkout and stay unique anyway.
    rel = "_outside/"
    for c in projDir:
      rel.add(if c in {'/', '\\', ':'}: '_' else: c)
  while rel.len > 0 and rel[0] in {'/', '\\'}:
    rel = rel[1 .. ^1]

  let suffix =
    if getCommand() == "check": "_check"
    elif defined(release) or defined(danger): "_r"
    else: "_d"
  var cacheDir = root & "/.nimcache"
  if rel.len > 0:
    cacheDir.add("/" & rel)
  switch("nimcache", cacheDir & "/" & project & suffix)
