# SPDX-License-Identifier: AGPL-3.0-or-later
# Pinned verbatim payload from CodeTracer commit
# 602e7bb728311c230c9a42fa7fd8aab546b6467a, config.nims.
# Source: https://github.com/metacraft-labs/codetracer/blob/602e7bb728311c230c9a42fa7fd8aab546b6467a/config.nims
#
# Keep every byte after this provenance header identical to the public source.
import std/[os, strutils]

proc addPathIfDir(path: string) =
  if path.len > 0 and dirExists(path):
    switch("path", path)

let repoRoot = currentSourcePath().parentDir()
let workspaceRoot = repoRoot.parentDir()

# Compiler switches previously in nim.cfg (deleted in dev when transitioning to
# reprobuild-managed config).  nim-serialization / nim-confutils require
# nimOldCaseObjects on Nim 2.x; the warning suppressions match the old nim.cfg.
switch("define", "nimOldCaseObjects")
switch("warning", "LockLevel:off")

# Paths that were previously in nim.cfg (deleted in dev when transitioning to
# reprobuild-managed config).  They are re-declared here so that both the legacy
# tup build and any nim invocations outside tup can still find these modules.
# When repro.paths is generated by reprobuild these will be redundant but harmless.
addPathIfDir(repoRoot / "src/frontend")       # kdom.nim and other JS-target stdlib shims
addPathIfDir(repoRoot / "libs/NimYAML")
addPathIfDir(repoRoot / "libs/asynctools")
addPathIfDir(repoRoot / "libs/nim")
addPathIfDir(repoRoot / "libs/nim-chronicles")
addPathIfDir(repoRoot / "libs/nim-faststreams")
addPathIfDir(repoRoot / "libs/nim-json-serialization")
addPathIfDir(repoRoot / "libs/nim-serialization")
addPathIfDir(repoRoot / "libs/nim-prompt")
addPathIfDir(repoRoot / "libs/nim-stew")
addPathIfDir(repoRoot / "libs/nim-unicodedb/src")
addPathIfDir(repoRoot / "libs/poly")
addPathIfDir(repoRoot / "libs/quicktest")
addPathIfDir(repoRoot / "libs/chronos")
addPathIfDir(repoRoot / "libs/parsetoml/src")
addPathIfDir(repoRoot / "libs/nim-result")
addPathIfDir(repoRoot / "libs/nim-confutils")
addPathIfDir(repoRoot / "libs/nimcrypto")
addPathIfDir(repoRoot / "libs/zip")
addPathIfDir(repoRoot / "libs/jsony/src")
addPathIfDir(repoRoot / "libs/nim-uuid4/src")
addPathIfDir(workspaceRoot / "isonim/src")
# Nim resolves later --path entries first. Prefer an explicit IsoNim source
# when validating a pinned dependency or an isolated worktree; normal
# workspace development still falls back to the sibling checkout above.
addPathIfDir(getEnv("ISONIM_SRC"))
addPathIfDir(workspaceRoot / "isonim-tui/src")
addPathIfDir(workspaceRoot / "isonim-gpui/src")
addPathIfDir(workspaceRoot / "nim-termctl/src")
addPathIfDir(workspaceRoot / "nim-pty/src")
addPathIfDir(workspaceRoot / "nim-everywhere/src")
addPathIfDir(workspaceRoot / "nim-acp/src")
addPathIfDir(workspaceRoot / "nim-agent-harbor/src")
addPathIfDir(workspaceRoot / "nim-agents/src")

# Include paths dynamically generated by reprobuild
let reprobuildPathsFile = repoRoot / "reprobuild.paths"
if fileExists(reprobuildPathsFile):
  for line in readFile(reprobuildPathsFile).splitLines():
    let path = line.strip()
    addPathIfDir(path)

# The top-level `ct` entry point imports `src/ct_test/incremental_cli`.
# Nim loads config files from the main module's directory, not from imported
# module directories, so `src/ct_test/nim.cfg` is not seen when compiling `ct`.
# Mirror the sibling discovery used by the dev shell: prefer an explicit source
# path, then the normal workspace sibling checkout.
addPathIfDir(getEnv("CODETRACER_TRACE_FORMAT_NIM_SRC"))
addPathIfDir(workspaceRoot / "codetracer-trace-format-nim" / "src")
addPathIfDir(getEnv("IO_MON_SRC"))
addPathIfDir(workspaceRoot / "io-mon" / "src")
addPathIfDir(getEnv("SHM_QUEUE_SRC"))
addPathIfDir(workspaceRoot / "nim-shm-queue" / "src")
# io-mon's writer now imports `shm_gset/transport` (the grow-only shared-memory
# set that backs io-mon's Linux dependency-capture channel), in addition to
# `shm_queue`. Thread nim-shm-gset onto the path the same way, or the `ct`
# compile fails with `cannot open file: shm_gset/transport`.
addPathIfDir(getEnv("SHM_GSET_SRC"))
addPathIfDir(workspaceRoot / "nim-shm-gset" / "src")
addPathIfDir(getEnv("NIM_STACKABLE_HOOKS_SRC"))
addPathIfDir(workspaceRoot / "nim-stackable-hooks" / "src")

const runquotaLibs = [
  "runquota_process",
  "runquota_core",
  "runquota_host",
  "runquota_host_macos",
  "runquota_host_linux",
  "runquota_host_windows",
  "runquota_codec",
  "runquota_protocol",
]

let runquotaSrc = getEnv("RUNQUOTA_SRC")
for lib in runquotaLibs:
  addPathIfDir(runquotaSrc / "libs" / lib / "src")
  addPathIfDir(workspaceRoot / "runquota" / "libs" / lib / "src")

# The trace-format Nim reader uses the `results` package >= 0.5. Keep this
# ahead of the repo-vendored `libs/nim-result` when available. CodeTracer code
# should import `results` directly; the deprecated singular `result` shim is not
# present in newer releases.
addPathIfDir(getEnv("CODETRACER_RESULTS_SRC"))
let pkgs2 = getHomeDir() / ".nimble" / "pkgs2"
if dirExists(pkgs2):
  var best = ""
  for kind, path in walkDir(pkgs2):
    if kind == pcDir and path.lastPathPart.startsWith("results-0.5"):
      if best.len == 0 or path.lastPathPart > best.lastPathPart:
        best = path
  addPathIfDir(best)

block:
  let nixCflags = getEnv("NIX_CFLAGS_COMPILE")
  if nixCflags.len > 0:
    let toks = nixCflags.splitWhitespace()
    var i = 0
    while i < toks.len:
      if toks[i] == "-isystem" and i + 1 < toks.len:
        let dir = toks[i + 1]
        if "zstd" in dir:
          switch("passC", "-isystem " & dir)
        i += 2
      else:
        i += 1

# >>> repro:project:codeTracer:repro-paths-bootstrap:v1 >>>
when withDir(thisDir(), system.fileExists("repro.paths")):
  include "repro.paths"
# <<< repro:project:codeTracer:repro-paths-bootstrap:v1 <<<
