# AUTO-GENERATED by scripts/generate_test_edges.nim — do not edit by hand.
# Regenerate with: nim r scripts/generate_test_edges.nim
#
# Suite-Modernization M4 shared pure-unit binary. Each import
# below contributes its module's ``suite``/``test`` cases to
# this one binary; every case stays individually addressable
# through ``--run "suite::test"`` because the protocol's case
# names are unique suite-wide and never depended on the binary
# boundary. Membership is declared in the generator's
# ``PureUnitBundles`` table; see the rationale there before
# adding a member.

import "../../libs/repro_solver/tests/t_clingo_smoke"
import "../../libs/repro_solver/tests/t_cross_package_propagates"
import "../../libs/repro_solver/tests/t_explainer_chosen_basic"
import "../../libs/repro_solver/tests/t_explainer_chosen_cross_package"
import "../../libs/repro_solver/tests/t_explainer_chosen_with_constraints"
import "../../libs/repro_solver/tests/t_explainer_chosen_with_override"
import "../../libs/repro_solver/tests/t_explainer_unsat_basic"
import "../../libs/repro_solver/tests/t_explainer_unsat_version_range"
import "../../libs/repro_solver/tests/t_semver_range_parsing"
import "../../libs/repro_solver/tests/t_semver_satisfies"
import "../../libs/repro_solver/tests/t_solve_unified_end_to_end"
import "../../libs/repro_solver/tests/t_solve_unified_unsatisfiable"
import "../../libs/repro_solver/tests/t_solve_variants_end_to_end"
import "../../libs/repro_solver/tests/t_solve_variants_unsatisfiable"
import "../../libs/repro_solver/tests/t_variant_encoder_bool_universe"
import "../../libs/repro_solver/tests/t_variant_encoder_conflicts"
import "../../libs/repro_solver/tests/t_variant_encoder_enum_universe"
import "../../libs/repro_solver/tests/t_variant_encoder_priorities"
import "../../libs/repro_solver/tests/t_variant_encoder_propagates"
import "../../libs/repro_solver/tests/t_variant_encoder_requires"
import "../../libs/repro_solver/tests/t_version_encoder_conditional_deps"
import "../../libs/repro_solver/tests/t_version_encoder_constraints"
import "../../libs/repro_solver/tests/t_version_encoder_transitive"
import "../../libs/repro_solver/tests/t_version_encoder_universe"
