# AUTO-GENERATED by scripts/generate_test_edges.nim — do not edit by hand.
# Regenerate with: nim r scripts/generate_test_edges.nim
#
# Suite-Modernization M4 shared pure-unit binary. Each import
# below contributes its module's ``suite``/``test`` cases to
# this one binary; every case stays individually addressable
# through ``--run "suite::test"`` because the protocol's case
# names are unique suite-wide and never depended on the binary
# boundary. Membership is declared in the generator's
# ``PureUnitBundles`` table; see the rationale there before
# adding a member.

import "../../libs/repro_peer_cache/tests/t_peer_cache_advertise_v2_codec_round_trip"
import "../../libs/repro_peer_cache/tests/t_peer_cache_bearssl_ecdsa_smoke"
import "../../libs/repro_peer_cache/tests/t_peer_cache_cert_validity_window_enforced"
import "../../libs/repro_peer_cache/tests/t_peer_cache_codec_frame_round_trip"
import "../../libs/repro_peer_cache/tests/t_peer_cache_codec_version_mismatch_rejected"
import "../../libs/repro_peer_cache/tests/t_peer_cache_cuckoo_filter_delete_round_trip"
import "../../libs/repro_peer_cache/tests/t_peer_cache_cuckoo_filter_false_positive_rate"
import "../../libs/repro_peer_cache/tests/t_peer_cache_ecdsa_sign_verify_round_trip"
import "../../libs/repro_peer_cache/tests/t_peer_cache_ecdsa_trust_anchor_file_format"
import "../../libs/repro_peer_cache/tests/t_peer_cache_event_stream_jsonl_round_trip"
import "../../libs/repro_peer_cache/tests/t_peer_cache_self_signed_cert_round_trip"
import "../../libs/repro_peer_cache/tests/t_peer_cache_tier2_central_fallthrough"
import "../../libs/repro_peer_cache/tests/t_peer_cache_tier2_eviction_policy"
