# AUTO-GENERATED by scripts/generate_test_edges.nim — do not edit by hand.
# Regenerate with: nim r scripts/generate_test_edges.nim
#
# Suite-Modernization M4 shared pure-unit binary. Each import
# below contributes its module's ``suite``/``test`` cases to
# this one binary; every case stays individually addressable
# through ``--run "suite::test"`` because the protocol's case
# names are unique suite-wide and never depended on the binary
# boundary. Membership is declared in the generator's
# ``PureUnitBundles`` table; see the rationale there before
# adding a member.

import "../../libs/repro_core/tests/t_convention_attribution"
import "../../libs/repro_core/tests/t_edge_determinism_vocabulary"
import "../../libs/repro_core/tests/t_smoke_repro_core"
