version = "0.1.0"
author = "Metacraft Labs"
description = "Reprobuild signed desired-state manifest pull agent (Windows-Runner-Binary-Cache-Deploy M5)"
license = "MIT"
srcDir = "src"
requires "nim >= 2.2.0"
requires "repro_peer_cache"
requires "repro_profile"
requires "repro_infra"
requires "repro_profile_compile"
requires "repro_elevation"
