## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: gh-releases:alire-project/alire
## Versions (newest-first): 2.1.1

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let alireCatalog* = @[
  VersionedProvisioning(
    version: "2.1.1",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin/alr.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/alire-project/alire/releases/download/v2.1.1/alr-2.1.1-bin-x86_64-windows.zip", sha256: "863013b1f94da6f3b7d0d5a74022ac3370424eeea9a470ebdb33d188d61b9125", sha512: "", sha1: "", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
