## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 3.16.1.0
##
## **M9.5 merge note (hand-edited):** added a ``(pcX86_64, poLinux)``
## platform slice manually (cabal ships on ``downloads.haskell.org``,
## not GitHub Releases — the M7 gh-releases harvester doesn't apply).
## URL pattern: ``cabal-install-<ver>-x86_64-linux-deb10.tar.xz``;
## sha256 lifted from upstream's ``SHA256SUMS``. The Debian 10 build
## is the LOWEST glibc floor cabal 3.16.1.0 publishes (glibc 2.28 /
## Debian Buster). M9.5 spec's glibc-2.17 honest-scope target is NOT
## met for cabal — operators on RHEL 7 / Ubuntu 14.04 era distros
## should fall through to cakNix; documented here for the operator's
## awareness. archive_format stays afTarXz; cabal ships a single flat
## ``cabal`` binary inside the tarball (no inner dir).

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let cabalCatalog* = @[
  VersionedProvisioning(
    version: "3.16.1.0",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["cabal.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://downloads.haskell.org/~cabal/cabal-install-latest/cabal-install-3.16.1.0-x86_64-windows.zip", sha256: "7f760fd4afde9bf3f592d71055c1ad6068d297c45244a3f71a5d7cad484d5afd", sha512: "", extract_path: ""),
      # M9.5: Linux x86_64 slice. Debian 10 build (glibc 2.28 floor —
      # higher than the spec's 2.17 target; documented as a known gap
      # in the merge note above). afTarXz (vs. Windows afZip); the
      # ``cabal`` binary lives at the tarball root (no inner dir).
      PlatformBinary(cpu: pcX86_64, os: poLinux, url: "https://downloads.haskell.org/~cabal/cabal-install-3.16.1.0/cabal-install-3.16.1.0-x86_64-linux-deb10.tar.xz", sha256: "f8bbdae03898a072fcdfbf3abc4b067587afa26222ac47821e78611ca0caa40f", sha512: "", sha1: "", extract_path: "", archive_format_override: afTarXz, has_archive_format_override: true, bin_relpath_override: @["cabal"])
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
