## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 3.16.1.0

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let cabalCatalog* = @[
  VersionedProvisioning(
    version: "3.16.1.0",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["cabal.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://downloads.haskell.org/~cabal/cabal-install-latest/cabal-install-3.16.1.0-x86_64-windows.zip", sha256: "7f760fd4afde9bf3f592d71055c1ad6068d297c45244a3f71a5d7cad484d5afd", sha512: "", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
