## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 4.3.3
##
## **M9.5 merge note (hand-edited):** added a ``(pcX86_64, poLinux)``
## platform slice harvested via ``--source gh-releases:Kitware/CMake
## --asset-pattern 'cmake-4\.3\.3-linux-x86_64\.tar\.gz' --platform-os
## linux``. The Linux tarball is ``afTarGz`` (vs. ``afZip``) and the
## binaries live under ``bin/cmake`` (no ``.exe``); the windows-only
## ``cmcldeps.exe`` + ``cmake-gui.exe`` are dropped from the override.
## Upstream CMake's Linux build targets glibc 2.17 (RHEL 7 / CentOS 7
## floor) — matches the M9.5 spec's glibc-2.17 honest-scope target.

import std/tables
import repro_project_dsl
import repro_dsl_stdlib/packages_schema
export packages_schema

# ---------------------------------------------------------------------------
# DSL-port M9.R.2 — hand-authored ``package cmake:`` DSL block carrying
# provisioning shape + the typed Layer-3 CLI surface so recipes can write
# ``cmake.configure(srcDir = ..., buildDir = ..., generator = "Ninja",
# cacheVars = @["CMAKE_BUILD_TYPE=Release"])`` instead of an inline
# ``sh.call(["cmake", "-S", ...])``.
#
# Positional / flag shape mirrors the canonical CMake CLI:
#
#   * ``cmake -S <srcDir> -B <buildDir> -G <gen> -D<var>=<val>`` for
#     configure.
#   * ``cmake --build <buildDir> --target <name> --config <cfg>`` for
#     build.
#   * ``cmake --install <buildDir> --prefix <prefix> --component <comp>``
#     for install.
#
# Cross-link: see ``CMake-Reprobuild-Generator.md`` for the longer-term
# CMake → reprobuild generator integration.
# ---------------------------------------------------------------------------

package cmake:
  provisioning:
    nixPackage "nixpkgs#cmake", executablePath = "bin/cmake",
      nixpkgsRev = "addf7cf5f383a3101ecfba091b98d0a1263dc9b8",
      nixpkgsNarHash = "sha256-hM20uyap1a0M9d344I692r+ik4gTMyj60cQWO+hAYP8="
    scoopApp(bucket = "main", app = "cmake",
      preferredVersion = ">=3.20", executablePath = "bin/cmake.exe",
      requiresExecutionProfileChecksum = false)
    tarball url = "https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-windows-x86_64.zip",
      sha256 = "935ade9e5e8723583c07f44c5592cea2a1c8f65c56ca7e07b34c025c880e0bd6",
      archiveType = "zip",
      stripComponents = 1,
      executablePath = "bin/cmake.exe",
      packageId = "cmake@4.3.3",
      cpu = "x86_64",
      os = "windows",
      lockIdentity = "tarball:cmake@4.3.3:sha256:935ade9e5e8723583c07f44c5592cea2a1c8f65c56ca7e07b34c025c880e0bd6"
    tarball url = "https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-linux-x86_64.tar.gz",
      sha256 = "927b2368a946c37269c3a66225ab00544e756459cdd0b5d0da438694fb9ff802",
      archiveType = "tar.gz",
      stripComponents = 1,
      executablePath = "bin/cmake",
      packageId = "cmake@4.3.3-linux",
      cpu = "x86_64",
      os = "linux",
      lockIdentity = "tarball:cmake@4.3.3-linux:sha256:927b2368a946c37269c3a66225ab00544e756459cdd0b5d0da438694fb9ff802"

  executable cmakeBin:
    cli:
      dependencyPolicy automaticMonitor

      subcmd "configure":
        flag srcDir is string,
          alias = "-S",
          format = separate,
          role = input
        flag buildDir is string,
          alias = "-B",
          format = separate,
          role = output
        flag generator is string,
          alias = "-G",
          format = separate
        flag cacheVars is seq[string],
          alias = "-D",
          format = concat,
          repeated = true
        flag toolchainFile is string,
          alias = "--toolchain=",
          format = concat
        flag config is string,
          alias = "--config=",
          format = concat

        outputs buildDir

      subcmd "build":
        flag buildDir is string,
          alias = "--build",
          format = separate,
          role = input,
          required = true
        flag target is string,
          alias = "--target",
          format = separate
        flag config is string,
          alias = "--config",
          format = separate
        flag jobs is int,
          alias = "-j",
          format = separate
        flag parallel is int,
          alias = "--parallel",
          format = separate

      subcmd "install":
        flag buildDir is string,
          alias = "--install",
          format = separate,
          role = input,
          required = true
        flag prefix is string,
          alias = "--prefix",
          format = separate,
          role = output
        flag component is string,
          alias = "--component",
          format = separate
        flag config is string,
          alias = "--config",
          format = separate

let cmakeCatalog* = @[
  VersionedProvisioning(
    version: "4.3.3",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin\\cmake.exe", "bin\\cmcldeps.exe", "bin\\cpack.exe", "bin\\ctest.exe", "bin\\cmake-gui.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-windows-x86_64.zip", sha256: "935ade9e5e8723583c07f44c5592cea2a1c8f65c56ca7e07b34c025c880e0bd6", sha512: "", extract_path: "cmake-4.3.3-windows-x86_64"),
      PlatformBinary(cpu: pcAArch64, os: poWindows, url: "https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-windows-arm64.zip", sha256: "db6e902b5ba6a08d0abed136763c4bd95adda17e882d659c0f5d14fe158f7395", sha512: "", extract_path: "cmake-4.3.3-windows-arm64"),
      # M9.5: Linux x86_64 slice. afTarGz (vs. Windows afZip) +
      # ``bin/<tool>`` no-suffix binaries; ``cmcldeps`` + ``cmake-gui``
      # are windows-only and dropped from the override.
      PlatformBinary(cpu: pcX86_64, os: poLinux, url: "https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-linux-x86_64.tar.gz", sha256: "927b2368a946c37269c3a66225ab00544e756459cdd0b5d0da438694fb9ff802", sha512: "", sha1: "", extract_path: "cmake-4.3.3-linux-x86_64", archive_format_override: afTarGz, has_archive_format_override: true, bin_relpath_override: @["bin/cmake", "bin/cpack", "bin/ctest"])
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
