## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 2.10.0

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let composerCatalog* = @[
  VersionedProvisioning(
    version: "2.10.0",
    archive_format: afRaw,
    install_method: imExtract,
    bin_relpath: @["composer.ps1"],
    platforms: @[
      PlatformBinary(cpu: pcAny, os: poWindows, url: "https://getcomposer.org/download/2.10.0/composer.phar", sha256: "a346538851988ead111d11e3cbd7d372eeba44abd0af412e09890d3c21ea6c31", sha512: "", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"COMPOSER_CACHE_DIR": "$persist_dir\\cache", "COMPOSER_HOME": "$persist_dir\\home"}.toTable())
]
