## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 1.20.2

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let crystalCatalog* = @[
  VersionedProvisioning(
    version: "1.20.2",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["crystal.exe", "shards.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/crystal-lang/crystal/releases/download/1.20.2/crystal-1.20.2-windows-x86_64-msvc-unsupported.zip", sha256: "15a41963373cc481f68dcc9a968bb11d36ee9254f1515eccee86d02223f8f82e", sha512: "", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
