## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 1.19.5

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let elixirCatalog* = @[
  VersionedProvisioning(
    version: "1.19.5",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin/elixir.bat", "bin/iex.bat", "bin/mix.bat", "bin/elixirc.bat"],
    platforms: @[
      PlatformBinary(cpu: pcAny, os: poWindows, url: "https://builds.hex.pm/builds/elixir/v1.19.5.zip", sha256: "db6701f2232be899190ecb8dbf280104fe2434675093c2b5935e563a08052afb", sha512: "", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
