## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 28.5

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let erlangCatalog* = @[
  VersionedProvisioning(
    version: "28.5",
    archive_format: afSevenZip,
    install_method: imInstallerSilent,
    bin_relpath: @["bin\\erl.exe", "bin\\erlc.exe", "bin\\escript.exe", "bin\\werl.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/erlang/otp/releases/download/OTP-28.5/otp_win64_28.5.exe#/dl.7z", sha256: "46f56351e2e67865c6aaff83bcd0a7d97d73bea643a0531774dd9ba8fbee7dc0", sha512: "", extract_path: "")
    ],
    installer_args: @["-sasl"],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"ERLANG_HOME": "${prefix}"}.toTable())
]
