## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 28.5
##
## **M3 LIVE-smoke status (Realize-Closure-And-Catalog-Expansion spec).**
## The M3 spec text predicted erlang would unblock via the basic
## ``afSevenZip`` dispatch ("7z auto-detects NSIS-wrapped 7z"). The
## live smoke against the upstream ``otp_win64_28.5.exe`` artifact
## refuted that prediction — 7z reports ``Cannot open the file as
## [7z] archive`` on the downloaded bytes. The upstream installer is
## a *true* NSIS installer (not a 7z-with-NSIS-stub the way Git-for-
## Windows ships); the ``#/dl.7z`` Scoop rename is metadata-only and
## does NOT change the file's on-disk structure.
##
## **M4 amendment**: install_method flipped to ``imInstallerNsisBundle``
## so the cakBuiltin realize loop dispatches through the M4 dark.exe
## (Burn outer unwrap) + 7z (fallback) + lessmsi (per-MSI extract)
## sandwich. **LIVE smoke status: STILL BLOCKED.** dark.exe rejects
## the OTP installer with ``DARK0339: Stub executable does not contain
## a .wixburn data section.`` (i.e. OTP is NOT a Burn bundle — it's a
## bona-fide NSIS installer using the modern NSIS installer format that
## the standalone 7zr.exe carried by ``packages/sevenzip.nim`` does NOT
## handle (7zr is the "Reduced 7z" — supports only .7z and .lzma;
## requires the FULL 7-Zip distribution to crack NSIS).
##
## **Root cause**: the M3 ``packages/sevenzip.nim`` chose the
## standalone ``7zr.exe`` for bootstrap simplicity (no MSI dep).
## The full 7-Zip ships as an MSI on Windows main — which now (post-M4)
## CAN be extracted via lessmsi but requires re-harvesting the
## sevenzip catalog with ``afInstallerMsi + imInstallerMsi``.
##
## **M8 (Realize-Closure-And-Catalog-Expansion spec) status update:**
## the M8 sevenzip re-harvest is DONE — ``packages/sevenzip.nim`` now
## ships the full 7-Zip 26.01 distribution. LIVE-validated (manual
## probe): ``7z.exe x otp_win64_28.5.exe`` extracts the OTP payload
## cleanly (detects the file as PE/NSIS, dumps the inner tree with
## ``erts-<ver>/bin/erl.exe`` runnable end-to-end — ``erl -version``
## returns the BEAM emulator version). **The 7z-capability blocker
## the M3/M4 docstring above predicted is GONE.**
##
## **New blocker** (folded into M11): the current catalog
## ``install_method = imInstallerNsisBundle`` dispatches through the M4
## Burn/MSI sandwich (``extractNsisMsiBundle`` requires dark.exe to
## crack the .wixburn section). The OTP installer is a bona-fide NSIS
## installer with NO Burn outer, so dark.exe rejects it (``DARK0339:
## Stub executable does not contain a .wixburn data section``). The
## right path is direct ``extract7z`` against the NSIS .exe — exactly
## what the M3 ``imExtract + afSevenZip`` code path does, but the
## current schema blocks ``imExtract + afInstallerNsis`` at compile
## time (see ``builtin_adapter.nim:2575``: ``imExtract is incompatible
## with installer archive_format``). Unblocking erlang in M11 needs
## EITHER:
##   * a new ``imInstallerNsis`` (plain) install method that dispatches
##     to ``extract7z`` directly (1-day add — three lines in the realize
##     loop + the enum + a tiny test);
##   * OR a schema relaxation that allows ``imExtract + afInstallerNsis``
##     when the catalog explicitly opts in (more controversial — the
##     current restriction is a useful guard).
## AND the catalog's ``bin_relpath`` must change from
## ``bin\\erl.exe`` to ``erts-<ver>\\bin\\erl.exe`` because OTP places
## its runtime under the ``erts-<ver>`` subdir, not a flat ``bin/``.
## A future re-harvest with ``--version-extract`` capturing the ``erts``
## version is also possible, but the simpler fix is per-version
## hand-edited bin_relpath in this file (OTP's erts version tracks
## OTP-major; for OTP-28.x it is erts-16.x).
##
## **Honest scope continued**: the OTP installer historically writes
## a per-user ``vcredist*`` redistributable side-effect and a
## ``post_install`` ``Remove-Item $PLUGINSDIR vcredist*`` cleanup;
## neither would be exercised by cakBuiltin's NSIS-bundle hook even
## if the outer extraction worked (the M4 hook materializes the file
## tree only; vcredist would need a separate cakBuiltin
## ``vcredist2022`` catalog entry per the Scoop ``suggest`` block).

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let erlangCatalog* = @[
  VersionedProvisioning(
    version: "28.5",
    archive_format: afInstallerNsis,
    install_method: imInstallerNsisBundle,
    bin_relpath: @["bin\\erl.exe", "bin\\erlc.exe", "bin\\escript.exe", "bin\\werl.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/erlang/otp/releases/download/OTP-28.5/otp_win64_28.5.exe", sha256: "46f56351e2e67865c6aaff83bcd0a7d97d73bea643a0531774dd9ba8fbee7dc0", sha512: "", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"ERLANG_HOME": "${prefix}"}.toTable())
]
