## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 28.5
##
## **M3 LIVE-smoke status (Realize-Closure-And-Catalog-Expansion spec).**
## The M3 spec text predicted erlang would unblock via the basic
## ``afSevenZip`` dispatch ("7z auto-detects NSIS-wrapped 7z"). The
## live smoke against the upstream ``otp_win64_28.5.exe`` artifact
## refutes that prediction — 7z reports ``Cannot open the file as
## [7z] archive`` on the downloaded bytes. The upstream installer is
## a *true* NSIS installer (not a 7z-with-NSIS-stub the way Git-for-
## Windows ships); the ``#/dl.7z`` Scoop rename is metadata-only and
## does NOT change the file's on-disk structure. erlang therefore
## requires either:
##   (a) the imInstallerSilent path actually invoking the NSIS
##       installer's ``Install.exe`` interactively (broken in cakBuiltin
##       because the installer needs the un-extracted upstream bytes
##       directly — out of M3 scope), OR
##   (b) the M4 NSIS+MSI realize hook to drive ``installer.exe /S
##       /D=<prefix>`` against the downloaded EXE.
##
## **Catalog reflects upstream truth.** The catalog below records the
## upstream manifest's installer block (install_method =
## imInstallerSilent) so the cakBuiltin realize loop fails loudly with
## an extraction-failed error rather than silently mis-classifying the
## file. M4's installer-silent hook will pick this up cleanly.
## **erlang remains BLOCKED on M4 — NOT a complete M3 unblock.**

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let erlangCatalog* = @[
  VersionedProvisioning(
    version: "28.5",
    archive_format: afSevenZip,
    install_method: imInstallerSilent,
    bin_relpath: @["bin\\erl.exe", "bin\\erlc.exe", "bin\\escript.exe", "bin\\werl.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/erlang/otp/releases/download/OTP-28.5/otp_win64_28.5.exe#/dl.7z", sha256: "46f56351e2e67865c6aaff83bcd0a7d97d73bea643a0531774dd9ba8fbee7dc0", sha512: "", extract_path: "")
    ],
    installer_args: @["-sasl"],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"ERLANG_HOME": "${prefix}"}.toTable())
]
