## ``fpc`` — Free Pascal compiler (M1 sha1 weak-hash provenance note,
## hand-edited; the catalog body below is auto-generated).
##
## **Why sha1.** The upstream Scoop manifest for ``freepascal`` ships
## only a sha1 digest for fpc 3.2.2. The M63 schema (sha256/sha512
## only) rejected this slice and Pascal Phase-2 graduation sat
## BLOCKED-NO-CATALOG in the M71 closing table. M1 of the
## Realize-Closure-And-Catalog-Expansion campaign extended the schema
## to accept sha1 with a deprecation warning, unblocking this harvest.
##
## **M4 amendment (Realize-Closure-And-Catalog-Expansion spec)**: the
## ``install_method`` flipped from ``imExtract`` (M1's placeholder
## because the M1 schema half landed without a working realize path)
## to ``imInstallerInnoSetup`` so the cakBuiltin realize loop
## dispatches through the M4 innounp.exe extractor. The Scoop manifest
## carries ``"innosetup": true`` (with NO ``installer:`` block — exactly
## the shape M1's Outstanding Task note flagged as needing M4); the M4
## harvester detects this marker and emits the right install_method.
## After M4 lands, the M59 pascal-fpc Phase-2 partial graduates to
## GRADUATE-PASS per M11.
##
## **Provenance.** The sha1 digest below
## (``c3fc24290da7349e4fba763eaadd2a5bec07bfa3``) is verbatim from
## ScoopInstaller/Main's ``bucket/freepascal.json``. Re-harvest with
## ``repro_catalog_harvester harvest --bucket ScoopInstaller/Main
## --app freepascal --app-alias freepascal=fpc`` to pick up an upstream
## upgrade. Do NOT hand-edit the digest in isolation: a digest that
## does not match the bytes the realize-loop's HTTP fetch returns will
## fail closed with ``EBuiltinDigestMismatch``.
##
## **Runtime behaviour.** The M64 realize loop accepts the slice but
## prints ``WSha1HashAccepted: fpc — verifying via sha1 (upstream-
## provided; weak)`` to stderr on every realize. Bump the catalog
## entry to sha256/sha512 (and remove this header note) when the
## upstream Scoop manifest upgrades.
##
## **Re-harvest preservation.** This hand-edited docstring is the
## only deviation from the harvester's auto-generated output. Anyone
## re-running the harvester must reattach this header (the harvester
## clobbers the file body and the `## Auto-generated` marker below).

## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 3.2.2

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let fpcCatalog* = @[
  VersionedProvisioning(
    version: "3.2.2",
    archive_format: afRaw,
    install_method: imInstallerInnoSetup,
    bin_relpath: @["bin\\i386-win32\\fp.exe", "bin\\i386-win32\\fpc.exe"],
    platforms: @[
      PlatformBinary(cpu: pcAny, os: poWindows, url: "https://downloads.sourceforge.net/project/freepascal/Win32/3.2.2/fpc-3.2.2.i386-win32.exe", sha256: "", sha512: "", sha1: "c3fc24290da7349e4fba763eaadd2a5bec07bfa3", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
