## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: gh-releases:brechtsanders/winlibs_mingw
## Versions (newest-first): 16.1.0posix-14.0.0-ucrt-r2

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let gcc_winlibsCatalog* = @[
  VersionedProvisioning(
    version: "16.1.0posix-14.0.0-ucrt-r2",
    archive_format: afSevenZip,
    install_method: imExtract,
    bin_relpath: @["bin/gcc.exe", "bin/g++.exe", "bin/gfortran.exe", "bin/ld.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/16.1.0posix-14.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-16.1.0-mingw-w64ucrt-14.0.0-r2.7z", sha256: "62fb8588d2deee7d662dbcbd386702adbf19643764c971c38aa4839472eee232", sha512: "", sha1: "", extract_path: "mingw64")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
