## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 9.12.1

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let ghcCatalog* = @[
  VersionedProvisioning(
    version: "9.12.1",
    archive_format: afTarXz,
    install_method: imExtract,
    bin_relpath: @["bin\\ghc.exe", "bin\\ghci.exe", "bin\\ghc-pkg.exe", "bin\\haddock.exe", "bin\\hp2ps.exe", "bin\\hpc.exe", "bin\\hsc2hs.exe", "bin\\runghc.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://downloads.haskell.org/~ghc/9.12.1/ghc-9.12.1-x86_64-unknown-mingw32.tar.xz", sha256: "22dc942be1b968d5e28e75c06aba52829d0c52d9234bc9941df9ab2a0e2a610d", sha512: "", extract_path: "ghc-9.12.1-x86_64-unknown-mingw32")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
