## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 9.12.1
##
## **M9.5 merge note (hand-edited):** added a ``(pcX86_64, poLinux)``
## platform slice manually (GHC ships on ``downloads.haskell.org``,
## not GitHub — so the M7 gh-releases harvester doesn't apply). URL
## pattern: ``ghc-<ver>-x86_64-centos7-linux.tar.xz``; sha256 lifted
## from upstream's ``SHA256SUMS``. The CentOS 7 build is selected
## because it floors at glibc 2.17 (RHEL 7) — directly matches the
## M9.5 spec's "glibc-2.17-compatible Linux tarballs" honest-scope
## target. archive_format stays afTarXz (same as Windows), but the
## inner dir is ``ghc-<ver>/`` (vs. the Windows mingw32 variant) and
## binaries lack the .exe suffix → both encoded via the M9.5
## per-platform overrides.

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let ghcCatalog* = @[
  VersionedProvisioning(
    version: "9.12.1",
    archive_format: afTarXz,
    install_method: imExtract,
    bin_relpath: @["bin\\ghc.exe", "bin\\ghci.exe", "bin\\ghc-pkg.exe", "bin\\haddock.exe", "bin\\hp2ps.exe", "bin\\hpc.exe", "bin\\hsc2hs.exe", "bin\\runghc.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://downloads.haskell.org/~ghc/9.12.1/ghc-9.12.1-x86_64-unknown-mingw32.tar.xz", sha256: "22dc942be1b968d5e28e75c06aba52829d0c52d9234bc9941df9ab2a0e2a610d", sha512: "", extract_path: "ghc-9.12.1-x86_64-unknown-mingw32"),
      # M9.5: Linux x86_64 slice. CentOS 7 build (glibc 2.17 floor).
      # NOTE: GHC's Linux tarball uses a different inner-dir scheme than
      # the Windows mingw32 archive — it ships under ``ghc-<ver>/`` and
      # requires a ``./configure && make install`` step to materialize
      # the bin shape; the cakBuiltin realize loop's M9.5 best-effort
      # extracts into the prefix and the binaries land under
      # ``ghc-9.12.1/bin/``. Operators using the LIVE WSL harness should
      # invoke the ``configure`` step manually (or use cakNix via the
      # M65 chain's first arm).
      PlatformBinary(cpu: pcX86_64, os: poLinux, url: "https://downloads.haskell.org/~ghc/9.12.1/ghc-9.12.1-x86_64-centos7-linux.tar.xz", sha256: "13b211eaacb85a3579e3523b0178ecc41a95486edd2fb7c82edcbb71981ffdc9", sha512: "", sha1: "", extract_path: "ghc-9.12.1", bin_relpath_override: @["bin/ghc-9.12.1", "bin/ghci-9.12.1", "bin/ghc-pkg-9.12.1", "bin/haddock-ghc-9.12.1", "bin/hp2ps", "bin/hpc", "bin/hsc2hs", "bin/runghc-9.12.1"])
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
