## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 9.5.1, 8.10.2
##
## M69 merge note (hand-edited): the ``env: {"GRADLE_HOME": "${prefix}"}``
## entry below is a hand-merged M69 addition. ``GRADLE_HOME`` is the
## conventional environment variable that Gradle itself, IDEs, and the
## M41 kotlin-gradle Tier 2b probe consult; it is exported by
## ``D:/metacraft/env.ps1`` at line 407 against the metacraft-dev-deps
## prefix. The harvester does NOT auto-detect this binding from the
## Scoop manifest (Scoop's ``env_set`` block carries no ``GRADLE_HOME``
## for this package), so re-harvesting this file blanks the ``env``
## table and the cakBuiltin realizer would emit no ``GRADLE_HOME``
## resource. Re-attach this ``env`` entry by hand if you regenerate.
## Mirrors the M67 ruby / M68 nim merged-files pattern.
##
## M2 merge note (hand-edited, 2026-05-31): the 8.10.2 slice below is
## hand-merged to preserve the Gradle 8.x LTS line as a backfill for
## the ``GRADLE_VERSION=8.10.2`` pin in
## ``windows/toolchain-versions.env``. Gradle 9 (the HEAD slice) is a
## major-version bump; the M2 reconciliation kept env.ps1 on 8.x and
## grew the catalog with the historical slice so operators on a
## migrated home.nim resolve cleanly without forcing the major bump.
## URL + SHA-256 lifted from Scoop bucket commit ``df9c451c53`` (the
## "gradle: Update to version 8.10.2" commit on ScoopInstaller/Main).
## The ``--version-history`` harvester walk reproduces both slices
## byte-identically *modulo* this merge note + the ``GRADLE_HOME``
## env entry — verify drift on this file is expected per the M67 /
## M68 pattern.
##
## **M9.5 merge note (hand-edited):** added a ``(pcX86_64, poLinux)``
## platform slice to BOTH the 9.5.1 and 8.10.2 versions. Gradle ships
## a universal cross-platform ``-all.zip`` (or ``-bin.zip``) — same
## archive, same sha256 across OSes. The Linux launcher is ``bin/gradle``
## (the bash launcher script) vs. the Windows ``bin\\gradle.bat`` —
## bin_relpath_override carries the platform-specific basename.
## archive_format stays afZip; URL + sha256 are identical between the
## Windows and Linux PlatformBinary entries. As a portable Java app,
## glibc floor is whatever the underlying JDK enforces.

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let gradleCatalog* = @[
  VersionedProvisioning(
    version: "9.5.1",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin\\gradle.bat"],
    platforms: @[
      PlatformBinary(cpu: pcAny, os: poWindows, url: "https://services.gradle.org/distributions/gradle-9.5.1-all.zip", sha256: "c72fb9991f6025cbe337d52ba77e531b3faf62bdd3e348fe1ccee9f51c71adb0", sha512: "", extract_path: "gradle-9.5.1"),
      # M9.5: Linux x86_64 slice (9.5.1). Same universal archive +
      # sha256 as Windows; bin_relpath_override drops the .bat suffix
      # for the bash launcher.
      PlatformBinary(cpu: pcX86_64, os: poLinux, url: "https://services.gradle.org/distributions/gradle-9.5.1-all.zip", sha256: "c72fb9991f6025cbe337d52ba77e531b3faf62bdd3e348fe1ccee9f51c71adb0", sha512: "", sha1: "", extract_path: "gradle-9.5.1", bin_relpath_override: @["bin/gradle"])
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"GRADLE_HOME": "${prefix}"}.toTable()),
  VersionedProvisioning(
    version: "8.10.2",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin\\gradle.bat"],
    platforms: @[
      PlatformBinary(cpu: pcAny, os: poWindows, url: "https://services.gradle.org/distributions/gradle-8.10.2-all.zip", sha256: "2ab88d6de2c23e6adae7363ae6e29cbdd2a709e992929b48b6530fd0c7133bd6", sha512: "", extract_path: "gradle-8.10.2"),
      # M9.5: Linux x86_64 slice (8.10.2). Same universal archive +
      # sha256 as Windows.
      PlatformBinary(cpu: pcX86_64, os: poLinux, url: "https://services.gradle.org/distributions/gradle-8.10.2-all.zip", sha256: "2ab88d6de2c23e6adae7363ae6e29cbdd2a709e992929b48b6530fd0c7133bd6", sha512: "", sha1: "", extract_path: "gradle-8.10.2", bin_relpath_override: @["bin/gradle"])
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"GRADLE_HOME": "${prefix}"}.toTable())
]
