## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 9.5.1
##
## M69 merge note (hand-edited): the ``env: {"GRADLE_HOME": "${prefix}"}``
## entry below is a hand-merged M69 addition. ``GRADLE_HOME`` is the
## conventional environment variable that Gradle itself, IDEs, and the
## M41 kotlin-gradle Tier 2b probe consult; it is exported by
## ``D:/metacraft/env.ps1`` at line 407 against the metacraft-dev-deps
## prefix. The harvester does NOT auto-detect this binding from the
## Scoop manifest (Scoop's ``env_set`` block carries no ``GRADLE_HOME``
## for this package), so re-harvesting this file blanks the ``env``
## table and the cakBuiltin realizer would emit no ``GRADLE_HOME``
## resource. Re-attach this ``env`` entry by hand if you regenerate.
## Mirrors the M67 ruby / M68 nim merged-files pattern.

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let gradleCatalog* = @[
  VersionedProvisioning(
    version: "9.5.1",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin\\gradle.bat"],
    platforms: @[
      PlatformBinary(cpu: pcAny, os: poWindows, url: "https://services.gradle.org/distributions/gradle-9.5.1-all.zip", sha256: "c72fb9991f6025cbe337d52ba77e531b3faf62bdd3e348fe1ccee9f51c71adb0", sha512: "", extract_path: "gradle-9.5.1")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"GRADLE_HOME": "${prefix}"}.toTable())
]
