## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: gh-releases:mstorsjo/llvm-mingw
## Versions (newest-first): 20260519

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let llvm_mingwCatalog* = @[
  VersionedProvisioning(
    version: "20260519",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin/clang.exe", "bin/clang++.exe", "bin/ld.lld.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/mstorsjo/llvm-mingw/releases/download/20260519/llvm-mingw-20260519-ucrt-x86_64.zip", sha256: "72dbd6e64614e3b3401998992d1bd9c8ace29e74611d71c80309ea71c3fb26f9", sha512: "", sha1: "", extract_path: "llvm-mingw-20260519-ucrt-x86_64")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
