## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 3.9.16

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let mavenCatalog* = @[
  VersionedProvisioning(
    version: "3.9.16",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["bin/mvn.cmd", "bin/mvn"],
    platforms: @[
      PlatformBinary(cpu: pcAny, os: poWindows, url: "https://dlcdn.apache.org/maven/maven-3/3.9.16/binaries/apache-maven-3.9.16-bin.zip", sha256: "", sha512: "ed41650d42485cfc243fad22158caf9cbb5dc408ce7a09ddb94dd42a019de929ca43065bfa450612cf12bf78b5cafa3884b96c090de326ff590448c933454af3", extract_path: "apache-maven-3.9.16")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
