## M4 (Realize-Closure-And-Catalog-Expansion spec) merge note: the
## ``install_method`` flipped from ``imExtract`` (M68 default for any
## non-installer-block manifest) to ``imInstallerMsi`` so the cakBuiltin
## realize loop dispatches through the M4 MSI extractor instead of
## raising ``afInstallerMsi`` + ``imExtract`` is incompatible at apply
## time.
##
## **M4 amendment** (post-live-smoke finding): the MSI extractor is
## ``lessmsi`` (NOT WiX dark.exe as the M4 spec text originally
## proposed). lessmsi writes files at the MSI's logical install
## hierarchy under ``<destDir>/SourceDir/<MSI's install path>/`` —
## so ``extract_path`` is ``SourceDir\\PFiles64\\Meson`` (was
## ``PFiles64\\Meson`` per the Scoop manifest, which is correct under
## msiexec /a but NOT under lessmsi). See
## ``packages/lessmsi.nim`` for the rationale.
##
## **Unblock target**: M71 deferred-8 row for meson. After M4 the row
## flips to CLEAN (the MSI extraction produces ``meson.exe`` at the
## prefix root via the ``SourceDir\Meson`` extract_path flatten).

## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 1.11.0

import std/tables
import repro_project_dsl
import repro_dsl_stdlib/packages_schema
export packages_schema

# ---------------------------------------------------------------------------
# M9.P stop-gap: hand-authored ``package meson:`` DSL block carrying
# the provisioning shape the M9 tool-identity resolver needs to map a
# ``uses: "meson"`` recipe declaration into a concrete adapter
# (nix on Nix-capable hosts, scoop or tarball on Windows / non-Nix
# Linux). The downstream ``mesonCatalog`` slice below remains intact
# for the M64 ``cakBuiltin`` adapter on Windows.
#
# The tarball pin points at meson 1.6.1's source release. The upstream
# tarball lays out ``meson-1.6.1/`` at the root and ships ``meson.py``
# directly inside (no shell wrapper); ``stripComponents = 1`` flattens
# the tree so the realized prefix carries ``meson.py`` at its root.
# ``executablePath = "meson.py"`` reflects the actual layout — the
# resolver invokes it via ``python meson.py`` on hosts that have a
# Python interpreter on PATH (covered by the recipe's ``uses:`` /
# convention layer).
#
# The architectural fix (M9.Q) is a new ``tpmFromSource`` mode + a
# resolver pre-pass that schedules from-source builds for build tools
# such as meson. This stop-gap unblocks the M9.P smoke today by giving
# the resolver something actionable for ``uses: "meson"``.

package meson:
  provisioning:
    nixPackage "nixpkgs#meson", executablePath = "bin/meson",
      nixpkgsRev = "addf7cf5f383a3101ecfba091b98d0a1263dc9b8",
      nixpkgsNarHash = "sha256-hM20uyap1a0M9d344I692r+ik4gTMyj60cQWO+hAYP8="
    # Windows / non-Nix Linux: meson via ScoopInstaller/Main. The Scoop
    # manifest installs the upstream MSI (handled by the M4 lessmsi
    # extractor downstream); the Scoop side surfaces ``meson.exe`` at
    # the prefix root.
    scoopApp(bucket = "main", app = "meson",
      preferredVersion = ">=1", executablePath = "meson.exe",
      requiresExecutionProfileChecksum = false)
    # Direct-download: meson source release from GitHub Releases.
    # Cross-platform — works on any host with Python 3 on PATH. The
    # tarball ships ``meson.py`` at the root of ``meson-1.6.1/`` so
    # ``stripComponents = 1`` lands ``meson.py`` at the realized
    # prefix root.
    tarball url = "https://github.com/mesonbuild/meson/releases/download/1.6.1/meson-1.6.1.tar.gz",
      sha256 = "1eca49eb6c26d58bbee67fd3337d8ef557c0804e30a6d16bfdf269db997464de",
      archiveType = "tar.gz",
      stripComponents = 1,
      executablePath = "meson.py",
      packageId = "meson@1.6.1",
      cpu = "any",
      os = "any",
      lockIdentity = "tarball:meson@1.6.1:sha256:1eca49eb6c26d58bbee67fd3337d8ef557c0804e30a6d16bfdf269db997464de"

  # -------------------------------------------------------------------
  # DSL-port M9.R.2 — typed Layer-3 CLI surface for ``meson``.
  #
  # Recipes can now write ``meson.setup(srcDir = ..., buildDir = ...,
  # prefix = ...)`` / ``meson.compile(buildDir = ...)`` /
  # ``meson.install(buildDir = ..., destdir = ...)`` instead of inline
  # ``sh.call(["meson", "setup", ...])``. The typed wrapper records a
  # ``BuildActionDef`` whose ``call.arguments`` carry the role-tagged
  # flag + positional values; the engine + action-cache use those for
  # input/output fingerprinting.
  #
  # Positional order matches the meson CLI: ``meson setup <buildDir>
  # <srcDir>`` — the build directory comes first, source directory
  # second. (See https://mesonbuild.com/Commands.html#setup.) ``compile``
  # / ``install`` / ``dist`` take ``-C <buildDir>`` only.
  # -------------------------------------------------------------------
  executable mesonBin:
    cli:
      dependencyPolicy automaticMonitor

      subcmd "setup":
        flag prefix is string,
          alias = "--prefix=",
          format = concat
        flag buildtype is string,
          alias = "--buildtype=",
          format = concat
        flag options is seq[string],
          alias = "-D",
          format = concat,
          repeated = true
        flag crossFile is string,
          alias = "--cross-file=",
          format = concat
        flag nativeFile is string,
          alias = "--native-file=",
          format = concat
        pos buildDir is string,
          position = 0,
          role = output
        pos srcDir is string,
          position = 1,
          role = input

        outputs buildDir

      subcmd "compile":
        flag workDir is string,
          alias = "-C",
          format = separate,
          role = input
        flag jobs is int,
          alias = "-j",
          format = separate

      subcmd "install":
        flag workDir is string,
          alias = "-C",
          format = separate,
          role = input
        flag destdir is string,
          alias = "--destdir=",
          format = concat,
          role = output
        flag tags is seq[string],
          alias = "--tags=",
          format = concat,
          repeated = true

      subcmd "dist":
        flag workDir is string,
          alias = "-C",
          format = separate,
          role = input
        flag formats is seq[string],
          alias = "--formats=",
          format = concat,
          repeated = true

let mesonCatalog* = @[
  VersionedProvisioning(
    version: "1.11.0",
    archive_format: afInstallerMsi,
    install_method: imInstallerMsi,
    bin_relpath: @["meson.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/mesonbuild/meson/releases/download/1.11.0/meson-1.11.0-64.msi", sha256: "ea8f6e328294fd2adc508a10d3a656b3c00c83cadc619a18fba19f2b589c3101", sha512: "", extract_path: "SourceDir\\PFiles64\\Meson")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
