## M4 (Realize-Closure-And-Catalog-Expansion spec) merge note: the
## ``install_method`` flipped from ``imExtract`` (M68 default for any
## non-installer-block manifest) to ``imInstallerMsi`` so the cakBuiltin
## realize loop dispatches through the M4 MSI extractor instead of
## raising ``afInstallerMsi`` + ``imExtract`` is incompatible at apply
## time.
##
## **M4 amendment** (post-live-smoke finding): the MSI extractor is
## ``lessmsi`` (NOT WiX dark.exe as the M4 spec text originally
## proposed). lessmsi writes files at the MSI's logical install
## hierarchy under ``<destDir>/SourceDir/<MSI's install path>/`` —
## so ``extract_path`` is ``SourceDir\\PFiles64\\Meson`` (was
## ``PFiles64\\Meson`` per the Scoop manifest, which is correct under
## msiexec /a but NOT under lessmsi). See
## ``packages/lessmsi.nim`` for the rationale.
##
## **Unblock target**: M71 deferred-8 row for meson. After M4 the row
## flips to CLEAN (the MSI extraction produces ``meson.exe`` at the
## prefix root via the ``SourceDir\Meson`` extract_path flatten).

## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 1.11.0

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let mesonCatalog* = @[
  VersionedProvisioning(
    version: "1.11.0",
    archive_format: afInstallerMsi,
    install_method: imInstallerMsi,
    bin_relpath: @["meson.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/mesonbuild/meson/releases/download/1.11.0/meson-1.11.0-64.msi", sha256: "ea8f6e328294fd2adc508a10d3a656b3c00c83cadc619a18fba19f2b589c3101", sha512: "", extract_path: "SourceDir\\PFiles64\\Meson")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
