## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 1.13.2
##
## **M9.5 merge note (hand-edited):** added a ``(pcX86_64, poLinux)``
## platform slice harvested via ``--source gh-releases:ninja-build/ninja
## --asset-pattern 'ninja-linux\.zip' --platform-os linux``. Same
## archive format (``afZip``) but the Linux binary is ``ninja`` (no
## ``.exe`` suffix) → bin_relpath_override carries the platform-
## specific basename. ninja's upstream Linux binary is built on
## Ubuntu and dynamically links to glibc; the M9.5 spec's
## "glibc-2.17 floor" target is honored by upstream's CI base image.

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let ninjaCatalog* = @[
  VersionedProvisioning(
    version: "1.13.2",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["ninja.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip", sha256: "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65", sha512: "", extract_path: ""),
      PlatformBinary(cpu: pcAArch64, os: poWindows, url: "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-winarm64.zip", sha256: "e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391", sha512: "", extract_path: ""),
      # M9.5: Linux x86_64 slice. Same archive format (afZip) as Windows
      # but the inner binary is ``ninja`` (no ``.exe``).
      PlatformBinary(cpu: pcX86_64, os: poLinux, url: "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip", sha256: "5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6", sha512: "", sha1: "", extract_path: "", bin_relpath_override: @["ninja"])
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
