## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 1.13.2
##
## **M9.5 merge note (hand-edited):** added a ``(pcX86_64, poLinux)``
## platform slice harvested via ``--source gh-releases:ninja-build/ninja
## --asset-pattern 'ninja-linux\.zip' --platform-os linux``. Same
## archive format (``afZip``) but the Linux binary is ``ninja`` (no
## ``.exe`` suffix) → bin_relpath_override carries the platform-
## specific basename. ninja's upstream Linux binary is built on
## Ubuntu and dynamically links to glibc; the M9.5 spec's
## "glibc-2.17 floor" target is honored by upstream's CI base image.

import std/tables
import repro_project_dsl
import repro_dsl_stdlib/nixpkgs_pin
import repro_dsl_stdlib/packages_schema
# DSL-port M9.R.2c — typed slot var for ``executable ninjaBin:``.
import repro_dsl_stdlib/types/executable
export packages_schema

# ---------------------------------------------------------------------------
# M9.P stop-gap: hand-authored ``package ninja:`` DSL block carrying
# the provisioning shape the M9 tool-identity resolver needs to map
# ``uses: "ninja"`` recipe declarations into a concrete adapter
# (nix on Nix-capable hosts; scoop or tarball on Windows / non-Nix
# Linux). The downstream ``ninjaCatalog`` slice below remains intact
# for the M64 ``cakBuiltin`` adapter on Windows.
#
# Direct-download pins use the official ninja-build/ninja v1.13.2
# release artifacts. The Windows ``ninja-win.zip`` and Linux
# ``ninja-linux.zip`` ship the ``ninja.exe`` / ``ninja`` binary flat
# at the archive root (no enclosing directory), so ``stripComponents``
# stays at 0.
#
# The architectural fix (M9.Q) is a new ``tpmFromSource`` mode + a
# resolver pre-pass that schedules from-source builds for build tools
# such as ninja. This stop-gap unblocks the M9.P smoke today by giving
# the resolver something actionable for ``uses: "ninja"``.

package ninja:
  provisioning:
    nixPackage "nixpkgs#ninja", executablePath = "bin/ninja",
      nixpkgsRev = CanonicalNixpkgsRev,
      nixpkgsNarHash = CanonicalNixpkgsNarHash
    # Windows / non-Nix Linux: ninja via ScoopInstaller/Main.
    scoopApp(bucket = "main", app = "ninja",
      preferredVersion = ">=1", executablePath = "ninja.exe",
      requiresExecutionProfileChecksum = false)
    # Direct-download: ninja v1.13.2 Windows binary release. The .zip
    # ships ``ninja.exe`` flat at the archive root.
    tarball url = "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip",
      sha256 = "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65",
      archiveType = "zip",
      executablePath = "ninja.exe",
      packageId = "ninja@1.13.2",
      cpu = "x86_64",
      os = "windows",
      lockIdentity = "tarball:ninja@1.13.2:sha256:07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65"
    # Windows aarch64. Upstream has published `ninja-winarm64.zip` since
    # 1.12; it is absent here only because nothing had asked for it. Digest
    # matches the `NINJA_SHA256_WIN_ARM64` pin Agent Harbor harvested
    # independently.
    tarball url = "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-winarm64.zip",
      sha256 = "e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391",
      archiveType = "zip",
      executablePath = "ninja.exe",
      packageId = "ninja@1.13.2",
      cpu = "aarch64",
      os = "windows",
      lockIdentity = "tarball:ninja@1.13.2:windows-aarch64:sha256:e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391"
    # Direct-download: ninja v1.13.2 Linux binary release. The .zip
    # ships ``ninja`` (no .exe suffix) flat at the archive root.
    # ninja's upstream Linux build targets glibc 2.17 on its CI base
    # image — matches the M9.5 honest-scope target.
    tarball url = "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip",
      sha256 = "5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6",
      archiveType = "zip",
      executablePath = "ninja",
      packageId = "ninja@1.13.2-linux",
      cpu = "x86_64",
      os = "linux",
      lockIdentity = "tarball:ninja@1.13.2-linux:sha256:5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6"

  # -------------------------------------------------------------------
  # DSL-port M9.R.2 — typed Layer-3 CLI surface for ``ninja``.
  #
  # Recipes write ``ninja.call(workDir = "./b", target = "all")`` instead
  # of an inline ``sh.call(["ninja", "-C", "./b", "all"])``. Ninja has
  # no subcommands (it's a single-mode build driver); the typed call
  # block uses the ``call:`` (no-subcmd) shape — same convention as
  # ``gcc.call(...)``. Positional targets are passed via ``targets:
  # seq[string]``.
  # -------------------------------------------------------------------
  executable ninjaBin:
    cli:
      dependencyPolicy automaticMonitor

      call:
        flag workDir is string,
          alias = "-C",
          format = separate,
          role = input
        flag file is string,
          alias = "-f",
          format = separate,
          role = input
        flag jobs is int,
          alias = "-j",
          format = separate
        flag tool is string,
          alias = "-t",
          format = separate
        pos targets is seq[string],
          position = 0,
          role = input,
          repeated = true

let ninjaCatalog* = @[
  VersionedProvisioning(
    version: "1.13.2",
    archive_format: afZip,
    install_method: imExtract,
    bin_relpath: @["ninja.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip", sha256: "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65", sha512: "", extract_path: ""),
      PlatformBinary(cpu: pcAArch64, os: poWindows, url: "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-winarm64.zip", sha256: "e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391", sha512: "", extract_path: ""),
      # M9.5: Linux x86_64 slice. Same archive format (afZip) as Windows
      # but the inner binary is ``ninja`` (no ``.exe``).
      PlatformBinary(cpu: pcX86_64, os: poLinux, url: "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip", sha256: "5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6", sha512: "", sha1: "", extract_path: "", bin_relpath_override: @["ninja"])
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
