## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: msys2:mingw64/ocaml
## Versions (newest-first): 5.4.1-2

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let ocamlCatalog* = @[
  VersionedProvisioning(
    version: "5.4.1-2",
    archive_format: afTarZst,
    install_method: imMsys2Pacman,
    bin_relpath: @["bin/ocaml.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-ocaml-5.4.1-2-any.pkg.tar.zst", sha256: "8510b89feaf0ad861f813e88901d1b61745168a1019488eb4706c6f8b0a3ae2d", sha512: "", sha1: "", extract_path: "mingw64")
    ],
    installer_args: @[],
    pacman_packages: @["mingw-w64-x86_64-ocaml"],
    bootstrap_argv: @[],
    env: initTable[string, string]())
]
