## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 4.0.5-1
##
## M67 merge note (hand-edited): the auto-generated body sits below
## the pre-existing M21 ``package ruby:`` Nix block. Keep the two in
## sync — the Nix block remains the source of truth for Nix-capable
## hosts, while the ``rubyCatalog`` slice below is consumed by the
## M64 ``cakBuiltin`` adapter on Windows. Re-harvest emits ONLY the
## catalog half; re-attach the Nix block by hand if you regenerate.
## The ``--bin-default`` invocation used:
##   --bin-default "ruby=ruby.exe,gem.cmd,bundle.cmd,rake.cmd,irb.cmd"
## synthesizes ``bin_relpath`` from the manifest's ``env_add_path``
## (``bin`` + ``gems\bin``); the cross-product produces 10 candidate
## relpaths so the realize loop can probe both prefixes.

import std/tables
import repro_project_dsl
import repro_dsl_stdlib/packages_schema
export packages_schema

# ---------------------------------------------------------------------------
# Pre-existing M21 Nix provisioning (preserved across the M67 harvest).
# ---------------------------------------------------------------------------

package ruby:
  provisioning:
    nixPackage "nixpkgs#ruby", executablePath = "bin/ruby",
      nixpkgsRev = "addf7cf5f383a3101ecfba091b98d0a1263dc9b8",
      nixpkgsNarHash = "sha256-hM20uyap1a0M9d344I692r+ik4gTMyj60cQWO+hAYP8="

# ---------------------------------------------------------------------------
# M67 bulk-harvest catalog (cakBuiltin adapter consumer on Windows).
# ---------------------------------------------------------------------------

let rubyCatalog* = @[
  VersionedProvisioning(
    version: "4.0.5-1",
    archive_format: afSevenZip,
    install_method: imExtract,
    bin_relpath: @["bin/ruby.exe", "bin/gem.cmd", "bin/bundle.cmd", "bin/rake.cmd", "bin/irb.cmd", "gems/bin/ruby.exe", "gems/bin/gem.cmd", "gems/bin/bundle.cmd", "gems/bin/rake.cmd", "gems/bin/irb.cmd"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-4.0.5-1/rubyinstaller-4.0.5-1-x64.7z", sha256: "74e31613fc71e6e23431dfc4d8b6ec2818a4dc1fd16e0983b074144c16719c8b", sha512: "", extract_path: "rubyinstaller-4.0.5-1-x64"),
      PlatformBinary(cpu: pcAArch64, os: poWindows, url: "https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-4.0.5-1/rubyinstaller-4.0.5-1-arm.7z", sha256: "c7c6bcd0b070bf7c2e0c03e70fb9754d022b8a216ebc4befab880874c6180b51", sha512: "", extract_path: "rubyinstaller-4.0.5-1-arm")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"GEM_HOME": "${prefix}\\gems"}.toTable())
]
