## Auto-generated by tools/catalog-harvester. DO NOT EDIT.
## Harvested from bucket: ScoopInstaller/Main
## Versions (newest-first): 6.3.1

import std/tables
import repro_dsl_stdlib/packages_schema
export packages_schema

let swiftCatalog* = @[
  VersionedProvisioning(
    version: "6.3.1",
    archive_format: afRaw,
    install_method: imExtract,
    bin_relpath: @["Runtimes/usr/bin/swift.exe", "Runtimes/usr/bin/swiftc.exe", "Toolchains/usr/bin/swift.exe", "Toolchains/usr/bin/swiftc.exe"],
    platforms: @[
      PlatformBinary(cpu: pcX86_64, os: poWindows, url: "https://download.swift.org/swift-6.3.1-release/windows10/swift-6.3.1-RELEASE/swift-6.3.1-RELEASE-windows10.exe", sha256: "e5a0e6b5bd8f8f3045b1d2420c06eceb6b7918d800bec3733ce4d657e7170f51", sha512: "", extract_path: ""),
      PlatformBinary(cpu: pcAArch64, os: poWindows, url: "https://download.swift.org/swift-6.3.1-release/windows10-arm64/swift-6.3.1-RELEASE/swift-6.3.1-RELEASE-windows10-arm64.exe", sha256: "9e99e2dde52df516e7ea1ff151d9cb296629d5274e7820f71635ae78a86975fd", sha512: "", extract_path: "")
    ],
    installer_args: @[],
    pacman_packages: @[],
    bootstrap_argv: @[],
    env: {"SDKROOT": "${prefix}\\Platforms\\Windows.platform\\Developer\\SDKs\\Windows.sdk"}.toTable())
]
