## Reading `Cargo.lock` into a crates.io vendor plan.
##
## The plan is what lets a from-source Rust package build offline: every
## transitive dependency, its download URL, and the SHA-256 to verify it
## against, all taken from the lockfile rather than from a resolver.
##
## What is asserted here is mostly what the reader REFUSES. A plan that is
## short by one crate does not fail here — it fails much later, inside
## cargo, with a message about a missing crate rather than about a lockfile,
## on whichever machine first tries to build offline. So every construct the
## reader does not understand exactly has to raise at the point where the
## lockfile is read, and each of those refusals has a case below.

import std/[strutils, unittest]

import repro_core/cargo_lock

const MinimalLock = """
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "just"
version = "1.51.0"
dependencies = [
 "ansi_term",
 "camino",
]

[[package]]
name = "ansi_term"
version = "0.12.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d52a9bb7ec0cf484c551830a7ce27bd20d67eac647e1befb56b0be4ee39a55d2"

[[package]]
name = "camino"
version = "1.1.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8b96ec4966b5813e2c0507c1f86115c8c5abaadc3980879c3424042a02fd1ad3"
"""

suite "Cargo.lock vendor plan":
  test "registry dependencies become a sorted, hash-carrying plan":
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    check plan.len == 2
    # Sorted by name, not file order: the plan feeds a content-addressed
    # step, so two hosts reading the same lockfile must produce the same
    # bytes, and cargo's own ordering is not part of the file's contract.
    check plan[0].name == "ansi_term"
    check plan[1].name == "camino"
    check plan[0].url ==
      "https://static.crates.io/crates/ansi_term/ansi_term-0.12.1.crate"
    check plan[0].sha256 ==
      "d52a9bb7ec0cf484c551830a7ce27bd20d67eac647e1befb56b0be4ee39a55d2"
    check plan[0].directoryName == "ansi_term-0.12.1"

  test "the package being built is not in its own plan":
    # `just` has no `source`, because it is the workspace member the
    # recipe is building. A plan that tried to download it would be
    # asking crates.io for the thing it already has.
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    for entry in plan:
      check entry.name != "just"

  test "the sparse index spelling is the same crates.io":
    # Cargo writes `sparse+https://index.crates.io/` since it defaulted to
    # the sparse protocol. Treating that as an unknown source would refuse
    # every lockfile generated by a current cargo.
    let lock = MinimalLock.replace(
      "registry+https://github.com/rust-lang/crates.io-index",
      "sparse+https://index.crates.io/")
    let plan = vendorPlan(parseCargoLock(lock))
    check plan.len == 2
    check plan[0].url.startsWith("https://static.crates.io/crates/")

  test "a git dependency is refused rather than dropped":
    # Silently skipping it yields a plan that looks complete and a build
    # that fails offline for a reason nothing reported.
    let lock = MinimalLock.replace(
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n" &
      "checksum = \"d52a9bb7ec0cf484c551830a7ce27bd20d67eac647e1befb56b0be4ee39a55d2\"",
      "source = \"git+https://github.com/ogham/rust-ansi-term?rev=abc#abc\"")
    expect CargoLockError:
      discard vendorPlan(parseCargoLock(lock))

  test "a registry dependency with no checksum is refused":
    let lock = MinimalLock.replace(
      "checksum = \"d52a9bb7ec0cf484c551830a7ce27bd20d67eac647e1befb56b0be4ee39a55d2\"\n",
      "")
    expect CargoLockError:
      discard vendorPlan(parseCargoLock(lock))

  test "a malformed checksum is refused":
    let lock = MinimalLock.replace(
      "d52a9bb7ec0cf484c551830a7ce27bd20d67eac647e1befb56b0be4ee39a55d2",
      "NOTHEX")
    expect CargoLockError:
      discard vendorPlan(parseCargoLock(lock))

  test "an unsupported lockfile version is refused":
    # v1 keeps checksums in a trailing `[metadata]` table, which is a
    # different parse. Accepting the version number while reading it as
    # v3 would produce a plan with no checksums at all.
    let lock = MinimalLock.replace("version = 3", "version = 1")
    expect CargoLockError:
      discard parseCargoLock(lock)

  test "a lockfile with no version key is refused":
    let lock = MinimalLock.replace("version = 3\n", "")
    expect CargoLockError:
      discard parseCargoLock(lock)

  test "an unrecognised key inside a package entry is refused":
    # The whole reason for a hand-written reader: an unknown construct is
    # a signal that cargo's format moved, and guessing past it is how a
    # plan silently loses a crate.
    let lock = MinimalLock.replace(
      "name = \"camino\"", "name = \"camino\"\nreplace = \"camino 1.0.0\"")
    expect CargoLockError:
      discard parseCargoLock(lock)

  test "a comment containing a hash inside a string survives":
    # `#` is a comment introducer everywhere except inside a quoted
    # string, and a git source URL carries one before its revision. The
    # refusal below has to be about the SOURCE, not about a truncated
    # line.
    let lock = MinimalLock.replace(
      "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
      "source = \"git+https://example.invalid/x?rev=deadbeef#deadbeef\"")
    var message = ""
    try:
      discard vendorPlan(parseCargoLock(lock))
    except CargoLockError as err:
      message = err.msg
    check message.contains("not crates.io")
    check message.contains("deadbeef")

  test "the same crate twice with the same checksum collapses":
    let doubled = MinimalLock & """

[[package]]
name = "camino"
version = "1.1.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8b96ec4966b5813e2c0507c1f86115c8c5abaadc3980879c3424042a02fd1ad3"
"""
    check vendorPlan(parseCargoLock(doubled)).len == 2

  test "the same crate twice with different checksums is refused":
    let conflicting = MinimalLock & """

[[package]]
name = "camino"
version = "1.1.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
"""
    expect CargoLockError:
      discard vendorPlan(parseCargoLock(conflicting))

  test "the emitted cargo config replaces both index spellings":
    # Replacing only the spelling this lockfile happens to name leaves
    # the other live, and a build that reaches the network for one crate
    # is not an offline build — it is an offline build with an
    # intermittent failure.
    let config = cargoVendorConfig("C:/work/vendor")
    check config.contains("[source.crates-io]")
    check config.contains("[source.\"sparse+https://index.crates.io/\"]")
    check config.count("replace-with = \"vendored-sources\"") == 2
    # Forward slashes: cargo reads this as TOML, where a backslash is an
    # escape introducer.
    check config.contains("directory = \"C:/work/vendor\"")

  test "the per-crate checksum file carries the lockfile digest":
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    let json = cargoChecksumJson(plan[0])
    check json.contains("\"package\":\"" & plan[0].sha256 & "\"")
    check json.contains("\"files\":{}")

  test "a plan round-trips through its committed manifest":
    # The manifest is what a recipe commits, because the lockfile it came
    # from does not exist at graph-emission time — it arrives with the
    # source the fetch action has not run yet. Pinning the closure beside
    # the recipe is what makes it reviewable and diffable rather than
    # invisible until a build is already running.
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    let restored = parseVendorManifest(renderVendorManifest(plan))
    check restored.len == plan.len
    for i in 0 ..< plan.len:
      check restored[i].url == plan[i].url
      check restored[i].sha256 == plan[i].sha256
      check restored[i].directoryName == plan[i].directoryName
      # Name and version are recovered from the directory name rather
      # than carried as their own columns: two spellings of the same fact
      # can disagree, and the directory name is what the fetch step and
      # cargo both use.
      check restored[i].name == plan[i].name
      check restored[i].version == plan[i].version

  test "the manifest is a shell-readable table":
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    let lines = renderVendorManifest(plan).strip().splitLines()
    check lines[0] == VendorManifestHeader
    # Three tab-separated fields per line, because the consumer is a
    # `while IFS=<tab> read -r url sha dir` loop and not a parser.
    for line in lines[1 .. ^1]:
      check line.split('\t').len == 3

  test "a manifest without the version header is refused":
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    let headerless = renderVendorManifest(plan).replace(
      VendorManifestHeader & "\n", "")
    expect CargoLockError:
      discard parseVendorManifest(headerless)

  test "a truncated manifest line is refused rather than skipped":
    # A skipped line is a crate that goes missing, and a build missing one
    # dependency fails inside cargo rather than here.
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    let broken = renderVendorManifest(plan).replace(
      "\tansi_term-0.12.1", "")
    expect CargoLockError:
      discard parseVendorManifest(broken)

  test "a manifest url outside crates.io is refused":
    let plan = vendorPlan(parseCargoLock(MinimalLock))
    let elsewhere = renderVendorManifest(plan).replace(
      "https://static.crates.io/crates/", "https://example.invalid/")
    expect CargoLockError:
      discard parseVendorManifest(elsewhere)
