/* M73 Phase 5 — GetProcAddress dispatch for NtCreateFile (ntdll backstop).
 *
 * NtCreateFile lives in ntdll, not kernel32. Per Monitor-Hook-Shim.md
 * §"NT Native APIs" it is the canonical lower-layer entry point for
 * file open/probe/create/write classification. Phase 5 adds it to the
 * hookTable with its own moduleDll = "ntdll.dll" and a deferred-path
 * snoop body (the path lives inside OBJECT_ATTRIBUTES.ObjectName and
 * extraction is a Phase 6+ task).
 *
 * This fixture proves the install + dispatch wiring lands a snoop
 * record per call. We use GetProcAddress(ntdll.dll, "NtCreateFile")
 * (mechanism 2 — runtime-resolved) because there is no public Win32
 * import library shim for NtCreateFile, and mingw's <winternl.h>
 * forward declarations don't link cleanly without the DDK headers.
 *
 * Invocation: fixture_ntcreatefile_getproc.exe <marker> <count>
 *
 * For each i in [0, count):
 *   - Build an OBJECT_ATTRIBUTES with an NT-style \??\<marker>.<i>.txt
 *     path and call NtCreateFile to open/create the file.
 *   - The depfile MUST contain at least one mrFileOpen record with
 *     detail "NtCreateFile" per call. The Phase 5 snoop body deferred
 *     path extraction so record.path is "" — the test counts records
 *     by detail+kind, not by marker, since the path is intentionally
 *     blank.
 *
 * NOTE: NtCreateFile is invoked transitively by CreateFileW itself, so
 * a CreateFileW call also fires the NtCreateFile snoop one level down.
 * The test must therefore (a) NOT call CreateFileW around the
 * NtCreateFile call (we use NtClose directly), and (b) account for the
 * baseline NtCreateFile fires generated by the process bootstrap
 * (loader, CRT init, etc.) — the test asserts the count is GREATER
 * THAN OR EQUAL TO N rather than strict equality, since we can't
 * predict how many incidental NtCreateFile calls the runtime makes.
 *
 * This is the one acceptable deviation from "strict equality" in the
 * Phase 5 dispatch-mechanism test: the surface under test (NtCreateFile)
 * is a process-wide lower layer that's unavoidably exercised by the
 * runtime before main() returns. The acceptance criterion is "the snoop
 * FIRES", which an inequality >= N captures.
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

/* Hand-rolled UNICODE_STRING / OBJECT_ATTRIBUTES / IO_STATUS_BLOCK so we
 * don't need the DDK headers. Matches phnt / winternl layouts. */
typedef struct _UNICODE_STRING {
  USHORT Length;
  USHORT MaximumLength;
  PWSTR Buffer;
} UNICODE_STRING, *PUNICODE_STRING;

typedef struct _OBJECT_ATTRIBUTES {
  ULONG Length;
  HANDLE RootDirectory;
  PUNICODE_STRING ObjectName;
  ULONG Attributes;
  PVOID SecurityDescriptor;
  PVOID SecurityQualityOfService;
} OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;

typedef struct _IO_STATUS_BLOCK {
  union {
    LONG Status;
    PVOID Pointer;
  } u;
  ULONG_PTR Information;
} IO_STATUS_BLOCK, *PIO_STATUS_BLOCK;

#define OBJ_CASE_INSENSITIVE 0x40

typedef LONG (NTAPI *NtCreateFile_fn)(
  PHANDLE FileHandle,
  ACCESS_MASK DesiredAccess,
  POBJECT_ATTRIBUTES ObjectAttributes,
  PIO_STATUS_BLOCK IoStatusBlock,
  PLARGE_INTEGER AllocationSize,
  ULONG FileAttributes,
  ULONG ShareAccess,
  ULONG CreateDisposition,
  ULONG CreateOptions,
  PVOID EaBuffer,
  ULONG EaLength);

typedef LONG (NTAPI *NtClose_fn)(HANDLE Handle);

/* CreateDisposition constants (per ntifs.h / phnt). */
#define FILE_OPEN_IF       0x00000003
#define FILE_NON_DIRECTORY_FILE 0x00000040
#define FILE_SYNCHRONOUS_IO_NONALERT 0x00000020

int wmain(int argc, wchar_t **argv) {
  if (argc != 3) {
    fwprintf(stderr, L"usage: %s <marker> <count>\n", argv[0]);
    return 2;
  }
  const wchar_t *marker = argv[1];
  int count = _wtoi(argv[2]);
  if (count <= 0) {
    fwprintf(stderr, L"count must be > 0\n");
    return 2;
  }

  HMODULE ntdll = GetModuleHandleW(L"ntdll.dll");
  if (ntdll == NULL) {
    fwprintf(stderr, L"GetModuleHandleW(ntdll.dll) returned NULL\n");
    return 3;
  }
  NtCreateFile_fn pNtCreateFile =
    (NtCreateFile_fn)GetProcAddress(ntdll, "NtCreateFile");
  NtClose_fn pNtClose = (NtClose_fn)GetProcAddress(ntdll, "NtClose");
  if (pNtCreateFile == NULL || pNtClose == NULL) {
    fwprintf(stderr, L"GetProcAddress(NtCreateFile/NtClose) returned NULL\n");
    return 3;
  }

  for (int i = 0; i < count; ++i) {
    /* NT object-namespace prefix: \??\ is the DosDevices alias.
     * Convert the marker (a Win32 path like C:\Users\...) by
     * prepending \??\. */
    wchar_t ntpath[1024];
    _snwprintf(ntpath, 1024, L"\\??\\%s.%d.txt", marker, i);
    ntpath[1023] = L'\0';

    UNICODE_STRING u;
    USHORT wlen = (USHORT)(wcslen(ntpath) * sizeof(wchar_t));
    u.Length = wlen;
    u.MaximumLength = wlen;
    u.Buffer = ntpath;

    OBJECT_ATTRIBUTES oa;
    memset(&oa, 0, sizeof(oa));
    oa.Length = sizeof(oa);
    oa.RootDirectory = NULL;
    oa.ObjectName = &u;
    oa.Attributes = OBJ_CASE_INSENSITIVE;
    oa.SecurityDescriptor = NULL;
    oa.SecurityQualityOfService = NULL;

    IO_STATUS_BLOCK iosb;
    memset(&iosb, 0, sizeof(iosb));

    HANDLE h = NULL;
    LONG status = pNtCreateFile(
      &h,
      0x80000000 | 0x100000,  /* GENERIC_READ | SYNCHRONIZE */
      &oa,
      &iosb,
      NULL,                    /* AllocationSize */
      0x80,                    /* FILE_ATTRIBUTE_NORMAL */
      0x7,                     /* FILE_SHARE_READ|WRITE|DELETE */
      FILE_OPEN_IF,
      FILE_NON_DIRECTORY_FILE | FILE_SYNCHRONOUS_IO_NONALERT,
      NULL, 0);
    if (status >= 0 && h != NULL) {
      pNtClose(h);
    } else {
      fwprintf(stderr, L"NtCreateFile failed for %s (status=0x%08lx)\n",
        ntpath, (unsigned long)status);
    }
  }
  return 0;
}
